module.exports = [
  // =================== 1 à 50 ===================
  { name: "Pikachu", type: ["Électrik"], techniques: { A: "Éclair", X: "Tonnerre", Y: "Queue de fer" } },
  { name: "Raichu", type: ["Électrik"], techniques: { A: "Éclair rapide", X: "Tonnerre suprême", Y: "Agilité" } },
  { name: "Bulbizarre", type: ["Plante", "Poison"], techniques: { A: "Fouet lianes", X: "Tempête verte", Y: "Soin de feuilles" } },
  { name: "Herbizarre", type: ["Plante", "Poison"], techniques: { A: "Lianes frappantes", X: "Explosion florale", Y: "Soin végétal" } },
  { name: "Florizarre", type: ["Plante", "Poison"], techniques: { A: "Griffe florale", X: "Tempête ultime", Y: "Bouclier vert" } },
  { name: "Salamèche", type: ["Feu"], techniques: { A: "Flammèche", X: "Lance-Flammes", Y: "Danse du feu" } },
  { name: "Reptincel", type: ["Feu"], techniques: { A: "Flamme rapide", X: "Inferno", Y: "Agilité" } },
  { name: "Dracaufeu", type: ["Feu", "Vol"], techniques: { A: "Flamme", X: "Déflagration", Y: "Vol rapide" } },
  { name: "Carapuce", type: ["Eau"], techniques: { A: "Pistolet à eau", X: "Hydrocanon", Y: "Bouclier d'eau" } },
  { name: "Carabaffe", type: ["Eau"], techniques: { A: "Coup de queue", X: "Vague extrême", Y: "Bouclier aquatique" } },
  { name: "Tortank", type: ["Eau"], techniques: { A: "Hydroqueue", X: "Tsunami", Y: "Protection aqueuse" } },
  { name: "Chenipan", type: ["Insecte"], techniques: { A: "Morsure", X: "Cocon piquant", Y: "Bouclier chitine" } },
  { name: "Chrysacier", type: ["Insecte"], techniques: { A: "Écrasement", X: "Explosion chrysale", Y: "Bouclier solide" } },
  { name: "Papilusion", type: ["Insecte", "Vol"], techniques: { A: "Poudre toxique", X: "Tempête papillon", Y: "Agilité" } },
  { name: "Aspicot", type: ["Insecte", "Poison"], techniques: { A: "Dard", X: "Piège venimeux", Y: "Carapace solide" } },
  { name: "Coconfort", type: ["Insecte", "Poison"], techniques: { A: "Choc piquant", X: "Explosion toxique", Y: "Bouclier" } },
  { name: "Dardargnan", type: ["Insecte", "Poison"], techniques: { A: "Dard venimeux", X: "Furie ultime", Y: "Esquive" } },
  { name: "Roucool", type: ["Vol", "Normal"], techniques: { A: "Bec tranchant", X: "Vent furieux", Y: "Esquive" } },
  { name: "Roucoups", type: ["Vol", "Normal"], techniques: { A: "Pic tranchant", X: "Ouragan", Y: "Agilité" } },
  { name: "Roucarnage", type: ["Vol", "Normal"], techniques: { A: "Frappe aérienne", X: "Tempête suprême", Y: "Bouclier" } },
  { name: "Rattata", type: ["Normal"], techniques: { A: "Morsure rapide", X: "Furie", Y: "Esquive" } },
  { name: "Rattatac", type: ["Normal"], techniques: { A: "Coup de crocs", X: "Furie rapide", Y: "Agilité" } },
  { name: "Sabelette", type: ["Sol"], techniques: { A: "Griffe sable", X: "Tempête de sable", Y: "Bouclier" } },
  { name: "Sablaireau", type: ["Sol"], techniques: { A: "Coup de griffe", X: "Furie sable", Y: "Bouclier" } },
  { name: "Nidoran♀", type: ["Poison"], techniques: { A: "Charge", X: "Dard Venin", Y: "Agilité" } },
  { name: "Nidorina", type: ["Poison"], techniques: { A: "Coup de corne", X: "Furie Venin", Y: "Esquive" } },
  { name: "Nidoqueen", type: ["Poison", "Sol"], techniques: { A: "Coup puissant", X: "Frappe ultime", Y: "Bouclier" } },
  { name: "Nidoran♂", type: ["Poison"], techniques: { A: "Charge rapide", X: "Dard venin", Y: "Agilité" } },
  { name: "Nidorino", type: ["Poison"], techniques: { A: "Coup de corne", X: "Frappe rapide", Y: "Esquive" } },
  { name: "Nidoking", type: ["Poison", "Sol"], techniques: { A: "Frappe puissante", X: "Coup de tonnerre", Y: "Bouclier" } },
  { name: "Mélofée", type: ["Fée"], techniques: { A: "Choc mignon", X: "Pouvoir lunaire", Y: "Soin" } },
  { name: "Mélodelfe", type: ["Fée"], techniques: { A: "Chant puissant", X: "Lune magique", Y: "Bouclier" } },
  { name: "Goupix", type: ["Feu"], techniques: { A: "Flammèche", X: "Feu follet", Y: "Agilité" } },
  { name: "Feunard", type: ["Feu"], techniques: { A: "Ruade", X: "Explosion de flammes", Y: "Bouclier" } },
  { name: "Goupix-Alola", type: ["Glace"], techniques: { A: "Flammèche glaciale", X: "Blizzard", Y: "Soin" } },
  { name: "Feunard-Alola", type: ["Glace"], techniques: { A: "Ruade glaciale", X: "Blizzard ultime", Y: "Bouclier" } },
  { name: "Nosferapti", type: ["Poison", "Vol"], techniques: { A: "Crocs", X: "Hurlement", Y: "Agilité" } },
  { name: "Nosferalto", type: ["Poison", "Vol"], techniques: { A: "Morsure", X: "Coup de vent", Y: "Esquive" } },
  { name: "Mystherbe", type: ["Plante", "Poison"], techniques: { A: "Fouet lianes", X: "Poison poudre", Y: "Bouclier" } },
  { name: "Ortide", type: ["Plante", "Poison"], techniques: { A: "Fouet lianes", X: "Explosion verte", Y: "Agilité" } },
  { name: "Rafflesia", type: ["Plante", "Poison"], techniques: { A: "Griffe florale", X: "Explosion florale", Y: "Bouclier" } },
  { name: "Parasar", type: ["Insecte", "Plante"], techniques: { A: "Spore", X: "Poussière", Y: "Agilité" } },
  { name: "Parasect", type: ["Insecte", "Plante"], techniques: { A: "Poussée", X: "Explosion spores", Y: "Bouclier" } },
  { name: "Mimitoss", type: ["Insecte", "Poison"], techniques: { A: "Piqûre", X: "Explosion toxique", Y: "Esquive" } },
  { name: "Aéromite", type: ["Insecte", "Poison"], techniques: { A: "Vent piquant", X: "Tempête toxique", Y: "Bouclier" } },
  { name: "Taupiqueur", type: ["Sol"], techniques: { A: "Fouille", X: "Tunnel", Y: "Agilité" } },
  { name: "Triopikeur", type: ["Sol"], techniques: { A: "Frappe souterraine", X: "Séisme", Y: "Bouclier" } },
  { name: "Miaouss", type: ["Normal"], techniques: { A: "Griffe", X: "Coup rapide", Y: "Agilité" } },
  { name: "Persian", type: ["Normal"], techniques: { A: "Coup de patte", X: "Furie", Y: "Esquive" } },
  { name: "Psykokwak", type: ["Eau"], techniques: { A: "Bec", X: "Hydrocanon", Y: "Agilité" } },
  { name: "Akwakwak", type: ["Eau"], techniques: { A: "Psyko", X: "Hydrocanon", Y: "Bouclier" } },
  { name: "Férosinge", type: ["Combat"], techniques: { A: "Poing Karaté", X: "Coup circulaire", Y: "Agilité" } },
  { name: "Colossinge", type: ["Combat"], techniques: { A: "Coup de poing", X: "Coup violent", Y: "Bouclier" } },
  { name: "Caninos", type: ["Feu"], techniques: { A: "Flammèche", X: "Crocs feu", Y: "Agilité" } },
  { name: "Arcanin", type: ["Feu"], techniques: { A: "Flamme rapide", X: "Déflagration", Y: "Bouclier" } },

  // =================== 51 à 100 ===================
  { name: "Ptitard", type: ["Eau"], techniques: { A: "Pistolet à eau", X: "Vague", Y: "Agilité" } },
  { name: "Têtarte", type: ["Eau"], techniques: { A: "Bulles", X: "Hydrocanon", Y: "Bouclier" } },
  { name: "Tartard", type: ["Eau", "Combat"], techniques: { A: "Coup puissant", X: "Hydro-poing", Y: "Agilité" } },
  { name: "Abra", type: ["Psy"], techniques: { A: "Choc mental", X: "Téléport", Y: "Bouclier" } },
  { name: "Kadabra", type: ["Psy"], techniques: { A: "Choc psy", X: "Télékinésie", Y: "Agilité" } },
  { name: "Alakazam", type: ["Psy"], techniques: { A: "Explosion mentale", X: "Télépathie", Y: "Bouclier" } },
  { name: "Machoc", type: ["Combat"], techniques: { A: "Poing", X: "Coup violent", Y: "Agilité" } },
  { name: "Machopeur", type: ["Combat"], techniques: { A: "Coup puissant", X: "Coup de poing", Y: "Bouclier" } },
  { name: "Mackogneur", type: ["Combat"], techniques: { A: "Frappe ultime", X: "Poing explosif", Y: "Agilité" } },
  { name: "Chétiflor", type: ["Plante", "Poison"], techniques: { A: "Fouet lianes", X: "Explosion verte", Y: "Bouclier" } },
  { name: "Boustiflor", type: ["Plante", "Poison"], techniques: { A: "Fouet puissant", X: "Tempête verte", Y: "Soin" } },
  { name: "Empiflor", type: ["Plante", "Poison"], techniques: { A: "Griffe florale", X: "Tempête florale", Y: "Bouclier" } },
  { name: "Tentacool", type: ["Eau", "Poison"], techniques: { A: "Piqûre", X: "Tentacule", Y: "Agilité" } },
  { name: "Tentacruel", type: ["Eau", "Poison"], techniques: { A: "Tentacule puissant", X: "Acide", Y: "Bouclier" } },
  { name: "Racaillou", type: ["Roche", "Sol"], techniques: { A: "Coup de rocher", X: "Séisme", Y: "Bouclier" } },
  { name: "Gravalanch", type: ["Roche", "Sol"], techniques: { A: "Griffe rocheuse", X: "Lance pierre", Y: "Agilité" } },
  { name: "Grolem", type: ["Roche", "Sol"], techniques: { A: "Coup de poing roche", X: "Séisme puissant", Y: "Bouclier" } },
  { name: "Ponyta", type: ["Feu"], techniques: { A: "Charge flamme", X: "Ruade", Y: "Agilité" } },
  { name: "Galopa", type: ["Feu"], techniques: { A: "Flamme rapide", X: "Déflagration", Y: "Bouclier" } },
  { name: "Ramoloss", type: ["Eau", "Psy"], techniques: { A: "Psyko", X: "Bulle", Y: "Agilité" } },
  { name: "Flagadoss", type: ["Eau", "Psy"], techniques: { A: "Explosion mentale", X: "Hydrocanon", Y: "Bouclier" } },
  { name: "Magnéti", type: ["Électrik", "Acier"], techniques: { A: "Éclair", X: "Magnétisme", Y: "Agilité" } },
  { name: "Magnéton", type: ["Électrik", "Acier"], techniques: { A: "Tonnerre", X: "Magnétisme puissant", Y: "Bouclier" } },
  { name: "Canarticho", type: ["Combat", "Vol"], techniques: { A: "Coup de pied", X: "Ruade aérienne", Y: "Agilité" } },
  { name: "Doduo", type: ["Normal", "Vol"], techniques: { A: "Pic", X: "Ruade", Y: "Agilité" } },
  { name: "Dodrio", type: ["Normal", "Vol"], techniques: { A: "Coup de bec", X: "Ruade rapide", Y: "Bouclier" } },
  { name: "Otaria", type: ["Eau"], techniques: { A: "Coup d'eau", X: "Hydrocanon", Y: "Bouclier" } },
  { name: "Lamantine", type: ["Eau", "Glace"], techniques: { A: "Pistolet à glace", X: "Blizzard", Y: "Agilité" } },
  { name: "Tadmorv", type: ["Poison"], techniques: { A: "Acide", X: "Explosion toxique", Y: "Bouclier" } }

];
