const questions = [
  { question: "Quel est le nom du physicien qui a découvert les rayons X ?", answer: "Wilhelm Röntgen" },
  { question: "Quel écrivain a refusé le prix Nobel de littérature en 1964 ?", answer: "Jean-Paul Sartre" },
  { question: "Quel est le plus ancien parlement encore en activité au monde ?", answer: "Althing (Islande)" },
  { question: "Quel pays a le plus grand nombre d'îles au monde ?", answer: "Suède" },
  { question: "Quelle est la capitale du Bhoutan ?", answer: "Thimphou" },
  { question: "Quel empereur romain a légalisé le christianisme ?", answer: "Constantin Ier" },
  { question: "Combien de satellites naturels possède Mars ?", answer: "2" },
  { question: "Dans quelle ville est mort Napoléon Bonaparte ?", answer: "Sainte-Hélène" },
  { question: "Quel est l'élément chimique de numéro atomique 79 ?", answer: "Or" },
  { question: "Quel est le nom du traité qui mit fin à la Première Guerre mondiale ?", answer: "Traité de Versailles" },
  { question: "Quel peintre est l'auteur de 'Guernica' ?", answer: "Pablo Picasso" },
  { question: "En quelle année l’euro a-t-il été introduit comme monnaie fiduciaire ?", answer: "2002" },
  { question: "Quel mathématicien grec a donné son nom à un théorème célèbre ?", answer: "Pythagore" },
  { question: "Quelle est la langue officielle de l’Éthiopie ?", answer: "Amharique" },
  { question: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", answer: "8 minutes" },
  { question: "Quel philosophe est l'auteur de 'Critique de la raison pure' ?", answer: "Emmanuel Kant" },
  { question: "Dans quel pays trouve-t-on la ville de Samarcande ?", answer: "Ouzbékistan" },
  { question: "Quel est le plus grand désert froid du monde ?", answer: "Antarctique" },
  { question: "Qui a découvert la pénicilline ?", answer: "Alexander Fleming" },
  { question: "Quel est l'acide présent dans l'estomac humain ?", answer: "Acide chlorhydrique" },
  { question: "En quelle année a eu lieu le krach boursier de Wall Street ?", answer: "1929" },
  { question: "Quel est le plus ancien livre imprimé au monde ?", answer: "Le Sūtra du diamant" },
  { question: "Qui a peint 'Le Jardin des délices' ?", answer: "Jérôme Bosch" },
  { question: "Quel écrivain est l’auteur de 'L'Étranger' ?", answer: "Albert Camus" },
  { question: "Quel organe du corps humain produit l'insuline ?", answer: "Pancréas" },
  { question: "Quel est le nom du premier satellite artificiel lancé dans l’espace ?", answer: "Spoutnik" },
  { question: "Qui a théorisé la relativité restreinte ?", answer: "Albert Einstein" },
  { question: "Quel pays a inventé l’imprimerie à caractères mobiles ?", answer: "Chine" }, 
  
  { question: "Quel footballeur a remporté le plus de Ballons d'Or ?", answer: "lionel messi" },
  { question: "Quel pays a remporté la première Coupe du Monde de football en 1930 ?", answer: "uruguay" },
  { question: "Combien de fois Rafael Nadal a-t-il gagné Roland-Garros ?", answer: "14" },
  { question: "Quel est le record du monde du 100m masculin ?", answer: "9.58" },
  { question: "Dans quel sport excelle Simone Biles ?", answer: "gymnastique" },
  { question: "Combien de joueurs sur le terrain pour une équipe de rugby à XV ?", answer: "15" },
  { question: "Quel pays a organisé les Jeux Olympiques de 1964 ?", answer: "japon" },
  { question: "Qui a marqué la 'main de Dieu' ?", answer: "diego maradona" },
  { question: "Quel est le sport le plus pratiqué au monde ?", answer: "football" },
  { question: "Combien de grands chelems existent en tennis ?", answer: "4" },
  { question: "Quel coureur a remporté le plus de Tours de France ?", answer: "eddy merckx" },
  { question: "Quel est le surnom du boxeur Mohamed Ali ?", answer: "the greatest" },
  { question: "Quel est le sport national au Japon ?", answer: "sumo" },
  { question: "Quel pays a gagné la CAN 2012 ?", answer: "zambie" },
  { question: "Quel nageur détient le record de médailles olympiques ?", answer: "michael phelps" },
  { question: "Quel joueur de tennis est surnommé 'le roi de la terre battue' ?", answer: "rafael nadal" },
  { question: "Quel footballeur a joué pour l'ajax, le barça et manchester united ?", answer: "zlatan ibrahimovic" },
  { question: "Combien de minutes dure un match de handball ?", answer: "60" },
  { question: "Quel est le nom du stade du real madrid ?", answer: "santiago bernabeu" },
  { question: "Qui a remporté le Ballon d'Or 2006 ?", answer: "fabio cannavaro" },
  { question: "Dans quel sport utilise-t-on un 'cocktail molotov' comme stratégie ?", answer: "paintball" },
  { question: "Quel joueur a marqué le but de la victoire pour l'espagne en finale de la coupe du monde 2010 ?", answer: "andres iniesta" },
  { question: "Combien de trous dans un parcours de golf standard ?", answer: "18" },
  { question: "Dans quel sport utilise-t-on un sabre ?", answer: "escrime" },
  { question: "Qui est le seul athlète à avoir couru le 200 m en moins de 19.20 s ?", answer: "usain bolt" },
  { question: "Quel pays a remporté le plus de coupes du monde de football ?", answer: "bresil" },
  { question: "Quel club de foot a remporté la ligue des champions en 1999 ?", answer: "manchester united" },
  { question: "Dans quelle ville se trouve le stade de l'olympique lyonnais ?", answer: "decines" },
  { question: "Quel est le record du monde du saut à la perche masculin ?", answer: "6.23" },
  { question: "Combien de fois la france a-t-elle gagné la coupe du monde de foot ?", answer: "2" },
  { question: "Quel joueur détient le record de buts en une seule saison de premier league ?", answer: "erling haaland" },
  { question: "Dans quel sport retrouve-t-on des 'rebonds' et des 'rebonds défensifs' ?", answer: "basketball" },
  { question: "Quel joueur est surnommé 'el fenomeno' ?", answer: "ronaldo" },
  { question: "Combien de sets faut-il gagner pour remporter un match en grand chelem masculin ?", answer: "3" },
  { question: "Quel pays a inventé le hockey sur glace ?", answer: "canada" },
  { question: "Quel joueur argentin est surnommé 'la pulga' ?", answer: "lionel messi" },
  { question: "Quelle est la distance officielle d’un marathon ?", answer: "42.195" },
  { question: "Quel pays a gagné le mondial 2006 ?", answer: "italie" },
  { question: "Qui est le joueur le plus capé de l’histoire de l’équipe de france de football ?", answer: "hugo lloris" },
  { question: "Quelle nation a remporté la coupe du monde de rugby en 2019 ?", answer: "afrique du sud" },
  { question: "Dans quel sport joue-t-on avec une raquette et un volant ?", answer: "badminton" },
  { question: "Quel est le sport d'équipe le plus rapide ?", answer: "hockey sur glace" },
  { question: "Quel joueur a remporté le ballon d’or 2007 ?", answer: "kaka" },
  { question: "Dans quelle ville se trouve le stade anfield ?", answer: "liverpool" },
  { question: "Quel basketteur est surnommé 'king james' ?", answer: "lebron james" },
  { question: "Quel est le poids d’un ballon de football réglementaire ?", answer: "450 grammes" },
  { question: "Combien de joueurs dans une équipe de volley ?", answer: "6" },
  { question: "Quel est le pays hôte des JO 2024 ?", answer: "france" },
  { question: "Quel joueur a remporté le plus de grands chelems en tennis ?", answer: "novak djokovic" },
  { question: "Quel sport est aussi appelé 'le noble art' ?", answer: "boxe" },
  { question: "Qui a gagné l'euro 2004 ?", answer: "grece" },
  { question: "Dans quel sport utilise-t-on un 'grip' et un 'service' ?", answer: "tennis" },
  { question: "Quel footballeur a joué pour liverpool, barcelone et bayern munich ?", answer: "philippe coutinho" },
  { question: "Combien de médailles olympiques a gagné la france en 2020 ?", answer: "33" },
  { question: "Dans quel sport utilise-t-on une planche appelée 'deck' ?", answer: "skateboard" },
  { question: "Quel est le sport de michael jordan ?", answer: "basketball" },
  { question: "Combien de kilomètres dans un 10k ?", answer: "10" },
  { question: "Quel est le nom du championnat anglais de football ?", answer: "premier league" },
  { question: "Combien de temps dure un match de basket nba ?", answer: "48 minutes" },
  { question: "Quel pays est surnommé la selecao ?", answer: "bresil" },
  { question: "Combien de médailles d'or a remporté bolt aux jeux olympiques ?", answer: "8" },
  { question: "Dans quel pays est né kylian mbappe ?", answer: "france" },
  { question: "Quel sport est pratiqué lors du superbowl ?", answer: "football americain" },
  { question: "Quel est le plus grand stade d’europe en capacité ?", answer: "camp nou" },
  { question: "Combien de quarts-temps dans un match de basket ?", answer: "4" },
  { question: "Quel est le surnom de l’équipe nationale d’allemagne ?", answer: "mannschaft" },
  { question: "Quel pays est le plus titré en coupe d’afrique des nations ?", answer: "egypte" },
  { question: "Combien de médailles a remporté phelps en tout ?", answer: "28" },
  { question: "Quel pays a organisé les jeux olympiques d’hiver 2022 ?", answer: "chine" },
  { question: "Quel joueur est célèbre pour sa 'main de dieu' ?", answer: "diego maradona" },
  { question: "Quelle nation est surnommée 'les lions indomptables' ?", answer: "cameroun" },
  { question: "Dans quel sport est-ce que tony parker a brillé ?", answer: "basketball" },
  { question: "Qui est le gardien mythique de l'italie championne du monde 2006 ?", answer: "gianluigi buffon" },
  { question: "Quel pays a remporté la coupe du monde de cricket en 2019 ?", answer: "angleterre" },
  { question: "Dans quel sport pratique-t-on le 'kata' ?", answer: "karate" },
  { question: "Qui a marqué un triplé en finale de coupe du monde 2022 ?", answer: "kylian mbappe" },
  { question: "Quelle est la couleur du maillot du meilleur grimpeur au tour de france ?", answer: "a pois" },
  { question: "Qui a remporté roland garros en 2023 ?", answer: "novak djokovic" },
  { question: "Dans quel sport le 'triple saut' est-il une épreuve ?", answer: "athletisme" },
  { question: "Quel est le pays d’origine du judo ?", answer: "japon" },
  { question: "Quel footballeur est surnommé 'la panthère' ?", answer: "samuel eto’o" },
  { question: "Quel est le sport le plus regardé au monde ?", answer: "football" },
  { question: "Quelle est la durée maximale d’un match de boxe professionnelle ?", answer: "36 minutes" },
  { question: "Quel est le club surnommé 'les reds' ?", answer: "liverpool" },
  { question: "Combien de fois roger federer a-t-il gagné wimbledon ?", answer: "8" },
  { question: "Quel est le sport du ballon ovale ?", answer: "rugby" },
  { question: "Dans quel sport trouve-t-on le terme 'birdie' ?", answer: "golf" },
  { question: "Qui est le capitaine du senegal en 2022 ?", answer: "kalidou koulibaly" },
  { question: "Dans quel sport est utilisé un arc ?", answer: "tir a l’arc" },
  { question: "Combien de médailles a gagné la france aux jeux paralympiques de tokyo 2020 ?", answer: "54" },
  { question: "Qui est le seul joueur à avoir remporté la coupe du monde comme joueur et entraîneur ?", answer: "mario zagallo" },
  { question: "Quel est le sport le plus populaire aux etats-unis ?", answer: "football americain" },
  
  { question: "🌎 Quel pays possède le drapeau 🇦🇷 ?", answer: "argentine" },
  { question: "🌍 La capitale du 🇳🇬 Nigéria est ?", answer: "abuja" },
  { question: "🌏 À quel pays appartient le drapeau 🇵🇭 ?", answer: "philippines" },
  { question: "🌍 Quelle est la capitale du 🇨🇩 Congo-Kinshasa ?", answer: "kinshasa" },
  { question: "🌎 Quel pays a pour capitale 'nassau' ?", answer: "bahamas" },
  { question: "🌏 Le drapeau 🇳🇵 représente quel pays ?", answer: "népal" },
  { question: "🌍 Quelle capitale se trouve en 🇨🇴 Colombie ?", answer: "bogota" },
  { question: "🌎 Le drapeau 🇧🇹 est celui de quel pays ?", answer: "bhoutan" },
  { question: "🌍 Le pays avec le drapeau 🇲🇳 ?", answer: "mongolie" },
  { question: "🌏 Quelle est la capitale de 🇱🇧 Liban ?", answer: "beyrouth" },
  { question: "🌎 Le drapeau 🇲🇷 appartient à ?", answer: "mauritanie" },
  { question: "🌍 Quelle capitale correspond au drapeau 🇧🇴 ?", answer: "la paz" },
  { question: "🌎 À quel pays appartient le drapeau 🇨🇺 ?", answer: "cuba" },
  { question: "🌍 La capitale de 🇸🇿 Eswatini est ?", answer: "mbabane" },
  { question: "🌏 Le drapeau 🇮🇶 représente quel pays ?", answer: "irak" },
  { question: "🌎 Quelle est la capitale du 🇻🇪 Venezuela ?", answer: "caracas" },
  { question: "🌍 Le drapeau 🇸🇮 correspond à quel pays ?", answer: "slovénie" },
  { question: "🌏 Quelle est la capitale de 🇦🇿 Azerbaïdjan ?", answer: "bakou" },
  { question: "🌎 À quel pays appartient le drapeau 🇬🇶 ?", answer: "guinée équatoriale" },
  { question: "🌍 Quel est le pays avec pour capitale 'dili' ?", answer: "timor oriental" },
  { question: "🌎 Quelle est la capitale du 🇲🇴 Macao ?", answer: "macao" },
  { question: "🌍 Quel drapeau est 🇰🇿 ?", answer: "kazakhstan" },
  { question: "🌏 Quelle capitale pour 🇸🇬 Singapour ?", answer: "singapour" },
  { question: "🌎 Quelle capitale a 🇪🇸 Espagne ?", answer: "madrid" },
  { question: "🌍 Quel pays a le drapeau 🇱🇮 ?", answer: "liechtenstein" },
  { question: "🌎 Le drapeau 🇹🇱 correspond à ?", answer: "timor oriental" },
  { question: "🌍 Quelle capitale pour 🇨🇿 République Tchèque ?", answer: "prague" },
  { question: "🌏 Quel pays a pour capitale 'sana'a' ?", answer: "yémen" },
  { question: "🌍 Le drapeau 🇱🇺 est celui de ?", answer: "luxembourg" },
  { question: "🌎 Quelle capitale pour 🇰🇪 Kenya ?", answer: "nairobi" },
  { question: "🌏 Drapeau 🇦🇲 correspond à quel pays ?", answer: "arménie" },
  { question: "🌍 Quelle est la capitale du 🇵🇾 Paraguay ?", answer: "asuncion" },
  { question: "🌎 Le drapeau 🇲🇱 représente ?", answer: "mali" },
  { question: "🌏 La capitale de 🇷🇸 Serbie est ?", answer: "belgrade" },
  { question: "🌍 Le drapeau 🇸🇳 représente ?", answer: "sénégal" },
  { question: "🌎 Quelle capitale pour 🇮🇩 Indonésie ?", answer: "jakarta" },
  { question: "🌍 Quel pays a le drapeau 🇹🇳 ?", answer: "tunisie" },
  { question: "🌏 Quelle capitale pour 🇳🇿 Nouvelle-Zélande ?", answer: "wellington" },
  { question: "🌍 Le drapeau 🇲🇪 appartient à ?", answer: "monténégro" },
  { question: "🌎 La capitale de 🇮🇱 Israël est ?", answer: "jérusalem" },
  { question: "🌍 Le drapeau 🇹🇿 est à ?", answer: "tanzanie" },
  { question: "🌏 Le pays avec le drapeau 🇦🇴 ?", answer: "angola" },
  { question: "🌎 Quelle est la capitale de 🇸🇰 Slovaquie ?", answer: "bratislava" },
  { question: "🌍 À quel pays correspond le drapeau 🇸🇷 ?", answer: "suriname" },
  { question: "🌎 Quelle est la capitale de 🇱🇸 Lesotho ?", answer: "maseru" },
  { question: "🌍 Le drapeau 🇱🇷 est celui de ?", answer: "libéria" },
  { question: "🌏 Quelle est la capitale de 🇨🇬 Congo-Brazzaville ?", answer: "brazzaville" },
  { question: "🌎 Quelle capitale pour 🇵🇰 Pakistan ?", answer: "islamabad" },
  { question: "🌍 Quel pays a pour capitale 'manama' ?", answer: "bahreïn" },
  { question: "🌏 Drapeau 🇺🇿 représente ?", answer: "ouzbekistan" },
  { question: "🌍 Quelle est la capitale de 🇨🇱 Chili ?", answer: "santiago" },
  { question: "🌎 Le drapeau 🇸🇴 est celui de ?", answer: "somalie" },
  { question: "🌏 Le drapeau 🇲🇲 est à quel pays ?", answer: "myanmar" },
  { question: "🌍 Quelle capitale pour 🇬🇲 Gambie ?", answer: "banjul" },
  { question: "🌎 Le drapeau 🇻🇺 appartient à ?", answer: "vanuatu" },
  { question: "🌍 Quelle capitale pour 🇬🇦 Gabon ?", answer: "libreville" },
  { question: "🌏 Le pays avec la capitale 'astana' ?", answer: "kazakhstan" },
  { question: "🌎 Quelle capitale pour 🇹🇭 Thaïlande ?", answer: "bangkok" },
  { question: "🌍 Quel pays a le drapeau 🇲🇬 ?", answer: "madagascar" },
  { question: "🌏 Quelle est la capitale de 🇮🇷 Iran ?", answer: "téhéran" },
  { question: "🌍 Le drapeau 🇧🇭 représente ?", answer: "bahreïn" },
  { question: "🌎 Quelle capitale pour 🇱🇦 Laos ?", answer: "vientiane" },
  { question: "🌏 À quel pays appartient le drapeau 🇲🇰 ?", answer: "macédoine" },
  { question: "🌍 Quelle est la capitale de 🇲🇻 Maldives ?", answer: "male" },
  { question: "🌎 Quel pays a le drapeau 🇷🇼 ?", answer: "rwanda" },
  { question: "🌏 Quelle capitale a 🇧🇩 Bangladesh ?", answer: "dhaka" },
  { question: "🌍 Le drapeau 🇺🇾 appartient à ?", answer: "uruguay" },
  { question: "🌎 Quelle capitale pour 🇹🇩 Tchad ?", answer: "ndjamena" },
  { question: "🌍 Quel drapeau est 🇸🇿 ?", answer: "eswatini" },
  { question: "🌏 Le pays avec pour capitale 'tashkent' ?", answer: "ouzbekistan" },
  { question: "🌎 Quelle capitale pour 🇲🇺 Maurice ?", answer: "port louis" },
  { question: "🌍 Le drapeau 🇫🇯 est celui de ?", answer: "fidji" },
  { question: "🌏 Quelle capitale pour 🇵🇪 Pérou ?", answer: "lima" },
  { question: "🌍 Le drapeau 🇲🇿 représente ?", answer: "mozambique" },
  { question: "🌎 Quelle est la capitale de 🇸🇩 Soudan ?", answer: "khartoum" },
  { question: "🌏 Drapeau 🇷🇪 est de ?", answer: "réunion" },
  { question: "🌍 Quelle capitale pour 🇬🇳 Guinée ?", answer: "conakry" },
  { question: "🌎 À quel pays appartient le drapeau 🇸🇽 ?", answer: "saint-martin" },
  { question: "🌏 Quelle capitale pour 🇰🇵 Corée du Nord ?", answer: "pyongyang" },
  { question: "🌍 Le drapeau 🇧🇾 appartient à ?", answer: "biélorussie" },
  { question: "🌎 Quelle capitale pour 🇸🇪 Suède ?", answer: "stockholm" },
  { question: "🌍 Quelle capitale pour 🇸🇬 Singapour ?", answer: "singapour" },
  { question: "🌏 Quel pays a la capitale 'georgetown' ?", answer: "guyana" },
  { question: "🌎 Drapeau 🇧🇯 représente ?", answer: "bénin" },
  { question: "🌍 Quelle est la capitale de 🇹🇬 Togo ?", answer: "lomé" },
  { question: "🌎 Quel est le pays du drapeau 🇦🇷 ?", answer: "argentine" },
  { question: "🌍 À quel pays correspond le drapeau 🇬🇹 ?", answer: "guatemala" },
  { question: "🌏 Quelle capitale pour 🇧🇿 Belize ?", answer: "belmopan" },
  { question: "🌍 Quel drapeau est 🇭🇹 ?", answer: "haïti" },
  { question: "🌎 Quelle capitale pour 🇧🇮 Burundi ?", answer: "bujumbura" },
  { question: "🌍 Quelle capitale pour 🇿🇼 Zimbabwe ?", answer: "harare" },
  { question: "🌏 À quel pays correspond le drapeau 🇿🇲 ?", answer: "zambie" },
  { question: "🌍 Quel pays a pour capitale 'doha' ?", answer: "qatar" },
  
  { question: "Dans quel pays se trouve le lac Vostok, enfoui sous la glace ?", answer: "antarctique" },
  { question: "Quelle ville est traversée par le méridien d’origine de Greenwich ?", answer: "londres" },
  { question: "Quel est l’endroit habité en permanence le plus au nord du monde ?", answer: "alert" },
  { question: "Quel pays d’Asie centrale n’a pas de frontière avec la mer ?", answer: "ouzbekistan" },
  { question: "Quel est le plus grand delta fluvial du monde ?", answer: "delta du gange" },
  { question: "Quelle est la seule mer sans côte ?", answer: "mer des sargasses" },
  { question: "Quelle est la plus grande île d’Afrique ?", answer: "madagascar" },
  { question: "Dans quel pays se trouve la région du Cachemire ?", answer: "inde" },
  { question: "Quel pays possède l’enclave de Ceuta ?", answer: "espagne" },
  { question: "Quelle est la capitale du Lesotho ?", answer: "maseru" },
  { question: "Quel fleuve traverse la capitale de l’Angola ?", answer: "kasaï" },
  { question: "Quelle est la plus grande île fluviale du monde ?", answer: "marajó" },
  { question: "Quel est le plus grand glacier continental ?", answer: "glacier lambert" },
  { question: "Quel est le plus ancien désert de la Terre ?", answer: "namib" },
  { question: "Quelle chaîne de montagnes sépare l’Europe de l’Asie ?", answer: "oural" },
  { question: "Quel pays abrite la dépression de Danakil ?", answer: "ethiopie" },
  { question: "Quel est le lac le plus salé de la planète ?", answer: "lac assal" },
  { question: "Quelle ville est située sur deux continents ?", answer: "istanbul" },
  { question: "Quel pays a le plus de fuseaux horaires ?", answer: "france" },
  { question: "Quel est le plus grand canyon du monde ?", answer: "grand canyon" },
  { question: "Quelle ville est la plus méridionale au monde ?", answer: "puerto williams" },
  { question: "Quelle est la plus grande presqu'île au monde ?", answer: "péninsule arabique" },
  { question: "Quel est le pays enclavé entre l’Autriche et la Suisse ?", answer: "liechtenstein" },
  { question: "Quel pays a le plus grand nombre de voisins terrestres ?", answer: "chine" },
  { question: "Quelle est la capitale de l’Érythrée ?", answer: "asmara" },
  { question: "Quel est le plus haut sommet d’Amérique du Nord ?", answer: "denali" },
  { question: "Quel pays d’Afrique n’a jamais été colonisé ?", answer: "ethiopie" },
  { question: "Quelle est la plus petite mer du monde ?", answer: "mer d’azov" },
  { question: "Quel est le seul pays traversé par l’équateur et le méridien de Greenwich ?", answer: "gabon" },
  { question: "Quel est le pays le plus plat du monde ?", answer: "maldives" },
  { question: "Dans quel pays se situe le détroit de Béring ?", answer: "russie" },
  { question: "Quel est le lac partagé par le Pérou et la Bolivie ?", answer: "titicaca" },
  { question: "Quel est le plus grand volcan actif ?", answer: "mauna loa" },
  { question: "Quel pays africain a la plus grande superficie ?", answer: "algérie" },
  { question: "Quelle est la capitale de la Papouasie-Nouvelle-Guinée ?", answer: "port moresby" },
  { question: "Quel pays a le plus grand réseau fluvial ?", answer: "brésil" },
  { question: "Quelle est la capitale du Suriname ?", answer: "paramaribo" },
  { question: "Quel est le point le plus bas de la Terre ?", answer: "mer morte" },
  { question: "Quel pays possède la plus grande zone économique exclusive ?", answer: "états-unis" },
  { question: "Quel fleuve forme une frontière naturelle entre Israël et la Jordanie ?", answer: "jourdain" },
  { question: "Quelle est la plus haute cascade du monde ?", answer: "salto angel" },
  { question: "Quelle ville est appelée la Venise du Nord ?", answer: "bruges" },
  { question: "Quel pays a la plus grande réserve de pétrole prouvée ?", answer: "venezuela" },
  { question: "Quel pays est divisé en cantons ?", answer: "suisse" },
  { question: "Quel est le plus long tunnel ferroviaire du monde ?", answer: "gotthard" },
  { question: "Quel est l’unique fleuve qui traverse l’équateur deux fois ?", answer: "congo" },
  { question: "Quel pays possède le fjord le plus long ?", answer: "norvège" },
  { question: "Quel est le volcan le plus haut du monde ?", answer: "ojos del salado" },
  { question: "Quel est le plus petit continent ?", answer: "océanie" },
  { question: "Quel est l’État le moins peuplé au monde ?", answer: "vatican" },
  { question: "Quel pays a pour capitale N’Djamena ?", answer: "tchad" },
  { question: "Quel est le plus haut plateau du monde ?", answer: "tibet" },
  { question: "Quel est le seul lac avec un écosystème marin en altitude ?", answer: "baïkal" },
  { question: "Quel est le détroit qui sépare l’Europe de l’Asie ?", answer: "bosphore" },
  { question: "Quel pays est formé de plus de 17 000 îles ?", answer: "indonésie" },
  { question: "Quelle île est considérée comme le plus vieux morceau de terre émergée ?", answer: "madagascar" },
  { question: "Quel est le point le plus oriental de la France ?", answer: "île de la réunion" },
  { question: "Quel fleuve traverse Vienne ?", answer: "danube" },
  { question: "Quel est le plus petit pays enclavé d’Afrique ?", answer: "burundi" },
  { question: "Quel est le pays le plus montagneux du monde ?", answer: "népal" },
  { question: "Quelle capitale est située sur les rives du fleuve Niger ?", answer: "niamey" },
  { question: "Quel pays est le plus touché par les séismes ?", answer: "japon" },
  { question: "Quel est le volcan le plus actif d’Indonésie ?", answer: "merapi" },
  { question: "Quel pays est situé entre le Togo et la Côte d’Ivoire ?", answer: "ghana" },
  { question: "Quel est le seul pays d’Afrique qui touche la mer Rouge et l’océan Indien ?", answer: "somalie" },
  { question: "Quel fleuve est sacré pour les hindous ?", answer: "gange" },
  { question: "Quel est le plus grand pays d’Océanie ?", answer: "australie" },
  { question: "Quel pays est surnommé « le toit du monde » ?", answer: "népal" },
  { question: "Quel est le principal fleuve d’Irak ?", answer: "euphrate" },
  { question: "Quelle chaîne de montagnes traverse l’Amérique du Sud ?", answer: "andes" },
  { question: "Quel est le plus grand archipel du monde ?", answer: "indonésie" },
  { question: "Quel est le climat dominant de la savane ?", answer: "tropical" },
  { question: "Quel pays possède les chutes Victoria ?", answer: "zambie" },
  { question: "Quel est le lac entre la Zambie et la Tanzanie ?", answer: "tanganyika" },
  { question: "Quel est le pays où se trouve le mont Everest ?", answer: "népal" },
  { question: "Quel fleuve traverse la ville de Paris ?", answer: "seine" },
  { question: "Quel pays est connu pour ses nombreux geysers ?", answer: "islande" },
  { question: "Quel est le plus long fleuve d’Europe ?", answer: "volga" },
  { question: "Quel est le seul pays du monde sans capitale officielle ?", answer: "nauru" },
  { question: "Quel pays se trouve au sud du Mexique ?", answer: "guatemala" },
  { question: "Quel est le désert situé en Australie ?", answer: "grand désert de victoria" },
  { question: "Quel pays est bordé par la mer Noire à l’est ?", answer: "bulgarie" },
  { question: "Quel pays est formé de plus de 7 000 îles ?", answer: "philippines" },
  { question: "Quel pays est surnommé « l’île-continent » ?", answer: "australie" },
  { question: "Quel pays a pour capitale Bakou ?", answer: "azerbaïdjan" },
  { question: "Quel est le fleuve le plus long d’Afrique de l’Ouest ?", answer: "niger" },
  { question: "Quel pays est traversé par les Andes et l’Amazonie ?", answer: "pérou" },
  { question: "Quel pays a une frontière terrestre avec le Groenland ?", answer: "canada" },
  { question: "Quel pays se trouve entre la Roumanie et l’Ukraine ?", answer: "moldavie" },
  { question: "Quel est le seul pays africain où le français n’est pas langue officielle ?", answer: "angola" },
  { question: "Quelle est la capitale de la Birmanie ?", answer: "naypyidaw" },
  
  { question: "Quelle verrerie est la plus précise pour mesurer un volume ?", answer: "pipette graduée" },
  { question: "Quel est le rôle du ballon à fond rond en synthèse organique ?", answer: "chauffage uniforme" },
  { question: "Quel est le solvant utilisé en chromatographie sur couche mince ?", answer: "éluant" },
  { question: "Comment appelle-t-on un mélange liquide homogène de deux solvants non miscibles ?", answer: "émulsion" },
  { question: "Quel est l’objectif principal d’une distillation fractionnée ?", answer: "séparer des liquides proches" },
  { question: "Quel gaz toxique est libéré lorsqu’on chauffe du chlorure d’ammonium ?", answer: "ammoniac" },
  { question: "Quel réactif est utilisé pour identifier les ions chlorure ?", answer: "nitrate d'argent" },
  { question: "Quel est le point d’ébullition de l’éthanol pur à pression atmosphérique ?", answer: "78,5" },
  { question: "Quel est le rôle du réfrigérant à eau dans une distillation ?", answer: "condensation des vapeurs" },
  { question: "Quel type de réaction est la précipitation ?", answer: "réaction ionique" },
  { question: "Quel est le rôle du charbon actif dans une recristallisation ?", answer: "éliminer les impuretés colorées" },
  { question: "Quel est le nom du tube utilisé pour faire de la centrifugation ?", answer: "tube falcon" },
  { question: "Quel ion rend la flamme violette en spectroscopie de flamme ?", answer: "potassium" },
  { question: "Quelle est la formule du permanganate de potassium ?", answer: "kmno4" },
  { question: "Quel produit est utilisé pour l’acidification dans un titrage redox ?", answer: "acide sulfurique" },
  { question: "Quel est l’effet d’un excès de base forte sur le pH ?", answer: "augmentation" },
  { question: "Quel instrument permet de mesurer une masse au mg près ?", answer: "balance analytique" },
  { question: "Quel est l’usage d’un dessiccateur en laboratoire ?", answer: "sécher une substance" },
  { question: "Quel est l’effet du chauffage à sec sur un nitrate métallique ?", answer: "décomposition" },
  { question: "Quel indicateur vire du rose au incolore en milieu acide ?", answer: "phénolphtaléine" },
  { question: "Quel est le danger majeur lors du mélange eau-acide sulfurique ?", answer: "dégagement de chaleur" },
  { question: "Quelle est la verrerie utilisée pour faire un titrage goutte à goutte ?", answer: "burette" },
  { question: "Quel acide est produit lors de la dissolution du dioxyde de soufre dans l’eau ?", answer: "acide sulfureux" },
  { question: "Quel est le produit formé lors de la combustion complète du méthane ?", answer: "dioxyde de carbone" },
  { question: "Quel est le rôle du filtre Büchner ?", answer: "filtration sous vide" },
  { question: "Quel métal est attaqué par l’acide nitrique concentré avec émission de gaz bruns ?", answer: "cuivre" },
  { question: "Quel est le produit de l’électrolyse de l’eau ?", answer: "hydrogène et oxygène" },
  { question: "Quel type de liaison relie l’hydrogène à l’oxygène dans une molécule d’eau ?", answer: "liaison covalente" },
  { question: "Quelle est la couleur du précipité d’iodure de plomb ?", answer: "jaune" },
  { question: "Quel est le rôle du ballon à vide en extraction liquide-liquide ?", answer: "évaporation du solvant" },
  { question: "Quel est le rôle de la solution d’amidon en titrage iodométrique ?", answer: "indicateur d'endpoint" },
  { question: "Quel métal donne une flamme verte en test de flamme ?", answer: "cuivre" },
  { question: "Quelle précaution doit-on prendre avec les bases concentrées ?", answer: "gants et lunettes" },
  { question: "Comment appelle-t-on une solution dont le pH est stable malgré ajout d’acide ou base ?", answer: "tampon" },
  { question: "Quel est le rôle du sulfate de sodium anhydre en chimie organique ?", answer: "séchage" },
  { question: "Quelle verrerie est utilisée pour condenser les vapeurs d’un liquide ?", answer: "réfrigérant" },
  { question: "Quel est le solvant polaire utilisé pour extraire les alcaloïdes ?", answer: "éthanol" },
  { question: "Quel est le risque si on chauffe une solution dans une verrerie fermée ?", answer: "explosion" },
  { question: "Quelle propriété physique permet la chromatographie en phase gazeuse ?", answer: "volatilité" },
  { question: "Quel ion donne une précipitation bleue avec la soude ?", answer: "cuivre" },
  { question: "Quel gaz se forme quand on mélange zinc et acide chlorhydrique ?", answer: "hydrogène" },
  { question: "Quelle est la couleur de la flamme du sodium ?", answer: "jaune" },
  { question: "Quel est le principal danger du cyanure en laboratoire ?", answer: "toxique" },
  { question: "Quel est l’intérêt d’un agitateur magnétique ?", answer: "mélange homogène" },
  { question: "Quelle technique permet de séparer des isomères ?", answer: "chromatographie" },
  { question: "Quelle est la principale caractéristique d’un acide fort ?", answer: "dissociation complète" },
  { question: "Quelle est la couleur de l’indicateur bleu de bromothymol en base ?", answer: "bleu" },
  { question: "Quel est le réactif de Fehling détecte ?", answer: "sucres réducteurs" },
  { question: "Quel est le rôle d’un ballon tricol en synthèse ?", answer: "réactions multiples" },
  { question: "Quel est l’usage du support élévateur en laboratoire ?", answer: "ajuster la hauteur" },
  { question: "Quel est le nom du passage direct de gaz à solide ?", answer: "condensation" },
  { question: "Quelle est la fonction du sel dans l’eau lors d’une électrolyse ?", answer: "conducteur" },
  
  { question: "Quel est le plus grand désert chaud du monde ?", answer: "sahara" },
  { question: "Quelle est la plus grande île du monde ?", answer: "groenland" },
  { question: "Quelle est la capitale du kazakhstan ?", answer: "astana" },
  { question: "Quel pays est entouré par l’italie ?", answer: "saint-marin" },
  { question: "Quel pays possède le plus de fuseaux horaires ?", answer: "france" },
  { question: "Quel est le point culminant de l’afrique ?", answer: "kilimandjaro" },
  { question: "Quelle est la capitale du canada ?", answer: "ottawa" },
  { question: "Quel pays est le plus peuplé d’afrique ?", answer: "nigeria" },
  { question: "Quelle est la capitale de l’iran ?", answer: "téhéran" },
  { question: "Quel est le plus long fleuve d’asie ?", answer: "yangtsé" },
  { question: "Dans quel pays se trouve le lac titicaca ?", answer: "pérou" },
  { question: "Quel pays possède le plus de lacs ?", answer: "canada" },
  { question: "Quel est le pays le plus grand du monde ?", answer: "russie" },
  { question: "Quelle est la capitale de la mongolie ?", answer: "oulan-bator" },
  { question: "Quel est le plus grand océan du monde ?", answer: "pacifique" },
  { question: "Quel est le plus petit pays du monde ?", answer: "vatican" },
  { question: "Quelle est la capitale de la norvège ?", answer: "oslo" },
  { question: "Quel pays a pour capitale bakou ?", answer: "azerbaïdjan" },
  { question: "Quel est le plus long fleuve du monde ?", answer: "nil" },
  { question: "Quelle est la plus haute montagne d’europe ?", answer: "elbrus" },
  { question: "Dans quel pays se trouve la ville de valparaíso ?", answer: "chili" },
  { question: "Quel pays possède le mont fuji ?", answer: "japon" },
  { question: "Quel pays est surnommé 'le pays du matin calme' ?", answer: "corée du sud" },
  { question: "Dans quel pays est situé le désert d’atakama ?", answer: "chili" },
  { question: "Quel est le détroit entre la russie et l’alaska ?", answer: "détroit de béring" },
  { question: "Quelle ville est la capitale de l’australie ?", answer: "canberra" },
  { question: "Quel est le pays le plus densément peuplé ?", answer: "monaco" },
  { question: "Quel pays est traversé par l’équateur et le méridien de greenwich ?", answer: "gabón" },
  { question: "Dans quel pays se situe la ville de dubaï ?", answer: "émirats arabes unis" },
  { question: "Quel est le fleuve qui traverse paris ?", answer: "seine" },
  { question: "Quelle est la capitale de l’afghanistan ?", answer: "kaboul" },
  { question: "Quel pays a pour capitale minsk ?", answer: "biélorussie" },
  { question: "Quel est l’ancien nom de la thaïlande ?", answer: "royaume de siam" },
  { question: "Quel pays forme une île avec l’indonésie ?", answer: "papouasie-nouvelle-guinée" },
  { question: "Quel pays européen n’a pas d’armée ?", answer: "liechtenstein" },
  { question: "Quel est le plus long fleuve d’europe ?", answer: "volga" },
  { question: "Dans quel pays se trouve la vallée de la mort ?", answer: "états-unis" },
  { question: "Quel est le plus grand lac d’eau douce du monde ?", answer: "lac supérieur" },
  { question: "Quelle est la capitale de la nouvelle-zélande ?", answer: "wellington" },
  { question: "Quel pays a pour capitale tallinn ?", answer: "estonie" },
  { question: "Dans quel pays se trouve le mont ararat ?", answer: "turquie" },
  { question: "Quel pays partage la plus longue frontière terrestre avec la chine ?", answer: "mongolie" },
  { question: "Quelle ville est la plus peuplée du brésil ?", answer: "são paulo" },
  { question: "Quel est le pays le plus au sud de l’amérique du sud ?", answer: "chili" },
  { question: "Quel pays est le plus montagneux d’europe ?", answer: "suisse" },
  { question: "Quel pays africain a le plus de voisins ?", answer: "république démocratique du congo" },
  { question: "Quelle mer borde la jordanie à l’ouest ?", answer: "mer morte" },
  { question: "Quel pays a la plus haute densité urbaine au monde ?", answer: "singapour" },
  { question: "Quelle île est située au sud-est de l’inde ?", answer: "sri lanka" },
  { question: "Quel est le point le plus bas de la terre ?", answer: "mer morte" },
  { question: "Quelle est la capitale de la république tchèque ?", answer: "prague" },
  { question: "Dans quel pays se situe le cap de bonne-espérance ?", answer: "afrique du sud" },
  { question: "Quel est le volcan le plus actif d’europe ?", answer: "etna" },
  { question: "Quel pays a pour capitale manille ?", answer: "philippines" },
  { question: "Quelle est la capitale du sri lanka ?", answer: "sri jayawardenapura kotte" },
  { question: "Quel pays d’amérique du sud est enclavé ?", answer: "paraguay" },
  { question: "Quelle est la capitale de la croatie ?", answer: "zagreb" },
  { question: "Quel pays a pour capitale islamabad ?", answer: "pakistan" },
  { question: "Quelle est la capitale de la birmanie ?", answer: "naypyidaw" },
  { question: "Quel fleuve traverse londres ?", answer: "tamise" },
  { question: "Quel pays africain a pour capitale addis-abeba ?", answer: "éthiopie" },
  { question: "Quel pays forme la corne de l’afrique avec djibouti et érythrée ?", answer: "somalie" },
  { question: "Quel est le plus petit état d’afrique ?", answer: "lesotho" },
  { question: "Quel est le pays d’europe avec le plus de volcans ?", answer: "italie" },
  { question: "Dans quel pays se trouve la ville de louvain ?", answer: "belgique" },
  { question: "Quel pays d’amérique centrale a deux côtes maritimes ?", answer: "panama" },
  { question: "Quel pays a pour capitale vilnius ?", answer: "lituanie" },
  { question: "Quel pays est entièrement entouré par l’afrique du sud ?", answer: "lesotho" },
  { question: "Quel pays a pour capitale berne ?", answer: "suisse" },
  { question: "Quelle mer est située entre la grèce et la turquie ?", answer: "mer égée" },
  { question: "Quel est le plus grand archipel du monde ?", answer: "indonésie" },
  { question: "Quel pays européen est le plus boisé ?", answer: "finlande" },
  { question: "Quel est le plus haut sommet de l’amérique du sud ?", answer: "aconcagua" },
  { question: "Quel pays a la plus grande réserve de pétrole connue ?", answer: "venezuela" },
  { question: "Dans quel pays se trouve le mont sinai ?", answer: "égypte" },
  { question: "Quel pays a pour capitale skopje ?", answer: "macédoine du nord" },
  { question: "Quel est le fleuve principal de la roumanie ?", answer: "danube" },
  { question: "Quel pays est bordé par le golfe persique et la mer d’oman ?", answer: "iran" },
  { question: "Quel est le seul pays à avoir une frontière avec le royaume-uni ?", answer: "irlande" },
  { question: "Quel est le pays qui possède l’archipel des îles galápagos ?", answer: "équateur" },
  { question: "Quel pays se trouve à la pointe nord-est de l’afrique ?", answer: "égypte" },
  { question: "Quel pays a pour capitale yaoundé ?", answer: "cameroun" },
  { question: "Dans quel pays est située la ville de turin ?", answer: "italie" },
  { question: "Quelle île française est située dans l’océan indien ?", answer: "la réunion" },
  { question: "Quel pays partage une frontière avec 14 autres pays ?", answer: "chine" },
  { question: "Quelle est la capitale du bénin ?", answer: "porto-novo" },
  { question: "Quel pays européen est une principauté avec andorre ?", answer: "monaco" },
  { question: "Quel pays a pour capitale douchanbé ?", answer: "tadjikistan" },
  { question: "Quel pays asiatique a pour capitale baku ?", answer: "azerbaïdjan" },
  { question: "Quel est le fleuve sacré de l’inde ?", answer: "gange" },
  { question: "Quel pays est traversé par le méridien de greenwich et l’équateur ?", answer: "gabón" },
  { question: "Quel est le plus grand désert froid du monde ?", answer: "antarctique" },
  { question: "Quel est le plus grand port d’europe ?", answer: "rotterdam" },
  { question: "Quelle est la capitale de la bolivie ?", answer: "sucre" },
  { question: "Quel pays a pour capitale bujumbura ?", answer: "burundi" }






];

const activeSessions = {};

module.exports = {
  config: {
    name: "quizz",
    role: "0",
    author: "Merdi Madimba or Bryan Bulakali",
    version: "1.0",
    description: "Quiz culture générale avec score",
    category: "🎮 Jeu"
  },

  onStart: async function ({ event, message, usersData }) {
    const threadID = event.threadID;

    if (activeSessions[threadID]) {
      return message.reply("❗ Un quiz est déjà en cours !");
    }

    // Sélectionner 10 questions aléatoires
    const selected = [...questions].sort(() => 0.5 - Math.random()).slice(0, 100);
    const scores = {};

    let currentIndex = 0;
    let currentQuestion = null;
    let timeoutID = null;
    let answered = false;

    const sendQuestion = async () => {
      if (currentIndex >= selected.length) {
        // Fin du quiz
        const sorted = Object.entries(scores).sort((a, b) => b[1] - a[1]);
        let finalBoard = "🏁 Fin du quiz ! Résultat final :\n";
        let winner = sorted[0]?.[0] || "Aucun";

        for (let [name, pts] of sorted) {
          finalBoard += `🏅 ${name} : ${pts} pts\n`;
        }

        finalBoard += `👑 Vainqueur : ${winner}`;
        await message.send(finalBoard);
        delete activeSessions[threadID];
        return;
      }

      answered = false;
      currentQuestion = selected[currentIndex];

      await message.send(`❓ Question ${currentIndex + 1} : ${currentQuestion.question}`);

      timeoutID = setTimeout(async () => {
        if (!answered) {
          await message.send(`⏰ Temps écoulé ! La bonne réponse était : ${currentQuestion.answer}`);
          currentIndex++;
          sendQuestion();
        }
      }, 10000);
    };

    activeSessions[threadID] = async ({ event, message }) => {
      if (!currentQuestion || answered) return;

      const senderName = await usersData.getName(event.senderID);
      const msg = event.body?.toLowerCase().trim();

      if (msg === currentQuestion.answer) {
        answered = true;
        clearTimeout(timeoutID);

        scores[senderName] = (scores[senderName] || 0) + 10;

        // Scoreboard
        let board = "📊 Score actuel :\n";
        for (let [name, pts] of Object.entries(scores)) {
          board += `🏅 ${name} : ${pts} pts\n`;
        }

        await message.reply(`✅ Bonne réponse de ${senderName} !\n\n${board}`);
        currentIndex++;
        setTimeout(sendQuestion, 1000);
      }
    };

    sendQuestion();
  },

  onChat: function (context) {
    const handler = activeSessions[context.event.threadID];
    if (handler) handler(context);
  }
};
