 const questions = [
  { "question": "Quel outil est utilisé pour visser ?", "answer": "tournevis" },
  { "question": "Comment appelle-t-on l’outil pour creuser la terre ?", "answer": "pelle" },
  { "question": "Quel est l’instrument pour mesurer des distances longues ?", "answer": "mètre ruban" },
  { "question": "Quel outil est utilisé pour aplanir du ciment ?", "answer": "truelle" },
  { "question": "Quel outil est utilisé pour enfoncer un clou ?", "answer": "marteau" }

  { "question": "Quel instrument permet d’observer les cellules ?", "answer": "microscope" },
  { "question": "Comment s'appelle une lame en verre utilisée en biologie ?", "answer": "lame" },
  { "question": "Quel outil sert à prélever un petit échantillon biologique ?", "answer": "pipette" },
  { "question": "Quel est le nom du récipient de culture des bactéries ?", "answer": "boîte de petri" },
  { "question": "Quel est l’outil utilisé pour disséquer ?", "answer": "scalpel" }

  { "question": "Quel matériau est principalement utilisé dans les fondations ?", "answer": "béton" },
  { "question": "Quel outil sert à mesurer l’horizontalité ?", "answer": "niveau" },
  { "question": "Comment appelle-t-on les murs porteurs en béton ?", "answer": "murs porteurs" },
  { "question": "Quel est le nom du plan vu de dessus dans un bâtiment ?", "answer": "plan de masse" },
  { "question": "Quel est le nom de la machine qui soulève des charges sur un chantier ?", "answer": "grue" },
  { "question": "Quel est le principal outil pour scier du bois ?", "answer": "scie" },
  { "question": "Comment appelle-t-on le revêtement supérieur d’un bâtiment ?", "answer": "toiture" }

  { "question": "Quelle est la planète la plus proche du Soleil ?", "answer": "mercure" },
  { "question": "Quel est le nom de notre galaxie ?", "answer": "voie lactée" },
  { "question": "Quel est le satellite naturel de la Terre ?", "answer": "lune" },
  { "question": "Combien de planètes compte le système solaire ?", "answer": "8" },
  { "question": "Quel est le nom du télescope spatial célèbre lancé en 1990 ?", "answer": "hubble" },
  { "question": "Quelle planète est connue pour ses anneaux ?", "answer": "saturne" },
  { "question": "Quel corps céleste est une boule de glace et de poussière ?", "answer": "comète" }

  { "question": "Quel est le nom du récipient conique utilisé en laboratoire ?", "answer": "erlenmeyer" },
  { "question": "Quel instrument mesure le pH d’une solution ?", "answer": "ph-mètre" },
  { "question": "Quel tube est utilisé pour chauffer les substances ?", "answer": "tube à essai" },
  { "question": "Quel objet sert à mesurer un volume précis ?", "answer": "pipette" },
  { "question": "Quel matériau est utilisé pour chauffer une substance ?", "answer": "bec bunsen" }

  { "question": "Quelle est la dérivée de x² ?", "answer": "2x" },
  { "question": "Quel est le nom du théorème utilisé pour les triangles rectangles ?", "answer": "pythagore" },
  { "question": "Combien de côtés a un dodécagone ?", "answer": "12" },
  { "question": "Quel est le symbole de l'infini ?", "answer": "∞" },
  { "question": "Combien de degrés a un triangle équilatéral ?", "answer": "180" },
  { "question": "Quelle est la racine carrée de 144 ?", "answer": "12" },
  { "question": "Comment appelle-t-on le résultat d'une multiplication ?", "answer": "produit" }

  { "question": "Quel est le langage utilisé pour créer une page web ?", "answer": "html" },
  { "question": "Quel est le système d’exploitation créé par Linus Torvalds ?", "answer": "linux" },
  { "question": "Quel langage est souvent utilisé pour le machine learning ?", "answer": "python" },
  { "question": "Quel protocole est utilisé pour sécuriser un site web ?", "answer": "https" },
  { "question": "Comment appelle-t-on une base de données relationnelle très populaire ?", "answer": "mysql" },
  { "question": "Quel composant exécute les instructions dans un ordinateur ?", "answer": "processeur" },
  { "question": "Quel est le nom du système de gestion de versions le plus utilisé ?", "answer": "git" }

  { "question": "Quel est le nom de l’unité de mesure de l’inductance ?", "answer": "henry" },
  { "question": "Quel physicien a formulé la loi de la gravitation universelle ?", "answer": "newton" },
  { "question": "Quel phénomène explique la couleur bleue du ciel ?", "answer": "diffusion" },
  { "question": "Quel type d'onde est utilisé dans un micro-ondes ?", "answer": "micro-onde" },
  { "question": "Quel est le nom du champ qui entoure une charge électrique ?", "answer": "champ électrique" },
  { "question": "Quelle est la formule de l’énergie cinétique ?", "answer": "1/2mv²" },
  { "question": "Quelle particule subatomique a une charge négative ?", "answer": "électron" }

  { question: "Qui est le protagoniste de My Hero Academia ?", answer: "izuku" },
  { question: "Qui est le protagoniste de Naruto Shippuden ?", answer: "naruto" },
  { question: "Qui est le protagoniste de L'Attaque des Titans ?", answer: "eren" },
  { question: "Qui est le protagoniste de One Piece ?", answer: "luffy" },
  { question: "Qui est le protagoniste de Demon Slayer ?", answer: "tanjiro" },
  { question: "Qui est le protagoniste de Jujutsu Kaisen ?", answer: "yuji" },
  { question: "Qui est le protagoniste de Death Note ?", answer: "light" },
  { question: "Qui est le protagoniste de Bleach ?", answer: "ichigo" },
  { question: "Qui est le protagoniste de Tokyo Revengers ?", answer: "takemichi" },
  { question: "Qui est le protagoniste de Dr. Stone ?", answer: "senku" },
  { question: "Qui est le protagoniste de Hunter x Hunter ?", answer: "gon" },
  { question: "Qui est le protagoniste de Fairy Tail ?", answer: "natsu" },
  { question: "Qui est le protagoniste de Blue Lock ?", answer: "isagi" },
  { question: "Qui est le protagoniste de Fire Force ?", answer: "shinra" },
  { question: "Qui est le protagoniste de Code Geass ?", answer: "lelouch" },
  { question: "Qui est le protagoniste de The Rising of the Shield Hero ?", answer: "naofumi" },
  { question: "Qui est le protagoniste de Black Clover ?", answer: "asta" },
  { question: "Qui est le protagoniste de Noragami ?", answer: "yato" },
  { question: "Qui est le protagoniste de Mob Psycho 100 ?", answer: "mob" },
  { question: "Qui est le protagoniste de Vinland Saga ?", answer: "thorfinn" },
  { question: "Qui est le protagoniste de Chainsaw Man ?", answer: "denji" },
  { question: "Qui est le protagoniste de One Punch Man ?", answer: "saitama" },
  { question: "Qui est le protagoniste de Spy x Family ?", answer: "loidy" },
  { question: "Qui est le protagoniste de Gintama ?", answer: "gintoki" },
  { question: "Qui est le protagoniste de Bungo Stray Dogs ?", answer: "atsushi" },
  { question: "Qui est le protagoniste de Assassination Classroom ?", answer: "nagisa" },
  { question: "Qui est le protagoniste de Soul Eater ?", answer: "maka" },
  { question: "Qui est le protagoniste de The Promised Neverland ?", answer: "emma" },
  { question: "Qui est le protagoniste de Re:Zero ?", answer: "subaru" },
  { question: "Qui est le protagoniste de Erased ?", answer: "satoru" }

  { question: "Quel grand festival de musique rock a réuni green day et nirvana en 2025 ?", answer: "fireaid" },
  { question: "Quel album de franz ferdinand est sorti en janvier 2025 ?", answer: "the human fear" },
  { question: "Quel groupe de rock est revenu brièvement sur scène en 2025 ?", answer: "nirvana" },
  { question: "Quel pays a accueilli l’eurovision 2025 ?", answer: "suisse" },
  { question: "Quel a été le slogan de l’eurovision 2025 ?", answer: "welcome home" },
  { question: "Quelle ville a organisé l’eurovision 2025 ?", answer: "bâle" },
  { question: "Combien d’équipes ont participé à la coupe du monde des clubs 2025 ?", answer: "32" },
  { question: "Quel club a dominé la coupe du monde des clubs 2025 selon les paris ?", answer: "real madrid" },
  { question: "Quel joueur légendaire a joué son 800ᵉ but en 2024 ?", answer: "lionel messi" },
  { question: "Quel champion d'athlétisme a établi un record de saut à la perche en 2025 ?", answer: "armand duplantis" },
  
  { question: "Quel pays d’asie centrale a intégré le brics en 2024 ?", answer: "iran" },
  { question: "Quelles nations ont rejoint le brics en 2024 ?", answer: "argentine, iran, arabie saoudite, égypte, indonésie" },
  { question: "Quel match caritatif a vu le retour de robbie williams ? (soccer aid)", answer: "soccer aid" },
  { question: "Qui est le nouvel ambassadeur musical de la fifa en 2025 ?", answer: "robbie williams" },
  { question: "Quelle chanson de robbie williams est l’hymne officiel de la fifa ?", answer: "desire" },
  { question: "Quel président de la république fédérale allemande quitte en 2025 ?", answer: "donald trump" },
  { question: "Qui est devenu le premier président africain du comité olympique en 2025 ?", answer: "kirsty coventry" },
  { question: "Où s’est tenue la session du comité olympique en mars 2025 ?", answer: "pylos" },
  { question: "Quel pays a remporté la ligue africaine de rugby 2024 ?", answer: "pays d'afrique" },
  { question: "Quel pays a accueilli les world games 2025 ?", answer: "chine" },
  
  { question: "Quel grand mouvement a affecté les récifs coralliens 2023–2025 ?", answer: "coral bleaching" },
  { question: "Quel record climatique 2025 est lié aux coraux ?", answer: "événement de blanchiment global" },
  { question: "Quel pays a remporté l’euro 2024 ?", answer: "espagne" },
  { question: "Qui a gagné le ballon d’or 2024 ?", answer: "erling haaland" },
  { question: "Quel club a remporté la série mondiale mlb 2024 ?", answer: "atlanta braves" },
  { question: "Quel événement a rassemblé les chefs d’état du g7 en canada en 2025 ?", answer: "sommet du g7" },
  { question: "Quel chef de la banque du royaume-uni attend une annonce en 2025 ?", answer: "bank of england" },
  { question: "Quel océan a vu des attaques houthies affecter la sécurité maritime ?", answer: "mer rouge" },
  { question: "Quel dirigeant a été renversé en 2024 en syrie ?", answer: "bashar al-assad" },
  { question: "Quel pays africain a élu claudia sheinbaum en 2024 ?", answer: "mexique" },
  
  { question: "Quel a été le thème principal du sommet g20 2024 au brésil ?", answer: "développement durable" },
  { question: "Quel a été l’objectif du cop28 2024 ?", answer: "changement climatique" },
  { question: "Quel pays a inauguré la plus grande ferme solaire flottante en 2024 ?", answer: "inde" },
  { question: "Qui a remporté le prix nobel de littérature 2023 ?", answer: "jon fosse" },
  { question: "Quel pays a célébré 75 ans de l’oms en 2024 ?", answer: "monde" },
  { question: "Quel pays est devenu le premier à éliminer le charbon en 2024 ?", answer: "royaume-uni" },
  { question: "Quel film a gagné oscar meilleur film 2024 ?", answer: "oppenheimer" },
  { question: "Quelle star a remporté grammy record of the year 2024 ?", answer: "kendrick lamar" },
  { question: "Quel groupe a joué à l’ouverture de la finale c1 2025 ?", answer: "linkin park" },
  { question: "Quel album de sleep token est entré n°1 en 2025 ?", answer: "even in arcadia" },
  
  { question: "Quel marathon de paris olympique a battu un record de la femme cycliste 2024 ?", answer: "équipe féminine britannique de cyclisme" },
  { question: "Quel tremblement de terre a frappé l’asie en 2024 ?", answer: "séisme magnitude 7.2 en indonésie" },
  { question: "Quel pays a renoncé à interdire les combustibles fossiles du gaz naturel d’ici 2027 ?", answer: "union européenne" },
  { question: "Quel pays a dépassé 5 milliards d’utilisateurs sur un réseau social en 2024 ?", answer: "facebook" },
  { question: "Quelle multinationale a lancé classgpt en 2024 ?", answer: "microsoft" },
  { question: "Quel pays a utilisé un rover martien lancé par l’esa en 2024 ?", answer: "esa" },
  { question: "Quel pays a mis en place un fonds climatique de 2 milliards pour l’afrique en 2024 ?", answer: "banque africaine de développement" },
  { question: "Qui a été élu président du mexique 2024 ?", answer: "claudia sheinbaum" },
  { question: "Quel pays auto a tenu une réunion sur l’armement g20 en 2024 ?", answer: "indonésie" },
  { question: "Quel pays a ajouté le temple hoysaleswara au patrimoine mondial 2024 ?", answer: "inde" }

  { question: "Qui a construit une arche pour survivre au déluge ?", answer: "noé" },
  { question: "Qui a reçu les dix commandements sur le mont Sinaï ?", answer: "moïse" },
  { question: "Quel roi a écrit de nombreux psaumes ?", answer: "david" },
  { question: "Qui fut le premier homme créé selon la Bible ?", answer: "adam" },
  { question: "Qui a trahi Jésus pour 30 pièces d’argent ?", answer: "judas" },
  { question: "Comment s’appelait la mère de Jésus ?", answer: "marie" },
  { question: "Combien de jours Jésus a-t-il jeûné dans le désert ?", answer: "40" },
  { question: "Quel disciple marcha sur l’eau vers Jésus ?", answer: "pierre" },
  { question: "Qui a été avalé par un grand poisson ?", answer: "jonas" },
  { question: "Dans quelle ville Jésus est-il né ?", answer: "bethléem" },
  { question: "Quel est le premier livre de la Bible ?", answer: "genèse" },
  { question: "Combien de livres contient la Bible ?", answer: "66" },
  { question: "Qui fut transformé en statue de sel ?", answer: "femme de lot" },
  { question: "Quel apôtre est aussi appelé Saul ?", answer: "paul" },
  { question: "Quel animal a parlé à Balaam ?", answer: "âne" },
  { question: "Quel est le dernier livre de la Bible ?", answer: "apocalypse" },
  { question: "Qui est l’auteur traditionnel des Proverbes ?", answer: "salomon" },
  { question: "Qui a tué Goliath ?", answer: "david" },
  { question: "Combien de plaies ont frappé l’Égypte ?", answer: "10" },
  { question: "Quel apôtre a renié Jésus trois fois ?", answer: "pierre" },
  { question: "Dans quel jardin Jésus a-t-il prié avant son arrestation ?", answer: "gethsémani" },
  { question: "Qui a construit le temple de Jérusalem ?", answer: "salomon" },
  { question: "Combien de jours Dieu a-t-il pris pour créer le monde ?", answer: "6" },
  { question: "Quel prophète a confronté les prophètes de Baal ?", answer: "élie" },
  { question: "Qui était roi quand Daniel a été jeté aux lions ?", answer: "darius" },
  { question: "Quel fruit Ève a-t-elle mangé dans le jardin ?", answer: "pomme" },
  { question: "Quelle mer Moïse a-t-il traversée avec les israélites ?", answer: "mer rouge" },
  { question: "Quel disciple était surnommé le jumeau ?", answer: "thomas" },
  { question: "Quel était le métier de Jésus ?", answer: "charpentier" },
  { question: "Combien de personnes sont entrées dans l’arche ?", answer: "8" }

  { question: "Quel est le nom du personnage principal dans The Legend of Zelda ?", answer: "link" },
  { question: "Quel jeu a pour protagoniste un plombier rouge ?", answer: "mario" },
  { question: "Quel battle royale est développé par Epic Games ?", answer: "fortnite" },
  { question: "Quel jeu de football est développé par EA Sports ?", answer: "fifa" },
  { question: "Dans quel jeu peut-on attraper des créatures appelées Pokémon ?", answer: "pokémon" },
  { question: "Quel jeu met en scène des agents dans une guerre contre le Black Tusk ?", answer: "the division" },
  { question: "Quel est le nom du jeu où l’on construit avec des blocs dans un monde ouvert ?", answer: "minecraft" },
  { question: "Quel jeu met en scène Kratos, un dieu de la guerre ?", answer: "god of war" },
  { question: "Quel jeu multijoueur propose des parties d'imposteurs et de vote ?", answer: "among us" },
  { question: "Dans quel jeu affronte-t-on Bowser ?", answer: "mario" },
  { question: "Quel FPS très populaire de Riot Games a pour nom un mot lié au courage ?", answer: "valorant" },
  { question: "Quel jeu d'horreur met en scène un ours nommé Freddy ?", answer: "five nights at freddy's" },
  { question: "Dans quel jeu incarne-t-on Arthur Morgan ?", answer: "red dead redemption 2" },
  { question: "Quel jeu de tir en équipe propose les personnages Tracer et Reinhardt ?", answer: "overwatch" },
  { question: "Quel jeu célèbre propose un mode créatif et un mode survie en blocs ?", answer: "minecraft" },
  { question: "Dans quel jeu de stratégie incarne-t-on un chef de civilisation ?", answer: "civilization" },
  { question: "Quel est le nom du jeu de simulation de vie avec des villageois animaux ?", answer: "animal crossing" },
  { question: "Dans quel jeu de combat retrouve-t-on Ryu et Ken ?", answer: "street fighter" },
  { question: "Quel jeu raconte l’histoire d’un chasseur dans un monde peuplé de monstres ?", answer: "monster hunter" },
  { question: "Dans quel jeu incarne-t-on un ninja de Konoha ?", answer: "naruto" },
  { question: "Quel jeu permet de cuisiner en coopération chaotique ?", answer: "overcooked" },
  { question: "Dans quel jeu d’horreur fuit-on Granny ?", answer: "granny" },
  { question: "Quel jeu de guerre se déroule souvent pendant la Seconde Guerre mondiale ?", answer: "call of duty" },
  { question: "Quel jeu mobile mélange bonbons et puzzles ?", answer: "candy crush" },
  { question: "Dans quel jeu incarne-t-on un samouraï du nom de Jin Sakai ?", answer: "ghost of tsushima" },
  { question: "Quel jeu met en scène un hérisson bleu très rapide ?", answer: "sonic" },
  { question: "Quel jeu de tir a popularisé le mode battle royale avec des véhicules ?", answer: "pubg" },
  { question: "Quel jeu de football a été renommé en EA FC ?", answer: "fifa" },
  { question: "Quel jeu raconte l’histoire de Ellie et Joel ?", answer: "the last of us" },
  { question: "Quel jeu de puzzle utilise des blocs qui tombent du haut ?", answer: "tetris" }

  
  { question: "Je suis toujours devant toi, mais tu ne peux jamais m’atteindre. Qui suis-je ?", answer: "l’avenir" },
  { question: "Je grandis sans vie, je n’ai pas de poumon mais j’ai besoin d’air. Qui suis-je ?", answer: "le feu" },
  { question: "Plus tu m’en prends, plus je deviens grand. Qui suis-je ?", answer: "un trou" },
  { question: "Je n’ai ni bouche ni oreilles, mais je répète tout ce que tu dis. Qui suis-je ?", answer: "l’écho" },
  { question: "Je commence la nuit et finis le matin, et pourtant je ne dure qu’un instant. Qui suis-je ?", answer: "un rêve" },
  { question: "Je suis à toi mais les autres m’utilisent plus que toi. Qui suis-je ?", answer: "ton nom" },
  { question: "Je suis plein de trous, mais je retiens l’eau. Qui suis-je ?", answer: "l’éponge" },
  { question: "Plus je suis sale, plus je deviens blanc. Qui suis-je ?", answer: "le tableau" },
  { question: "Je vole sans ailes, je pleure sans yeux. Qui suis-je ?", answer: "le nuage" },
  { question: "J’ai un cou mais pas de tête. Qui suis-je ?", answer: "une bouteille" },
  { question: "Je peux remplir une pièce sans prendre d’espace. Qui suis-je ?", answer: "la lumière" },
  { question: "Je marche sans jambes. Qui suis-je ?", answer: "le temps" },
  { question: "Je ne peux être vu qu’une fois par an. Qui suis-je ?", answer: "le 29 février" },
  { question: "Je suis toujours là mais on ne me voit que dans le noir. Qui suis-je ?", answer: "l’obscurité" },
  { question: "Je suis chaud en hiver et froid en été. Qui suis-je ?", answer: "le vent" },
  { question: "Je peux être cassé sans être touché. Qui suis-je ?", answer: "une promesse" },
  { question: "Je suis petit au départ et grand à la fin, je peux tuer. Qui suis-je ?", answer: "un secret" },
  { question: "Je suis invisible, mais je fais du bruit quand je me déplace. Qui suis-je ?", answer: "le vent" },
  { question: "On me casse pour manger ce qu’il y a à l’intérieur. Qui suis-je ?", answer: "un œuf" },
  { question: "Plus je suis rapide, moins tu me vois. Qui suis-je ?", answer: "le temps" },
  { question: "On me coupe pour faire du feu, je pousse sans vie. Qui suis-je ?", answer: "le bois" },
  { question: "Je suis rond, j’ai une queue, mais je ne suis pas un animal. Qui suis-je ?", answer: "la pièce" },
  { question: "Je suis rouge, je suis sucré, mais je pique si on me coupe. Qui suis-je ?", answer: "l’oignon" },
  { question: "Je tombe sans jamais monter. Qui suis-je ?", answer: "la pluie" },
  { question: "Je peux être long ou court, et pourtant tout le monde en a. Qui suis-je ?", answer: "le nom" },
  { question: "Je suis un animal, mais je parle. Qui suis-je ?", answer: "le perroquet" },
  { question: "On me mange, mais je suis aussi une couleur. Qui suis-je ?", answer: "l’orange" },
  { question: "Je suis dans l’eau mais je ne me mouille pas. Qui suis-je ?", answer: "l’ombre" },
  { question: "Je suis né dans une grotte, je brille sans flamme. Qui suis-je ?", answer: "un diamant" },
  { question: "On me trouve dans le ciel, mais je ne vole pas. Qui suis-je ?", answer: "la lune" },
  { question: "J’ai un lit mais je ne dors jamais. Qui suis-je ?", answer: "la rivière" },
  { question: "Je suis parfois chaud, parfois froid, je monte mais je ne tombe jamais. Qui suis-je ?", answer: "la température" },
  { question: "Je m’ouvre sans clé et me ferme sans serrure. Qui suis-je ?", answer: "la bouche" },
  { question: "J’ai quatre pattes mais je ne marche pas. Qui suis-je ?", answer: "une chaise" },
  { question: "Je suis léger comme une plume, mais même le plus fort ne peut me tenir longtemps. Qui suis-je ?", answer: "le souffle" },
  { question: "Je parle toutes les langues. Qui suis-je ?", answer: "l’écho" },
  { question: "Je suis là quand tu dors, je disparais quand tu te réveilles. Qui suis-je ?", answer: "le rêve" },
  { question: "On me jette quand je veut m’en servir. Qui suis-je ?", answer: "l’ancre" },
  { question: "Je suis parfois blanc, parfois noir, je donne des mots. Qui suis-je ?", answer: "la page" },
  { question: "Je commence grand et finis petit. Qui suis-je ?", answer: "la bougie" },
  { question: "On me touche sans me voir. Qui suis-je ?", answer: "le vent" },
  { question: "Je peux tuer sans toucher. Qui suis-je ?", answer: "le poison" },
  { question: "Je suis fort la nuit et faible le jour. Qui suis-je ?", answer: "la lune" },
  { question: "J’ai des racines mais je ne suis pas une plante. Qui suis-je ?", answer: "une dent" },
  { question: "Je suis sec mais je mouille. Qui suis-je ?", answer: "la serviette" },
  { question: "Je vis dans la tête mais je ne suis pas vivant. Qui suis-je ?", answer: "l’idée" },
  { question: "Je peux voler sans ailes et courir sans jambes. Qui suis-je ?", answer: "le temps" },
  { question: "On me remplit pour que je puisse vider. Qui suis-je ?", answer: "le seau" },
  { question: "Je disparais dès qu’on me nomme. Qui suis-je ?", answer: "le silence" }

  { question: "🇯🇲 Ce drapeau appartient à quel pays ?", answer: "jamaïque" },
  { question: "🇳🇿 Ce drapeau appartient à quel pays ?", answer: "nouvelle-zélande" },
  { question: "🇿🇦 Ce drapeau appartient à quel pays ?", answer: "afrique du sud" },
  { question: "🇦🇷 Ce drapeau appartient à quel pays ?", answer: "argentine" },
  { question: "🇵🇹 Ce drapeau appartient à quel pays ?", answer: "portugal" },
  { question: "🇳🇴 Ce drapeau appartient à quel pays ?", answer: "norvège" },
  { question: "🇵🇪 Ce drapeau appartient à quel pays ?", answer: "pérou" },
  { question: "🇪🇹 Ce drapeau appartient à quel pays ?", answer: "éthiopie" },
  { question: "🇮🇷 Ce drapeau appartient à quel pays ?", answer: "iran" },
  { question: "🇲🇲 Ce drapeau appartient à quel pays ?", answer: "birmanie" },
  { question: "🇧🇼 Ce drapeau appartient à quel pays ?", answer: "botswana" },
  { question: "🇧🇩 Ce drapeau appartient à quel pays ?", answer: "bangladesh" },
  { question: "🇮🇸 Ce drapeau appartient à quel pays ?", answer: "islande" },
  { question: "🇬🇪 Ce drapeau appartient à quel pays ?", answer: "géorgie" },
  { question: "🇰🇼 Ce drapeau appartient à quel pays ?", answer: "koweït" },
  { question: "🇲🇽 Ce drapeau appartient à quel pays ?", answer: "mexique" },
  { question: "🇹🇿 Ce drapeau appartient à quel pays ?", answer: "tanzanie" },
  { question: "🇹🇹 Ce drapeau appartient à quel pays ?", answer: "trinité-et-tobago" },
  { question: "🇨🇺 Ce drapeau appartient à quel pays ?", answer: "cuba" },
  { question: "🇻🇳 Ce drapeau appartient à quel pays ?", answer: "vietnam" },
  { question: "🇩🇿 Ce drapeau appartient à quel pays ?", answer: "algérie" },
  { question: "🇸🇳 Ce drapeau appartient à quel pays ?", answer: "sénégal" },
  { question: "🇬🇳 Ce drapeau appartient à quel pays ?", answer: "guinée" },
  { question: "🇨🇻 Ce drapeau appartient à quel pays ?", answer: "cap-vert" },
  { question: "🇨🇲 Ce drapeau appartient à quel pays ?", answer: "cameroun" },
  { question: "🇬🇭 Ce drapeau appartient à quel pays ?", answer: "ghana" },
  { question: "🇳🇪 Ce drapeau appartient à quel pays ?", answer: "niger" },
  { question: "🇹🇩 Ce drapeau appartient à quel pays ?", answer: "tchad" },
  { question: "🇨🇬 Ce drapeau appartient à quel pays ?", answer: "république du congo" },
  { question: "🇰🇵 Ce drapeau appartient à quel pays ?", answer: "corée du nord" }
  { question: "Quel mathématicien grec a formulé le théorème de l’hypoténuse ?", answer: "pythagore" },
  { question: "Quel physicien est considéré comme le père de la mécanique quantique ?", answer: "max planck" },
  { question: "Qui a écrit *le capital* ?", answer: "karl marx" },
  { question: "Quelle est la capitale du turkménistan ?", answer: "achgabat" },
  { question: "Quel est le point culminant de l’amérique du sud ?", answer: "aconcagua" },
  { question: "Dans quel pays se trouve une partie du lac titicaca ?", answer: "pérou" },
  { question: "Quel est l’élément chimique dont le symbole est 'w' ?", answer: "tungstène" },
  { question: "Quel est le nom de la galaxie la plus proche de la voie lactée ?", answer: "andromède" },
  { question: "Quelle est la constante d’avogadro ?", answer: "6.022 x 10^23" },
  { question: "Qui a peint *guernica* ?", answer: "pablo picasso" },
  { question: "Quel empire a succédé à babylone en mésopotamie ?", answer: "empire perse" },
  { question: "Combien y a-t-il de lettres dans l’alphabet grec ?", answer: "24" },
  { question: "Qui a écrit *le monde comme volonté et comme représentation* ?", answer: "arthur schopenhauer" },
  { question: "Quel est le deuxième plus long fleuve du monde ?", answer: "amazone" },
  { question: "Quel pays d’asie centrale est totalement enclavé ?", answer: "ouzbekistan" },
  { question: "Quelle est la capitale de la papouasie-nouvelle-guinée ?", answer: "port moresby" },
  { question: "Quel acide est présent dans l’estomac humain ?", answer: "acide chlorhydrique" },
  { question: "Qui a inventé le vaccin contre la rage ?", answer: "louis pasteur" },
  { question: "Où se situe samarcande ?", answer: "ouzbekistan" },
  { question: "Quel philosophe grec a enseigné alexandre le grand ?", answer: "aristote" },
  { question: "Qui a découvert la pénicilline ?", answer: "alexander fleming" },
  { question: "Quel océan borde l’est de l’australie ?", answer: "pacifique" },
  { question: "Quel organe produit l’insuline ?", answer: "pancréas" },
  { question: "Qui a inventé le microscope ?", answer: "antonie van leeuwenhoek" },
  { question: "Quel pays est situé entre le sénégal et la guinée ?", answer: "guinée-bissau" },
  { question: "Quel pays d’afrique n’a jamais été colonisé ?", answer: "éthiopie" },
  { question: "Qui est le dieu romain équivalent à hadès ?", answer: "pluton" },
  { question: "Quel pays produit le plus de cacao au monde ?", answer: "côte d’ivoire" },
  { question: "Quel philosophe est lié au doute méthodique ?", answer: "descartes" },
  { question: "Quelle est la langue officielle de l’érythrée ?", answer: "tigrigna" },
  { question: "Quel est le satellite naturel de pluton ?", answer: "charon" },
  { question: "Qui a écrit *crime et châtiment* ?", answer: "dostoïevski" },
  { question: "Quel est le nom complet de l’adn ?", answer: "acide désoxyribonucléique" },
  { question: "Qui a construit la sagrada familia ?", answer: "gaudí" },
  { question: "Quel est le métal le plus léger ?", answer: "lithium" },
  { question: "Qui a écrit *l’éthique* ?", answer: "spinoza" },
  { question: "Quel est le plus vieux désert du monde ?", answer: "désert du namib" },
  { question: "Dans quelle ville se trouve le cern ?", answer: "genève" },
  { question: "Quel est le groupe sanguin donneur universel ?", answer: "o-" },
  { question: "Quelle molécule transporte l’oxygène ?", answer: "hémoglobine" },
  { question: "Quel est le roman le plus vendu après la bible ?", answer: "don quichotte" },
  { question: "Quel est le plus long os du corps humain ?", answer: "fémur" },
  { question: "Quelle est la plus grande espèce de requin ?", answer: "requin-baleine" },
  { question: "Qui a écrit *le nom de la rose* ?", answer: "umberto eco" },
  { question: "Quel organe filtre le sang ?", answer: "rein" },
  { question: "Quelle est la planète la plus dense ?", answer: "terre" },
  { question: "Quelle est la capitale du bhoutan ?", answer: "thimphou" },
  { question: "Quel pays possède le plus de volcans actifs ?", answer: "indonésie" },
  { question: "Quel était le navire de charles darwin ?", answer: "beagle" },
  { question: "Quelle est la distance terre-soleil ?", answer: "150 millions de km" },
  { question: "Qui a inventé le calcul infinitésimal avec newton ?", answer: "leibniz" },
  { question: "Quel isotope est utilisé dans les centrales ?", answer: "uranium-235" },
  { question: "Quel pays a l’équateur et la plus haute capitale ?", answer: "équateur" },
  { question: "Quel est le plus grand mammifère terrestre ?", answer: "éléphant d’afrique" },
  { question: "Quelle était l’ancienne capitale du japon ?", answer: "kyoto" },
  { question: "Qui a écrit *ainsi parlait zarathoustra* ?", answer: "nietzsche" },
  { question: "Quel organe produit la bile ?", answer: "foie" },
  { question: "Quel est le premier satellite lancé ?", answer: "spoutnik" },
  { question: "Dans quel pays est la ville de petra ?", answer: "jordanie" },
  { question: "Quel empereur romain a lancé la construction du colisée ?", answer: "vespasien" },
  { question: "Quelle est l’unité de la pression ?", answer: "pascal" },
  { question: "Qui a formulé la loi de la gravitation ?", answer: "isaac newton" },
  { question: "Quel est le manuscrit maya le plus connu ?", answer: "codex de dresde" },
  { question: "Quelle est la capitale du kazakhstan ?", answer: "astana" },
  { question: "Quel est le point le plus profond des océans ?", answer: "fosse des mariannes" },
  { question: "Quel est le plus grand archipel du monde ?", answer: "indonésie" },
  { question: "Qui a écrit *les misérables* ?", answer: "victor hugo" },
  { question: "Quel organe est touché par l’hépatite ?", answer: "foie" },
  { question: "Qui a proposé la théorie de la sélection naturelle ?", answer: "charles darwin" },
  { question: "Qui est le dieu nordique du tonnerre ?", answer: "thor" },
  { question: "Quel volcan a détruit pompéi ?", answer: "vésuve" },
  { question: "Quel océan borde l’est de l’afrique ?", answer: "océan indien" },
  { question: "Quel acide est utilisé dans les batteries ?", answer: "acide sulfurique" },
  { question: "Qui a écrit *les métamorphoses* ?", answer: "ovide" },
  { question: "Quel atome a un seul proton ?", answer: "hydrogène" },
  { question: "Quel pays est à l’origine du confucianisme ?", answer: "chine" },
  { question: "Quelle femme a reçu un prix nobel en premier ?", answer: "marie curie" },
  { question: "Quel pays est surnommé la terre du milieu ?", answer: "chine" },
  { question: "Qui a écrit *critique de la raison pure* ?", answer: "kant" },
  { question: "Quel est l’autre nom de la voie digestive ?", answer: "tube digestif" }


  { question: "Quel est le point le plus bas sur terre ?", answer: "mer Morte" },
  { question: "Dans quel pays se trouve le désert d’Atacama ?", answer: "chili" },
  { question: "Quel fleuve traverse le plus de pays ?", answer: "le Danube" },
  { question: "Dans quel pays se trouve la ville de Timbuktu ?", answer: "mali" },
  { question: "Quelle est la plus grande île du monde ?", answer: "groenland" },
  { question: "Quel est le plus grand désert chaud du monde ?", answer: "sahara" },
  { question: "Dans quel pays se trouve la ville de Vladivostok ?", answer: "russie" },
  { question: "Quel est le plus haut volcan actif ?", answer: "ojos del salado" },
  { question: "Quel pays est enclavé entre l’Inde et la Chine ?", answer: "bhoutan" },
  { question: "Quel pays d’Afrique n’a jamais été colonisé ?", answer: "éthiopie, libéria" },
  { question: "Quel est le pays le plus peuplé d’Afrique ?", answer: "nigéria" },
  { question: "Quelle mer borde la Jordanie à l’ouest ?", answer: "mer morte" },
  { question: "Quel est le plus long fleuve d’Asie ?", answer: "yangtsé" },
  { question: "Dans quel pays se trouve la Patagonie ?", answer: "argentine" },
  { question: "Quel pays possède le plus de fuseaux horaires ?", answer: "france" },
  { question: "Quelle chaîne de montagnes traverse le Pérou ?", answer: "andes" },
  { question: "Quel pays a pour capitale N'Djamena ?", answer: "tchad" },
  { question: "Où se situe le mont Elbrouz ?", answer: "russie" },
  { question: "Quel pays possède la ville de Luanda ?", answer: "angola" },
  { question: "Quel est le plus grand pays du monde sans accès à la mer ?", answer: "kazakhstan" },

  { question: "Quel pays a un drapeau vert uni sans symbole ?", answer: "libye" },
  { question: "Quel pays a un drapeau avec un cèdre ?", answer: "liban" },
  { question: "Quel drapeau a une étoile jaune sur fond rouge ?", answer: "vietnam" },
  { question: "Quel drapeau possède un soleil levant rouge ?", answer: "japon" },
  { question: "Quel drapeau a un oiseau Quetzal ?", answer: "guatemala" },
  { question: "Quel drapeau représente une feuille d'érable ?", answer: "canada" },
  { question: "Quel pays a un drapeau bleu clair avec un soleil ?", answer: "argentine" },
  { question: "Quel pays a un drapeau noir, rouge et jaune horizontal ?", answer: "allemagne" },
  { question: "Quel drapeau a un croissant et une étoile blanche ?", answer: "turquie" },
  { question: "Quel drapeau a une étoile verte à cinq branches ?", answer: "maroc" },

  { question: "Qui était le roi de France pendant la Révolution française ?", answer: "louis 16" },
  { question: "Quel empire a précédé l'Allemagne moderne ?", answer: "saint-empire romain germanique" },
  { question: "En quelle année a eu lieu la chute du mur de Berlin ?", answer: "1989" },
  { question: "Quel traité a mis fin à la Première Guerre mondiale ?", answer: "versailles" },
  { question: "Qui a fondé l'empire mongol ?", answer: "gengis khan" },
  { question: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", answer: "1492" },
  { question: "Quelle guerre a opposé le Nord et le Sud des États-Unis ?", answer: "sécession" },
  { question: "Qui était le dictateur espagnol jusqu’en 1975 ?", answer: "franco" },
  { question: "Quel événement a marqué le début de la Seconde Guerre mondiale ?", answer: "l'invasion de la pologne" },
  { question: "Qui a été le premier président des États-Unis ?", answer: "washington" },
  { question: "Quelle civilisation a construit Machu Picchu ?", answer: "incas" },
  { question: "Qui a été le chef de la Révolution russe de 1917 ?", answer: "lénine" },
  { question: "En quelle année l'URSS a-t-elle été dissoute ?", answer: "1991" },
  { question: "Quel empereur romain a christianisé l’Empire ?", answer: "constantin 1" },
  { question: "Quelle reine a régné sur l’Angleterre de 1837 à 1901 ?", answer: "victoria" },
  { question: "Quel pays a été le dernier à abolir l'esclavage ?", answer: "mauritanie" },
  { question: "En quelle année Napoléon est-il mort ?", answer: "1821" },
  { question: "Qui a libéré l’Amérique du Sud de la domination espagnole ?", answer: "bolivar" },
  { question: "Quel est le nom de l’ancien nom de l’Iran ?", answer: "perse" },
  { question: "Qui était président des USA pendant la crise de Cuba ?", answer: "kennedy" },

  // ... (les 50 premières que tu as déjà)

  // 🧪 Chimie (20)
  { question: "Quel est le symbole chimique de l’or ?", answer: "au" },
  { question: "Quel gaz est utilisé dans les enseignes lumineuses ?", answer: "néon" },
  { question: "Quel est l'élément chimique numéro 1 du tableau périodique ?", answer: "hydrogène" },
  { question: "Quel est le nom scientifique de l'eau ?", answer: "oxyde de dihydrogène" },
  { question: "Quel métal liquide est utilisé dans les thermomètres ?", answer: "mercure" },
  { question: "Quelle est la formule chimique du sel de table ?", answer: "nacl" },
  { question: "Quel élément a pour symbole Fe ?", answer: "fer" },
  { question: "Quel est le gaz le plus abondant dans l’atmosphère ?", answer: "azote" },
  { question: "Quel acide est contenu dans l’estomac humain ?", answer: "acide chlorhydrique" },
  { question: "Quel est l’élément chimique symbolisé par K ?", answer: "potassium" },
  { question: "Combien y a-t-il de groupes dans le tableau périodique ?", answer: "18" },
  { question: "Qui est considéré comme le père de la chimie moderne ?", answer: "lavoisier" },
  { question: "Quel gaz est nécessaire à la combustion ?", answer: "oxygène" },
  { question: "Quel est l’élément principal du diamant ?", answer: "carbone" },
  { question: "Quel est l’acide utilisé dans les batteries de voiture ?", answer: "acide sulfurique" },
  { question: "Quel élément a pour symbole Cu ?", answer: "cuivre" },
  { question: "Quel est le gaz responsable de l’effet de serre ?", answer: "co2" },
  { question: "Quel est le pH d’une solution neutre ?", answer: "7" },
  { question: "Quelle est la masse molaire de l’eau (H2O) ?", answer: "18" },
  { question: "Quelle est la formule chimique du dioxyde de carbone ?", answer: "co2" },

  // 🏀 Sport (20)
  { question: "Quel pays a remporté la Coupe du Monde 2018 ?", answer: "france" },
  { question: "Combien de joueurs dans une équipe de football ?", answer: "11" },
  { question: "Quel est le sport national au Japon ?", answer: "sumo" },
  { question: "Qui détient le record du 100m ?", answer: "bolt" },
  { question: "Quel est le surnom de Michael Jordan ?", answer: "air jordan" },
  { question: "Combien de points pour un panier à 3 points au basket ?", answer: "3" },
  { question: "Quel sport se joue avec un volant ?", answer: "badminton" },
  { question: "Quel pays a inventé le football ?", answer: "angleterre" },
  { question: "Quel nageur a remporté le plus de médailles olympiques ?", answer: "phelps" },
  { question: "Combien de trous dans un parcours de golf standard ?", answer: "18" },
  { question: "Quel est le sport le plus pratiqué dans le monde ?", answer: "football" },
  { question: "Quel sport se joue sur un ring ?", answer: "boxe" },
  { question: "Quel athlète est surnommé ‘le roi de la terre battue’ ?", answer: "nadal" },
  { question: "Quel est le tournoi le plus prestigieux au tennis ?", answer: "wimbledon" },
  { question: "Quel sport utilise une crosse et une rondelle ?", answer: "hockey sur glace" },
  { question: "Quel est le pays d’origine du cricket ?", answer: "angleterre" },
  { question: "Combien de joueurs sur un terrain de volley ?", answer: "6" },
  { question: "Quel est le sport national de l’Inde ?", answer: "hockey sur gazon" },
  { question: "Quel est le seul pays à avoir participé à toutes les Coupes du Monde ?", answer: "brésil" },
  { question: "Quel est le sport le plus populaire aux États-Unis ?", answer: "football américain" },

  // 🔍 Découverte (20)
  { question: "Qui a découvert la gravité ?", answer: "newton" },
  { question: "Qui a découvert l’Amérique ?", answer: "colomb" },
  { question: "Quel scientifique a inventé l’ampoule électrique ?", answer: "edison" },
  { question: "Qui a inventé le téléphone ?", answer: "graham bell" },
  { question: "Qui a découvert la radioactivité ?", answer: "becquerel" },
  { question: "Qui a découvert la pénicilline ?", answer: "fleming" },
  { question: "Qui a proposé la théorie de l'évolution ?", answer: "darwin" },
  { question: "Qui a découvert l’insuline ?", answer: "banting" },
  { question: "Qui a découvert la structure de l’ADN ?", answer: "watson et crick" },
  { question: "Qui a découvert l’oxygène ?", answer: "priestley" },
  { question: "Quel navigateur a fait le tour du monde ?", answer: "magellan" },
  { question: "Qui a inventé l’imprimerie ?", answer: "gutenberg" },
  { question: "Qui a découvert la loi de la relativité ?", answer: "einstein" },
  { question: "Qui a été le premier homme sur la Lune ?", answer: "neil armstrong" },
  { question: "Qui a découvert les Amériques pour l’Europe ?", answer: "colomb" },
  { question: "Qui a découvert l’héliocentrisme ?", answer: "copernic" },
  { question: "Qui a prouvé que la Terre tourne autour du Soleil ?", answer: "galilée" },
  { question: "Qui a découvert la circulation du sang ?", answer: "harvey" },
  { question: "Qui a découvert le vaccin contre la rage ?", answer: "pasteur" },
  { question: "Qui a inventé Internet ?", answer: "berners-lee" },

  // 🧬 Biologie (20)
  { question: "Quelle cellule transporte l’oxygène ?", answer: "globule rouge" },
  { question: "Combien de chromosomes chez l’humain ?", answer: "46" },
  { question: "Quel organe produit l’insuline ?", answer: "pancréas" },
  { question: "Quel est l’organe principal du système nerveux ?", answer: "cerveau" },
  { question: "Quelle est la plus grande cellule du corps humain ?", answer: "ovule" },
  { question: "Quel est l’organe du système respiratoire ?", answer: "poumon" },
  { question: "Qu’est-ce qu’un gène ?", answer: "un segment d’adn" },
  { question: "Quelle est la molécule d’énergie de la cellule ?", answer: "atp" },
  { question: "Quel organe filtre le sang ?", answer: "rein" },
  { question: "Quelle est la durée moyenne de grossesse humaine ?", answer: "9 mois" },
  { question: "Quel organe pompe le sang ?", answer: "coeur" },
  { question: "Comment s’appelle l’ensemble des os ?", answer: "squelette" },
  { question: "Quelle est la fonction des globules blancs ?", answer: "défense immunitaire" },
  { question: "Qu’est-ce que l’ADN ?", answer: "acide désoxyribonucléique" },
  { question: "Quel organe contrôle les hormones ?", answer: "hypothalamus" },
  { question: "Combien de paires de côtes possède l’humain ?", answer: "12" },
  { question: "Quel organe est responsable de la digestion chimique ?", answer: "estomac" },
  { question: "Quel est le liquide principal du corps humain ?", answer: "eau" },
  { question: "Comment s’appelle le pigment de la peau ?", answer: "mélanine" },
  { question: "Quelle est la fonction des reins ?", answer: "filtrer le sang" },

  // Suite (math, anatomie, capitales, emoji drapeaux) dans le message suivant…

  // ➗ Mathématiques (20)
  { question: "Combien font 7 x 8 ?", answer: "56" },
  { question: "Quel est le carré de 9 ?", answer: "81" },
  { question: "Quelle est la racine carrée de 144 ?", answer: "12" },
  { question: "Combien y a-t-il de côtés dans un hexagone ?", answer: "6" },
  { question: "Quelle est la valeur de Pi approximativement ?", answer: "3.14" },
  { question: "Combien de degrés dans un angle droit ?", answer: "90" },
  { question: "Que vaut 2 puissance 5 ?", answer: "32" },
  { question: "Quel est le périmètre d’un carré de 4 cm de côté ?", answer: "16" },
  { question: "Combien y a-t-il de centimètres dans un mètre ?", answer: "100" },
  { question: "Combien de zéros dans un million ?", answer: "6" },
  { question: "Combien font 15 % de 200 ?", answer: "30" },
  { question: "Combien de faces a un cube ?", answer: "6" },
  { question: "Quel est le terme pour une figure à 5 côtés ?", answer: "pentagone" },
  { question: "Quelle est l’unité de base de la masse ?", answer: "kilogramme" },
  { question: "Combien font 150+300 ?", answer: "450" },
  { question: "Combien de secondes dans une heure ?", answer: "3600" },
  { question: "Combien de jours dans une année bissextile ?", answer: "366" },
  { question: "Combien de côtés a un triangle équilatéral ?", answer: "3" },
  { question: "Quel est le triple de 15 ?", answer: "45" },
  { question: "Combien de litres dans un mètre cube ?", answer: "1000" },

  // 🧠 Anatomie (20)
  { question: "Combien d’os dans le corps humain ?", answer: "206" },
  { question: "Quel est le plus long os du corps humain ?", answer: "fémur" },
  { question: "Combien de dents possède un adulte ?", answer: "32" },
  { question: "Quel organe est responsable de la vision ?", answer: "oeil" },
  { question: "Quel muscle contrôle la respiration ?", answer: "diaphragme" },
  { question: "Combien de ventricules a le cœur ?", answer: "2" },
  { question: "Quel est l’organe principal de l’audition ?", answer: "oreille" },
  { question: "Comment s'appelle le tube digestif principal ?", answer: "intestin" },
  { question: "Quel est le plus gros organe du corps humain ?", answer: "peau" },
  { question: "Combien de lobes dans le cerveau humain ?", answer: "4" },
  { question: "Où se trouve le foie ?", answer: "l'abdomen" },
  { question: "Combien de muscles dans le corps humain ?", answer: "600" },
  { question: "Quel organe sécrète la bile ?", answer: "foie" },
  { question: "Quel est le rôle des globules blancs ?", answer: "protéger contre les infections" },
  { question: "Comment s'appelle le système de commande du corps ?", answer: "système nerveux" },
  { question: "Quel est l’organe principal de l’odorat ?", answer: "nez" },
  { question: "Combien de côtes chez l’être humain ?", answer: "24" },
  { question: "Quel organe est situé dans le thorax ?", answer: "poumon" },
  { question: "Comment s'appelle le squelette du dos ?", answer: "colonne vertébrale" },
  { question: "Quelle est la fonction des reins ?", answer: "filtrer le sang" },

  // 🏛️ Capitales (20)
  { question: "Quelle est la capitale de la France ?", answer: "paris" },
  { question: "Quelle est la capitale du Brésil ?", answer: "brasilia" },
  { question: "Quelle est la capitale de l’Australie ?", answer: "canberra" },
  { question: "Quelle est la capitale du Canada ?", answer: "ottawa" },
  { question: "Quelle est la capitale du Japon ?", answer: "tokyo" },
  { question: "Quelle est la capitale de la Chine ?", answer: "pékin" },
  { question: "Quelle est la capitale de l’Afrique du Sud ?", answer: "pretoria" },
  { question: "Quelle est la capitale de la Russie ?", answer: "moscou" },
  { question: "Quelle est la capitale de l’Italie ?", answer: "rome" },
  { question: "Quelle est la capitale du Sénégal ?", answer: "dakar" },
  { question: "Quelle est la capitale du Maroc ?", answer: "rabat" },
  { question: "Quelle est la capitale de l’Algérie ?", answer: "alger" },
  { question: "Quelle est la capitale de l’Inde ?", answer: "new delhi" },
  { question: "Quelle est la capitale de la Corée du Sud ?", answer: "séoul" },
  { question: "Quelle est la capitale de la RDC ?", answer: "kinshasa" },
  { question: "Quelle est la capitale du Kenya ?", answer: "nairobi" },
  { question: "Quelle est la capitale de l’Espagne ?", answer: "madrid" },
  { question: "Quelle est la capitale de l’Allemagne ?", answer: "berlin" },
  { question: "Quelle est la capitale de la Grèce ?", answer: "athènes" },
  { question: "Quelle est la capitale de la Suède ?", answer: "stockholm" },

  // 🏳️‍🌈 Emoji Drapeaux (10)
  { question: "Quel pays est représenté par 🇫🇷 ?", answer: "france" },
  { question: "Quel pays est représenté par 🇯🇵 ?", answer: "japon" },
  { question: "Quel pays est représenté par 🇺🇸 ?", answer: "usa" },
  { question: "Quel pays est représenté par 🇬🇧 ?", answer: "royaume-uni, Angleterre, grande Bretagne" },
  { question: "Quel pays est représenté par 🇨🇳 ?", answer: "chine" },
  { question: "Quel pays est représenté par 🇧🇷 ?", answer: "brésil" },
  { question: "Quel pays est représenté par 🇨🇦 ?", answer: "canada" },
  { question: "Quel pays est représenté par 🇮🇹 ?", answer: "italie" },
  { question: "Quel pays est représenté par 🇩🇪 ?", answer: "allemagne" },
  { question: "Quel pays est représenté par 🇷🇺 ?", answer: "russie" },
 
  { question: "Quelle est la capitale de la France ?", answer: "paris" },
  { question: "Combien y a-t-il de continents sur Terre ?", answer: "7" },
  { question: "Qui a peint La Joconde ?", answer: "léonard de vinci" },
  { question: "Quelle est la plus grande planète du système solaire ?", answer: "jupiter" },
  { question: "Quelle est la monnaie du Japon ?", answer: "yen" },
  { question: "Combien de côtés a un hexagone ?", answer: "6" },
  { question: "En quelle année a eu lieu la Révolution française ?", answer: "1789" },
  { question: "Quel métal est utilisé pour fabriquer l’or ?", answer: "or" },
  { question: "Quel est l'organe principal du système circulatoire ?", answer: "coeur" },
  { question: "Combien font 7 x 8 ?", answer: "56" },
  { question: "Quel pays a gagné la Coupe du Monde 2018 ?", answer: "france" },
  { question: "Quelle est la capitale de l’Allemagne ?", answer: "berlin" },
  { question: "Combien de lettres dans l’alphabet français ?", answer: "26" },
  { question: "Quel est l'élément chimique H2O ?", answer: "eau" },
  { question: "Qui est le dieu du tonnerre dans la mythologie nordique ?", answer: "thor" },
  { question: "Quel animal est le roi de la savane ?", answer: "lion" },
  { question: "Combien de joueurs dans une équipe de football ?", answer: "11" },
  { question: "Quel est le plus grand océan du monde ?", answer: "pacifique" },
  { question: "Combien y a-t-il de jours dans une année bissextile ?", answer: "366" },
  { question: "Quelle est la langue la plus parlée au monde ?", answer: "mandarin" },
  { question: "Quel est le plus haut sommet du monde ?", answer: "everest" },
  { question: "Qui a écrit Roméo et Juliette ?", answer: "shakespeare" },
  { question: "Combien de couleurs dans l’arc-en-ciel ?", answer: "7" },
  { question: "Quel est le symbole chimique de l’oxygène ?", answer: "o" },
  { question: "Quelle planète est la plus proche du soleil ?", answer: "mercure" },
  { question: "Quelle est la capitale de la RDC ?", answer: "kinshasa" },
  { question: "Combien de zéros dans un milliard ?", answer: "9" },
  { question: "Quel pays a pour capitale Abuja ?", answer: "nigeria" },
  { question: "Quel est l’inventeur de la théorie de la relativité ?", answer: "einstein" },
  { question: "Quel est l’animal le plus rapide du monde ?", answer: "guépard" },
{ question: "Quel est le plus long fleuve du monde ?", answer: "nil" },
{ question: "Quelle est la capitale de l’Espagne ?", answer: "madrid" },
{ question: "Quel est le symbole chimique du fer ?", answer: "fe" },
{ question: "Combien d’heures dans une journée ?", answer: "24" },
{ question: "Quel est le pays d’origine du sushi ?", answer: "japon" },
{ question: "Quel est l’auteur de Harry Potter ?", answer: "jk rowling" },
{ question: "Dans quelle ville se trouve la Tour Eiffel ?", answer: "paris" },
{ question: "Quelle mer borde l’Égypte ?", answer: "mer rouge" },
{ question: "Quel est le sport national du Brésil ?", answer: "football" },
{ question: "Combien de joueurs au basketball ?", answer: "5" },
{ question: "Quel est l’instrument à cordes typique d’un orchestre ?", answer: "violon" },
{ question: "Combien de pattes une araignée possède-t-elle ?", answer: "8" },
{ question: "Dans quelle galaxie vivons-nous ?", answer: "voie lactée" },
{ question: "Quel est l’animal emblème de l’Australie ?", answer: "kangourou" },
{ question: "Combien de lunes possède la Terre ?", answer: "1" },
{ question: "Quelle est la capitale de l’Italie ?", answer: "rome" },
{ question: "Quel est le nom du président actuel de la RDC (2024) ?", answer: "félix tshisekedi" },
{ question: "Quel est le continent le plus peuplé ?", answer: "asie" },
{ question: "Comment s'appelle le gaz qu'on respire ?", answer: "oxygène" },
{ question: "Combien de mois dans une année ?", answer: "12" },
{ question: "Quel est le plus petit pays du monde ?", answer: "vatican" },
{ question: "Quelle langue parle-t-on au Brésil ?", answer: "portugais" },
{ question: "Combien de dents a un adulte normalement ?", answer: "32" },
{ question: "Combien de secondes dans une minute ?", answer: "60" },
{ question: "Qui a inventé l’ampoule électrique ?", answer: "edison" },
{ question: "Quelle est la première lettre de l’alphabet grec ?", answer: "alpha" },
{ question: "Quel pays a pour capitale Rabat ?", answer: "maroc" },
{ question: "Quel animal pond des œufs et allaite ?", answer: "ornithorynque" },
{ question: "Combien y a-t-il de couleurs primaires ?", answer: "3" },
{ question: "Quel est le métal précieux de couleur jaune ?", answer: "or" },
{ question: "Quel est le cri du chien ?", answer: "aboiement" },
{ question: "Quelle est la capitale du Canada ?", answer: "ottawa" },
{ question: "Dans quel pays se trouve le mont Kilimandjaro ?", answer: "tanzanie" },
{ question: "Quel est l'élément chimique du sel de table ?", answer: "sodium" },
{ question: "Quel est le plus grand désert du monde ?", answer: "antarctique" },
{ question: "Quel est le nom du satellite naturel de la Terre ?", answer: "lune" },
{ question: "Qui a écrit L’Iliade et l’Odyssée ?", answer: "homère" },
{ question: "Quelle est la capitale du Kenya ?", answer: "nairobi" },
{ question: "Quel fruit est jaune et courbé ?", answer: "banane" },
{ question: "Combien de doigts a un humain ?", answer: "10" },
{ question: "Qui est l’inventeur de Facebook ?", answer: "mark zuckerberg" },
{ question: "Quel est le plus grand pays du monde ?", answer: "russie" },
{ question: "Combien de jours en février pendant une année bissextile ?", answer: "29" },
{ question: "Quel est l’autre nom du Sahara ?", answer: "désert du sahara" },
{ question: "Quelle est la devise de la République Française ?", answer: "liberté égalité fraternité" },
{ question: "Quelle est la capitale de la Chine ?", answer: "pékin" },
{ question: "Quel animal a une mémoire légendaire ?", answer: "éléphant" },
{ question: "Quel est l’animal emblème de la Chine ?", answer: "panda" },
{ question: "Quel est le sport où on utilise une raquette et un volant ?", answer: "badminton" },
{ question: "Qui est mon créateur  ?", answer: "merdi" },
{ question: "Qui est l'auteur du manga bleach' ?", answer: "tite kubo" },
  // 🏀 SPORT (20)
  { question: "Quel footballeur a remporté le plus de Ballon d'Or ?", answer: "messi" },
  { question: "Quel pays a remporté la Coupe du Monde 2018 ?", answer: "france" },
  { question: "Qui est surnommé le 'Roi du football' ?", answer: "pelé" },
  { question: "Combien de joueurs composent une équipe de football sur le terrain ?", answer: "11" },
  { question: "Quel est le sport principal des Jeux Olympiques d'hiver ?", answer: "ski" },
  { question: "Combien de points vaut un tir à trois points au basketball ?", answer: "3" },
  { question: "Quelle est la surface de jeu au tennis ?", answer: "court" },
  { question: "Qui a remporté Roland-Garros 2022 chez les hommes ?", answer: "nadal" },
  { question: "Quel est le pays d’origine du judo ?", answer: "japon" },
  { question: "Qui est le recordman mondial du 100 mètres ?", answer: "bolt" },
  { question: "Combien de temps dure un match de football ?", answer: "90" },
  { question: "Quel est le pays d’origine du rugby ?", answer: "angleterre" },
  { question: "Qui a remporté le plus de Grands Prix de F1 ?", answer: "hamilton" },
  { question: "Quel sport est pratiqué dans un ring ?", answer: "boxe" },
  { question: "Dans quel sport utilise-t-on une crosse ?", answer: "hockey" },
  { question: "Combien de sets faut-il gagner pour remporter un match en Grand Chelem chez les hommes ?", answer: "3" },
  { question: "Quelle nation est la plus titrée en handball masculin ?", answer: "france" },
  { question: "Dans quel sport y a-t-il des touchdowns ?", answer: "football américain" },
  { question: "Combien de joueurs sur un terrain de volley ?", answer: "6" },
  { question: "Quelle est la nationalité de Kylian Mbappé ?", answer: "français" },

  // 📜 HISTOIRE (20)
  { question: "En quelle année a eu lieu la Révolution française ?", answer: "1789" },
  { question: "Qui fut le premier président des États-Unis ?", answer: "washington" },
  { question: "Quel mur est tombé en 1989 ?", answer: "berlin" },
  { question: "Qui a dirigé l’Allemagne pendant la Seconde Guerre mondiale ?", answer: "hitler" },
  { question: "Quel explorateur a découvert l’Amérique ?", answer: "colomb" },
  { question: "Comment s'appelait l'empereur de France en 1804 ?", answer: "napoléon" },
  { question: "Quel pays a lancé la bombe atomique sur Hiroshima ?", answer: "usa" },
  { question: "Qui a été assassiné à Dallas en 1963 ?", answer: "kennedy" },
  { question: "Quel roi a été guillotiné pendant la Révolution française ?", answer: "louis" },
  { question: "Quel empire était dirigé par César ?", answer: "rome" },
  { question: "Comment s'appelait le régime politique de Staline ?", answer: "communisme" },
  { question: "Qui a libéré la France en 1944 ?", answer: "de gaulle" },
  { question: "Quel pays a colonisé le Congo ?", answer: "belgique" },
  { question: "Où est né Nelson Mandela ?", answer: "afrique du sud" },
  { question: "Qui a inventé l’imprimerie ?", answer: "gutenberg" },
  { question: "En quelle année s’est terminé la Seconde Guerre mondiale ?", answer: "1945" },
  { question: "Qui a découvert la pénicilline ?", answer: "fleming" },
  { question: "Quelle guerre a opposé le Nord et le Sud des USA ?", answer: "sécession" },
  { question: "Quel traité a mis fin à la Première Guerre mondiale ?", answer: "versailles" },
  { question: "Quel pays a envahi la Pologne en 1939 ?", answer: "allemagne" },

  // ⚡ MYTHOLOGIE (20)
  { question: "Quel dieu grec est le roi de l’Olympe ?", answer: "zeus" },
  { question: "Qui est le dieu de la mer dans la mythologie grecque ?", answer: "poséidon" },
  { question: "Quel héros a tué le Minotaure ?", answer: "thésée" },
  { question: "Comment s’appelle le dieu nordique du tonnerre ?", answer: "thor" },
  { question: "Qui est le messager des dieux grecs ?", answer: "hermès" },
  { question: "Quel dieu égyptien a une tête de chacal ?", answer: "anubis" },
  { question: "Qui est la déesse de l’amour dans la mythologie romaine ?", answer: "vénus" },
  { question: "Quel titan a volé le feu aux dieux ?", answer: "prométhée" },
  { question: "Quel monstre a des serpents pour cheveux ?", answer: "méduse" },
  { question: "Qui est le dieu de la guerre chez les Grecs ?", answer: "arès" },
  { question: "Quel est le royaume des morts chez les Grecs ?", answer: "hadès" },
  { question: "Quel héros a affronté l’Hydre de Lerne ?", answer: "hercule" },
  { question: "Quel cheval ailé vient de la mythologie grecque ?", answer: "pégase" },
  { question: "Comment s'appelle l’arbre sacré des Vikings ?", answer: "ygdrassil" },
  { question: "Qui a ouvert la boîte contenant tous les maux ?", answer: "pandore" },
  { question: "Quel dieu égyptien est associé au soleil ?", answer: "rê" },
  { question: "Quel est le nom latin de Zeus ?", answer: "jupiter" },
  { question: "Quel est le dieu de la forge chez les Grecs ?", answer: "héphaïstos" },
  { question: "Quel dieu romain correspond à Hadès ?", answer: "pluton" },
  { question: "Quelle déesse romaine est l’équivalent d’Athéna ?", answer: "minerve" },

  // ⚗️ CHIMIE (20)
  { question: "Quel est le symbole chimique de l’eau ?", answer: "h2o" },
  { question: "Quel gaz les plantes absorbent-elles ?", answer: "co2" },
  { question: "Quel est le numéro atomique de l’oxygène ?", answer: "8" },
  { question: "Quel est le métal liquide à température ambiante ?", answer: "mercure" },
  { question: "Quel gaz est essentiel à la respiration humaine ?", answer: "oxygène" },
  { question: "Quel est l’élément chimique avec le symbole Fe ?", answer: "fer" },
  { question: "Quelle est la formule du sel de table ?", answer: "nacl" },
  { question: "Quel est l’élément le plus léger ?", answer: "hydrogène" },
  { question: "Quel est l’élément chimique avec le symbole Au ?", answer: "or" },
  { question: "Quel acide est contenu dans l’estomac ?", answer: "chlorhydrique" },
  { question: "Quel est le pH d’une solution neutre ?", answer: "7" },
  { question: "Quel est le gaz le plus abondant dans l’air ?", answer: "azote" },
  { question: "Quel est l’unité de masse atomique ?", answer: "uma" },
  { question: "Quelle est la formule chimique du dioxyde de carbone ?", answer: "co2" },
  { question: "Quel métal est utilisé dans les piles ?", answer: "lithium" },
  { question: "Quel est l’état de l’eau à 0 degré ?", answer: "glace" },
  { question: "Quel est le nom du tableau des éléments ?", answer: "périodique" },
  { question: "Quel est le nom du gaz qui fait rougir une flamme ?", answer: "oxygène" },
  { question: "Quel est le nom du processus de rouille ?", answer: "oxydation" },
  { question: "Comment s’appelle le changement de solide à gaz ?", answer: "sublimation" },

  // 🐾 ZOOLOGIE (20)
  { question: "Quel est l’animal terrestre le plus rapide ?", answer: "guépard" },
  { question: "Quel mammifère est capable de voler ?", answer: "chauve-souris" },
  { question: "Quel animal a une mémoire exceptionnelle ?", answer: "éléphant" },
  { question: "Quel est le plus grand mammifère marin ?", answer: "baleine" },
  { question: "Quel est le seul oiseau qui ne vole pas mais court vite ?", answer: "autruche" },
  { question: "Quel insecte produit du miel ?", answer: "abeille" },
  { question: "Quel est le félin le plus grand ?", answer: "tigre" },
  { question: "Quel animal change de couleur pour se camoufler ?", answer: "caméléon" },
  { question: "Quel animal est connu pour sa lenteur ?", answer: "paresseux" },
  { question: "Quel est le roi de la savane ?", answer: "lion" },
  { question: "Quel est le plus grand reptile du monde ?", answer: "crocodile" },
  { question: "Quel animal a une bosse sur le dos ?", answer: "chameau" },
  { question: "Quel animal pond des œufs et allaite ses petits ?", answer: "ornithorynque" },
  { question: "Quel animal a des tentacules et un bec ?", answer: "pieuvre" },
  { question: "Quel oiseau est symbole de la paix ?", answer: "colombe" },
  { question: "Quel poisson est connu pour sa mémoire courte ?", answer: "poisson rouge" },
  { question: "Quel insecte vit en colonie avec une reine ?", answer: "fourmi" },
  { question: "Quel animal vit à la fois dans l’eau et sur terre ?", answer: "grenouille" },
  { question: "Quel est le plus grand oiseau du monde ?", answer: "autruche" },
  { question: "Quel animal vit en Antarctique et aime la glace ?", answer: "manchot" },
   { question: "Quelle était la première civilisation connue de l'histoire  ?", answer: "sumérienne" },
    { question: "Quelle est la date de la signature de l'armistice ' ?", answer: "11 novembre 1918" },
     { question: "Qui était le pharaon Egyptien qui a établi le culte d'un dieu unique Aton ' ?", answer: "Akhenaton" },
      { question: "Qui a formulé la théorie des trois vies: la politique, la vie contemplative et la vie plaisante  ?", answer: "aristote" },
       { question: "Qui a introduit le concept de l'aliénation dans sa théorie sociale ' ?", answer: "karl marx" },
        { question: "Quel philosophe a posé la question «Que sais-je ?» comme point de départ de sa réflexion  ?", answer: "socrate" },
  
          { question: "Quelle balisage est utilisé pour définir un paragraphe de texte en HTML ?", answer: "p" },
           { question: "Quelle balise est utilisée pour créé une liste à puces en HTML  ?", answer: "ul" },
            { question: "Quel roi a essayé de ruer Jésus quand il était bébé ?", answer: "hérode" },
             { question: "Qui a marché sur l'eau avec Jésus ?", answer: "pierre" },
              { question: "Qui était appelé «L'homme de douleurs » dans la prophétie d'esaïe ?", answer: "jésus" },
               { question: "Quelle est la Partie matériel ou physique de l'ordinateur  ?", answer: "hardware" },
                { question: "comment est appelé l'adresse numérique unique identifiant un appareil sur un réseau  ?", answer: "ip" },
                 { question: "Que signifie le symbole √ ?", answer: "racine carrée" },
                  { question: "combien des faces a un cube  ?", answer: "6" },
                    { question: "Quel est ce pays 🇺🇬 ?", answer: "ouganda" },
                      { question: "Quel est ce pays 🇦🇴 ?", answer: "angola" },
                        { question: "Quel est ce pays 🇨🇳?", answer: "chine" },
                          { question: "Quel est ce pays 🇪🇬 ?", answer: "egypte" },
                            { question: "Quel est ce pays 🇬🇷 ?", answer: "grèce" },
                              { question: "Quel est ce pays 🇲🇬 ?", answer: "madagascar" },
     { question: "Qui est mon créateur  ?", answer: "merdi" }

];


const activeSessions = {};

module.exports = {
  config: {
    name: "quizz",
    role: "0",
    author: "Merdi Madimba",
    version: "1.0",
    description: "Quiz culture générale avec score",
    category: "🎮 Jeu"
  },

  onStart: async function ({ event, message, usersData }) {
    const threadID = event.threadID;

    if (activeSessions[threadID]) {
      return message.reply("❗ Un quiz est déjà en cours !");
    }

    // Sélectionner 10 questions aléatoires
    const selected = [...questions].sort(() => 0.5 - Math.random()).slice(0, 100);
    const scores = {};

    let currentIndex = 0;
    let currentQuestion = null;
    let timeoutID = null;
    let answered = false;

    const sendQuestion = async () => {
      if (currentIndex >= selected.length) {
        // Fin du quiz
        const sorted = Object.entries(scores).sort((a, b) => b[1] - a[1]);
        let finalBoard = "🏁 Fin du quiz ! Résultat final :\n";
        let winner = sorted[0]?.[0] || "Aucun";

        for (let [name, pts] of sorted) {
          finalBoard += `🏅 ${name} : ${pts} pts\n`;
        }

        finalBoard += `👑 Vainqueur : ${winner}`;
        await message.send(finalBoard);
        delete activeSessions[threadID];
        return;
      }

      answered = false;
      currentQuestion = selected[currentIndex];

      await message.send(`❓ Question ${currentIndex + 1} : ${currentQuestion.question}`);

      timeoutID = setTimeout(async () => {
        if (!answered) {
          await message.send(`⏰ Temps écoulé ! La bonne réponse était : ${currentQuestion.answer}`);
          currentIndex++;
          sendQuestion();
        }
      }, 10000);
    };

    activeSessions[threadID] = async ({ event, message }) => {
      if (!currentQuestion || answered) return;

      const senderName = await usersData.getName(event.senderID);
      const msg = event.body?.toLowerCase().trim();

      if (msg === currentQuestion.answer) {
        answered = true;
        clearTimeout(timeoutID);

        scores[senderName] = (scores[senderName] || 0) + 10;

        // Scoreboard
        let board = "📊 Score actuel :\n";
        for (let [name, pts] of Object.entries(scores)) {
          board += `🏅 ${name} : ${pts} pts\n`;
        }

        await message.reply(`✅ Bonne réponse de ${senderName} !\n\n${board}`);
        currentIndex++;
        setTimeout(sendQuestion, 1000);
      }
    };

    sendQuestion();
  },

  onChat: function (context) {
    const handler = activeSessions[context.event.threadID];
    if (handler) handler(context);
  }
};
