const questions = [
  { question: "qui est le professeur de yuji itadori ?\n🎌Jujutsu Kaisen🎌", answer: "satoru gojo" },
  { question: "quel est le nom du démon qui partage le corps de yuji ?\n🎌Jujutsu Kaisen🎌", answer: "ryomen sukuna" },
  { question: "quel est le lycée où sont formés les exorcistes ?\n🎌Jujutsu Kaisen🎌", answer: "lycée tokyo d'exorcisme" },
  { question: "quel est le nom de la technique héréditaire du clan gojo ?\n🎌Jujutsu Kaisen🎌", answer: "six yeux" },
  { question: "quelle est la technique spéciale de toge inumaki ?\n🎌Jujutsu Kaisen🎌", answer: "paroles maudites" },
  { question: "quel est le nom complet de megumi ?\n🎌Jujutsu Kaisen🎌", answer: "megumi fushiguro" },
  { question: "qui est le directeur du lycée d’exorcisme de tokyo ?\n🎌Jujutsu Kaisen🎌", answer: "masamichi yaga" },
  { question: "quel objet contient les doigts de sukuna ?\n🎌Jujutsu Kaisen🎌", answer: "talismans maudits" },
  { question: "qui est la seule fille de l’équipe principale ?\n🎌Jujutsu Kaisen🎌", answer: "nobara kugisaki" },
  { question: "quelle est la malédiction qui manipule les poupées ?\n🎌Jujutsu Kaisen🎌", answer: "mechamaru" },
  { question: "quel est le grade de yuji lorsqu’il débute ?\n🎌Jujutsu Kaisen🎌", answer: "grade 4" },
  { question: "comment s'appelle le panda dans le lycée ?\n🎌Jujutsu Kaisen🎌", answer: "panda" },
  { question: "quelle technique permet de créer une barrière infinie ?\n🎌Jujutsu Kaisen🎌", answer: "infini" },
  { question: "quel est le nom du frère maudit de choso ?\n🎌Jujutsu Kaisen🎌", answer: "kechizu" },
  { question: "quel est le nom du personnage qui contrôle le sang ?\n🎌Jujutsu Kaisen🎌", answer: "choso" },
  { question: "quelle technique utilise nanami ?\n🎌Jujutsu Kaisen🎌", answer: "ratio" },
  { question: "quel est le vrai nom de geto ?\n🎌Jujutsu Kaisen🎌", answer: "suguru geto" },
  { question: "qui est l’ennemi principal dans le film jujutsu kaisen 0 ?\n🎌Jujutsu Kaisen🎌", answer: "suguru geto" },
  { question: "quel est le nom du personnage possédé par sukuna ?\n🎌Jujutsu Kaisen🎌", answer: "yuji itadori" },
  { question: "quelle est la technique de combat de nobara ?\n🎌Jujutsu Kaisen🎌", answer: "marteau et clous" },
  { question: "qui utilise le style de projection ?\n🎌Jujutsu Kaisen🎌", answer: "naoya zenin" },
  { question: "qui est la sorcière de kyoto utilisant une hache ?\n🎌Jujutsu Kaisen🎌", answer: "mai zenin" },
  { question: "quelle est la forme ultime de sukuna ?\n🎌Jujutsu Kaisen🎌", answer: "forme à 4 bras" },
  { question: "qui est le rival principal de gojo à l’école ?\n🎌Jujutsu Kaisen🎌", answer: "geto" },
  { question: "quel personnage veut venger la mort de ses frères maudits ?\n🎌Jujutsu Kaisen🎌", answer: "choso" },
  { question: "quelle est la forme de technique la plus puissante ?\n🎌Jujutsu Kaisen🎌", answer: "extension de domaine" },
  { question: "comment s’appelle le domaine de gojo ?\n🎌Jujutsu Kaisen🎌", answer: "infini illimité" },
  { question: "qui est le plus puissant exorciste vivant ?\n🎌Jujutsu Kaisen🎌", answer: "satoru gojo" },
  { question: "quelle est la malédiction représentant la peur de la mer ?\n🎌Jujutsu Kaisen🎌", answer: "dagon" },
  { question: "quelle est l’identité de l’antagoniste aux points de suture ?\n🎌Jujutsu Kaisen🎌", answer: "mahito" },
  { question: "qui manipule les âmes avec sa main ?\n🎌Jujutsu Kaisen🎌", answer: "mahito" },
  { question: "quelle est la spécialité de nanami ?\n🎌Jujutsu Kaisen🎌", answer: "ratio technique" },
  { question: "qui est le maître de yuta ?\n🎌Jujutsu Kaisen🎌", answer: "gojo" },
  { question: "quel objet contient rika dans le film ?\n🎌Jujutsu Kaisen🎌", answer: "bague" },
  { question: "qui tue mahito ?\n🎌Jujutsu Kaisen🎌", answer: "kenjaku" },
  { question: "qui est kenjaku ?\n🎌Jujutsu Kaisen🎌", answer: "possesseur du corps de geto" },
  { question: "quelle est l’arme principale de yuta ?\n🎌Jujutsu Kaisen🎌", answer: "katana" },
  { question: "qui utilise une technique avec des cheveux ?\n🎌Jujutsu Kaisen🎌", answer: "kusakabe" },
  { question: "qui est la présidente de la classe de megumi ?\n🎌Jujutsu Kaisen🎌", answer: "tsukimi" },
  { question: "quel est le lien entre gojo et le clan zenin ?\n🎌Jujutsu Kaisen🎌", answer: "rivalité de clans" },
  { question: "quel est le niveau de yuki tsukumo ?\n🎌Jujutsu Kaisen🎌", answer: "grade spécial" },
  { question: "quelle est la technique de maki zenin ?\n🎌Jujutsu Kaisen🎌", answer: "force physique pure" },
  { question: "qui tue naoya zenin ?\n🎌Jujutsu Kaisen🎌", answer: "maki" },
  { question: "quelle technique de gojo permet d’écraser tout autour ?\n🎌Jujutsu Kaisen🎌", answer: "rouge" },
  { question: "quelle technique attire tout vers un point ?\n🎌Jujutsu Kaisen🎌", answer: "bleu" },
  { question: "quelle technique de gojo combine bleu et rouge ?\n🎌Jujutsu Kaisen🎌", answer: "hollow purple" },
  { question: "quel est le nom du clan de megumi ?\n🎌Jujutsu Kaisen🎌", answer: "zenin" },
  { question: "quelle est la condition d’utilisation du domaine ?\n🎌Jujutsu Kaisen🎌", answer: "consommation de beaucoup d’énergie" },
  { question: "quel personnage a été réincarné par kenjaku ?\n🎌Jujutsu Kaisen🎌", answer: "geto" },
  { question: "qui est considéré comme le successeur potentiel de gojo ?\n🎌Jujutsu Kaisen🎌", answer: "yuta okkotsu" },

  { question: "dans naruto shippuden, quel est le nom du démon renard scellé en naruto ?\n🎌Naruto Shippuden🎌", answer: "kyubi" },
  { question: "dans naruto shippuden, qui est le chef de l'akatsuki ?\n🎌Naruto Shippuden🎌", answer: "pain" },
  { question: "dans naruto shippuden, quelle est la vraie identité de tobi ?\n🎌Naruto Shippuden🎌", answer: "obito uchiha" },
  { question: "dans naruto shippuden, quel est le nom de la mère de naruto ?\n🎌Naruto Shippuden🎌", answer: "kushina uzumaki" },
  { question: "dans naruto shippuden, qui est le frère aîné de sasuke ?\n🎌Naruto Shippuden🎌", answer: "itachi uchiha" },
  { question: "dans naruto shippuden, quel bijuu a sept queues ?\n🎌Naruto Shippuden🎌", answer: "chomei" },
  { question: "dans naruto shippuden, quel est le nom de la technique ultime de naruto ?\n🎌Naruto Shippuden🎌", answer: "rasenshuriken" },
  { question: "dans naruto shippuden, quel est le clan de shikamaru ?\n🎌Naruto Shippuden🎌", answer: "nara" },
  { question: "dans naruto shippuden, quel est le nom du père de naruto ?\n🎌Naruto Shippuden🎌", answer: "minato namikaze" },
  { question: "dans naruto shippuden, quel est le rang ninja de kakashi ?\n🎌Naruto Shippuden🎌", answer: "jonin" },
  { question: "dans naruto shippuden, qui peut contrôler les marionnettes ?\n🎌Naruto Shippuden🎌", answer: "kankuro" },
  { question: "dans naruto shippuden, quel est le village caché du sable ?\n🎌Naruto Shippuden🎌", answer: "sunagakure" },
  { question: "dans naruto shippuden, qui a tué asuma ?\n🎌Naruto Shippuden🎌", answer: "hidan" },
  { question: "dans naruto shippuden, quelle technique utilise gai pour ouvrir les portes ?\n🎌Naruto Shippuden🎌", answer: "huit portes" },
  { question: "dans naruto shippuden, quel est le nom du bijuu à une queue ?\n🎌Naruto Shippuden🎌", answer: "shukaku" },
  { question: "dans naruto shippuden, qui est le jinchuriki de huit queues ?\n🎌Naruto Shippuden🎌", answer: "killer bee" },
  { question: "dans naruto shippuden, qui est le sensei de naruto à l’académie ?\n🎌Naruto Shippuden🎌", answer: "iruka" },
  { question: "dans naruto shippuden, quel est le nom de la technique d’invocation de naruto ?\n🎌Naruto Shippuden🎌", answer: "invocation des crapauds" },
  { question: "dans naruto shippuden, qui est la cinquième hokage ?\n🎌Naruto Shippuden🎌", answer: "tsunade" },
  { question: "dans naruto shippuden, qui est l’utilisateur principal du sharigan et rinnegan ?\n🎌Naruto Shippuden🎌", answer: "madara uchiha" },
  { question: "dans naruto shippuden, quelle organisation cherche à capturer les bijuu ?\n🎌Naruto Shippuden🎌", answer: "akatsuki" },
  { question: "dans naruto shippuden, quel personnage utilise l’art explosif ?\n🎌Naruto Shippuden🎌", answer: "deidara" },
  { question: "dans naruto shippuden, quel est le nom complet de pain ?\n🎌Naruto Shippuden🎌", answer: "nagato uzumaki" },
  { question: "dans naruto shippuden, qui est le partenaire de kakuzu ?\n🎌Naruto Shippuden🎌", answer: "hidan" },
  { question: "dans naruto shippuden, qui est le père de sasuke ?\n🎌Naruto Shippuden🎌", answer: "fugaku uchiha" },
  { question: "dans naruto shippuden, qui est le fils de naruto ?\n🎌Naruto Shippuden🎌", answer: "boruto" },
  { question: "dans naruto shippuden, quel est le nom du crapaud maître de naruto ?\n🎌Naruto Shippuden🎌", answer: "fukasaku" },
  { question: "dans naruto shippuden, qui est la sœur de neji ?\n🎌Naruto Shippuden🎌", answer: "hinata" },
  { question: "dans naruto shippuden, qui est le chef du clan aburame ?\n🎌Naruto Shippuden🎌", answer: "shino" },
  { question: "dans naruto shippuden, qui est l’utilisateur du style de sable de fer ?\n🎌Naruto Shippuden🎌", answer: "sasori" },
  { question: "dans naruto shippuden, quel ninja utilise le style lave ?\n🎌Naruto Shippuden🎌", answer: "mei terumi" },
  { question: "dans naruto shippuden, quel est le rang de yamato ?\n🎌Naruto Shippuden🎌", answer: "anbu" },
  { question: "dans naruto shippuden, quel ninja invoque un chien géant ?\n🎌Naruto Shippuden🎌", answer: "kakashi" },
  { question: "dans naruto shippuden, qui tue danzo shimura ?\n🎌Naruto Shippuden🎌", answer: "sasuke uchiha" },
  { question: "dans naruto shippuden, quelle est la spécialité du clan ino ?\n🎌Naruto Shippuden🎌", answer: "contrôle mental" },
  { question: "dans naruto shippuden, quel est le nom du fondateur du clan uchiha ?\n🎌Naruto Shippuden🎌", answer: "madara" },
  { question: "dans naruto shippuden, qui tue kurama ?\n🎌Naruto Shippuden🎌", answer: "personne" },
  { question: "dans naruto shippuden, qui est l’hôte de kurama ?\n🎌Naruto Shippuden🎌", answer: "naruto uzumaki" },
  { question: "dans naruto shippuden, quel est le jutsu interdit de l’akatsuki ?\n🎌Naruto Shippuden🎌", answer: "edo tensei" },
  { question: "dans naruto shippuden, quelle technique utilise les ombres ?\n🎌Naruto Shippuden🎌", answer: "kagemane" },
  { question: "dans naruto shippuden, qui est le coéquipier de neji ?\n🎌Naruto Shippuden🎌", answer: "lee" },
  { question: "dans naruto shippuden, qui est le rival de naruto dans sa team ?\n🎌Naruto Shippuden🎌", answer: "sasuke" },
  { question: "dans naruto shippuden, qui est la sensei de l’équipe de hinata ?\n🎌Naruto Shippuden🎌", answer: "kurenai" },
  { question: "dans naruto shippuden, qui manipule les papillons pour combattre ?\n🎌Naruto Shippuden🎌", answer: "choji" },
  { question: "dans naruto shippuden, quelle est la spécialité de kiba ?\n🎌Naruto Shippuden🎌", answer: "collaboration avec akamaru" },
  { question: "dans naruto shippuden, quel est le frère de itachi ?\n🎌Naruto Shippuden🎌", answer: "sasuke" },
  { question: "dans naruto shippuden, qui a sauvé naruto de zabuza ?\n🎌Naruto Shippuden🎌", answer: "kakashi" },
  { question: "dans naruto shippuden, qui a formé l’équipe taka ?\n🎌Naruto Shippuden🎌", answer: "sasuke" },

  { question: "dans bleach, comment se nomme le zanpakuto principal d'ichigo kurosaki ?\n🎌Bleach🎌", answer: "zangetsu" },
  { question: "dans bleach, qui est le capitaine de la 6e division du gotei 13 ?\n🎌Bleach🎌", answer: "byakuya kuchiki" },
  { question: "dans bleach, comment appelle-t-on la forme évoluée d'un zanpakuto ?\n🎌Bleach🎌", answer: "bankai" },
  { question: "dans bleach, quel personnage est le capitaine traître de la 5e division ?\n🎌Bleach🎌", answer: "sosuke aizen" },
  { question: "dans bleach, qui est l'esprit hollow intérieur d'ichigo ?\n🎌Bleach🎌", answer: "inner hollow" },
  { question: "dans bleach, quelle est la ville natale d'ichigo kurosaki ?\n🎌Bleach🎌", answer: "karakura" },
  { question: "dans bleach, quel est le pouvoir de protection d'orihime inoue ?\n🎌Bleach🎌", answer: "shun shun rikka" },
  { question: "dans bleach, qui dirige la 12e division de recherche ?\n🎌Bleach🎌", answer: "mayuri kurotsuchi" },
  { question: "dans bleach, quel est le nom complet du personnage surnommé chad ?\n🎌Bleach🎌", answer: "yasutora sado" },
  { question: "dans bleach, quelle division est chargée des soins ?\n🎌Bleach🎌", answer: "4e division" },
  { question: "dans bleach, quelle division aime le combat frontal ?\n🎌Bleach🎌", answer: "11e division" },
  { question: "dans bleach, quel est le zanpakuto de renji abarai ?\n🎌Bleach🎌", answer: "zabimaru" },
  { question: "dans bleach, quelle est la forme bankai de zabimaru ?\n🎌Bleach🎌", answer: "soui zabimaru" },
  { question: "dans bleach, qui porte toujours un bob et un éventail ?\n🎌Bleach🎌", answer: "kisuke urahara" },
  { question: "dans bleach, quelle est la technique de déplacement des shinigami ?\n🎌Bleach🎌", answer: "shunpo" },
  { question: "dans bleach, quelle est l'attaque signature d'ichigo ?\n🎌Bleach🎌", answer: "getsuga tensho" },
  { question: "dans bleach, quel est le nom de sa bankai ?\n🎌Bleach🎌", answer: "tensa zangetsu" },
  { question: "dans bleach, qui est le père d'ichigo ?\n🎌Bleach🎌", answer: "isshin kurosaki" },
  { question: "dans bleach, qui est le capitaine de la 11e division ?\n🎌Bleach🎌", answer: "kenpachi zaraki" },
  { question: "dans bleach, comment s'appelle le monde des hollows ?\n🎌Bleach🎌", answer: "hueco mundo" },
  { question: "dans bleach, quel groupe contient les plus puissants arrancars ?\n🎌Bleach🎌", answer: "espada" },
  { question: "dans bleach, quel est le numéro de grimmjow ?\n🎌Bleach🎌", answer: "6" },
  { question: "dans bleach, quel espada peut se transformer deux fois ?\n🎌Bleach🎌", answer: "ulquiorra" },
  { question: "dans bleach, qui est le plus jeune capitaine du gotei 13 ?\n🎌Bleach🎌", answer: "toshirou hitsugaya" },
  { question: "dans bleach, qui est la vice-capitaine de hitsugaya ?\n🎌Bleach🎌", answer: "rangiku matsumoto" },
  { question: "dans bleach, quel est le zanpakuto de byakuya kuchiki ?\n🎌Bleach🎌", answer: "senbonzakura" },
  { question: "dans bleach, quelle division est dirigée par soi fon ?\n🎌Bleach🎌", answer: "2e division" },
  { question: "dans bleach, quel est le zanpakuto de soi fon ?\n🎌Bleach🎌", answer: "suzumebachi" },
  { question: "dans bleach, quel personnage est surnommé le roi des quincy ?\n🎌Bleach🎌", answer: "yhwach" },
  { question: "dans bleach, quel est le nom du groupe ennemi final ?\n🎌Bleach🎌", answer: "wandenreich" },
  { question: "dans bleach, quel est le pouvoir de kyoka suigetsu d'aizen ?\n🎌Bleach🎌", answer: "hypnose totale" },
  { question: "dans bleach, qui dirige les vizards ?\n🎌Bleach🎌", answer: "shinji hirako" },
  { question: "dans bleach, comment s'appelle le chat qui aide ichigo ?\n🎌Bleach🎌", answer: "yoruichi" },
  { question: "dans bleach, quelle était la division d'urahara avant son exil ?\n🎌Bleach🎌", answer: "12e division" },
  { question: "dans bleach, qui est la vice-capitaine de zaraki kenpachi ?\n🎌Bleach🎌", answer: "yachiru kusajishi" },
  { question: "dans bleach, quelle est l'attaque ultime d'ichigo contre aizen ?\n🎌Bleach🎌", answer: "mugetsu" },
  { question: "dans bleach, quel est le nom du monde des âmes ?\n🎌Bleach🎌", answer: "soul society" },
  { question: "dans bleach, qui est le scientifique le plus fou de la soul society ?\n🎌Bleach🎌", answer: "mayuri kurotsuchi" },
  { question: "dans bleach, quel est le bankai de mayuri ?\n🎌Bleach🎌", answer: "konjiki ashisogi jizo" },
  { question: "dans bleach, qui est l'espada numéro 1 ?\n🎌Bleach🎌", answer: "starrk" },
  { question: "dans bleach, quel espada porte deux pistolets ?\n🎌Bleach🎌", answer: "starrk" },
  { question: "dans bleach, quel est l'ennemi final de l'anime ?\n🎌Bleach🎌", answer: "yhwach" },
  { question: "dans bleach, comment se nomme le roi spirituel ?\n🎌Bleach🎌", answer: "reiou" },
  { question: "dans bleach, quel capitaine utilise des jeux pour se battre en bankai ?\n🎌Bleach🎌", answer: "shunsui kyoraku" },
  { question: "dans bleach, quel zanpakuto se divise en deux sabres dès sa base ?\n🎌Bleach🎌", answer: "katen kyokotsu" },
  { question: "dans bleach, quel est le pouvoir principal des quincy ?\n🎌Bleach🎌", answer: "arc spirituel" },
  { question: "dans bleach, quel est le nom de la division des assassins ?\n🎌Bleach🎌", answer: "onmitsukido" },
  { question: "dans bleach, qui est l'espada numéro 4 ?\n🎌Bleach🎌", answer: "ulquiorra" },
  { question: "dans bleach, qui est le capitaine le plus ancien du gotei 13 avant sa mort ?\n🎌Bleach🎌", answer: "yamamoto genryusai" },
  { question: "dans bleach, quel zanpakuto utilise la chaleur et le feu ?\n🎌Bleach🎌", answer: "ryujin jakka" },
  { question: "dans bleach, qui possède le bankai mugetsu ?\n🎌Bleach🎌", answer: "ichigo kurosaki" },
  
  { question: "quel est le nom complet du héros principal ?\n🎌Demon Slayer🎌", answer: "tanjiro kamado" },
  { question: "comment s’appelle la sœur de tanjiro ?\n🎌Demon Slayer🎌", answer: "nezuko kamado" },
  { question: "quel est le nom de la technique principale de tanjiro ?\n🎌Demon Slayer🎌", answer: "souffle de l’eau" },
  { question: "qui est le chef des piliers ?\n🎌Demon Slayer🎌", answer: "kagaya ubuyashiki" },
  { question: "quel démon a tué la famille de tanjiro ?\n🎌Demon Slayer🎌", answer: "muzan kibutsuji" },
  { question: "qui est le pilier du feu ?\n🎌Demon Slayer🎌", answer: "kyojuro rengoku" },
  { question: "comment s'appelle le garçon qui utilise la foudre ?\n🎌Demon Slayer🎌", answer: "zenitsu agatsuma" },
  { question: "comment s’appelle celui qui porte une tête de sanglier ?\n🎌Demon Slayer🎌", answer: "inosuke hashibira" },
  { question: "quelle est la particularité de nezuko en tant que démon ?\n🎌Demon Slayer🎌", answer: "elle résiste au soleil" },
  { question: "quelle organisation combat les démons ?\n🎌Demon Slayer🎌", answer: "corps des pourfendeurs de démons" },
  { question: "quelle est la couleur des cheveux de muzan ?\n🎌Demon Slayer🎌", answer: "noir" },
  { question: "qui est le pilier du son ?\n🎌Demon Slayer🎌", answer: "tengen uzui" },
  { question: "quelle technique utilise zenitsu ?\n🎌Demon Slayer🎌", answer: "souffle de la foudre" },
  { question: "qui est le pilier de l’insecte ?\n🎌Demon Slayer🎌", answer: "shinobu kocho" },
  { question: "qui est la sœur de shinobu ?\n🎌Demon Slayer🎌", answer: "kanae kocho" },
  { question: "comment s'appelle la plus forte lune supérieure ?\n🎌Demon Slayer🎌", answer: "kokushibo" },
  { question: "combien de lunes supérieures existe-t-il ?\n🎌Demon Slayer🎌", answer: "six" },
  { question: "qui est l’ancien pourfendeur devenu lune supérieure ?\n🎌Demon Slayer🎌", answer: "kokushibo" },
  { question: "quelle est la spécialité de muzan ?\n🎌Demon Slayer🎌", answer: "créer des démons" },
  { question: "quelle est la faiblesse principale des démons ?\n🎌Demon Slayer🎌", answer: "lumière du soleil" },
  { question: "qui est le pilier de la brume ?\n🎌Demon Slayer🎌", answer: "muichiro tokito" },
  { question: "qui est le pilier de l’amour ?\n🎌Demon Slayer🎌", answer: "mitsuri kanroji" },
  { question: "qui est le pilier de la pierre ?\n🎌Demon Slayer🎌", answer: "gyomei himejima" },
  { question: "quelle est la technique spéciale de muzan ?\n🎌Demon Slayer🎌", answer: "biologiquement immortel" },
  { question: "comment s'appelle le sabre utilisé par les pourfendeurs ?\n🎌Demon Slayer🎌", answer: "katana nichirin" },
  { question: "quelle est la première mission de tanjiro ?\n🎌Demon Slayer🎌", answer: "sauver une fille enlevée la nuit" },
  { question: "qui entraîne tanjiro au début ?\n🎌Demon Slayer🎌", answer: "sakonji urokodaki" },
  { question: "quel démon tanjiro affronte à la sélection finale ?\n🎌Demon Slayer🎌", answer: "le démon aux bras multiples" },
  { question: "combien de jours dure la sélection finale ?\n🎌Demon Slayer🎌", answer: "sept jours" },
  { question: "quel personnage a une double personnalité ?\n🎌Demon Slayer🎌", answer: "zenitsu agatsuma" },
  { question: "quel pilier meurt dans le train de l’infini ?\n🎌Demon Slayer🎌", answer: "rengoku" },
  { question: "qui est la première lune supérieure vaincue ?\n🎌Demon Slayer🎌", answer: "gyutaro" },
  { question: "quelle est la spécialité d’inosuke ?\n🎌Demon Slayer🎌", answer: "combat instinctif" },
  { question: "quelle est la couleur du sabre de tanjiro ?\n🎌Demon Slayer🎌", answer: "noir" },
  { question: "quelle forme développe tanjiro après l’eau ?\n🎌Demon Slayer🎌", answer: "souffle du soleil" },
  { question: "quel est le style le plus ancien ?\n🎌Demon Slayer🎌", answer: "souffle du soleil" },
  { question: "qui est le rival de tanjiro parmi les démons ?\n🎌Demon Slayer🎌", answer: "akaza" },
  { question: "quelle est la position d'akaza chez les lunes ?\n🎌Demon Slayer🎌", answer: "troisième lune" },
  { question: "qui utilise le souffle du serpent ?\n🎌Demon Slayer🎌", answer: "obanaï iguro" },
  { question: "quelle est l’arme d’uzui ?\n🎌Demon Slayer🎌", answer: "deux grosses lames attachées" },
  { question: "quel est le lien entre muichiro et kokushibo ?\n🎌Demon Slayer🎌", answer: "descendants d’un même ancêtre" },
  { question: "qui est le plus jeune pilier ?\n🎌Demon Slayer🎌", answer: "muichiro" },
  { question: "quel pilier est aveugle ?\n🎌Demon Slayer🎌", answer: "gyomei" },
  { question: "qui est la meilleure amie de mitsuri ?\n🎌Demon Slayer🎌", answer: "obanaï" },
  { question: "quelle est la fin de muzan ?\n🎌Demon Slayer🎌", answer: "vaincu par tanjiro et les pourfendeurs" },
  { question: "tanjiro devient-il démon ?\n🎌Demon Slayer🎌", answer: "oui" },
  { question: "comment nezuko redevient humaine ?\n🎌Demon Slayer🎌", answer: "avec un remède spécial" },
  { question: "quel démon utilise une sœur et un frère ?\n🎌Demon Slayer🎌", answer: "gyutaro et daki" },
  { question: "qui est responsable de la mission du quartier des plaisirs ?\n🎌Demon Slayer🎌", answer: "uzui" },
  { question: "qui crée le médicament pour nezuko ?\n🎌Demon Slayer🎌", answer: "tamayo" },
  
  { question: "qui est le protagoniste principal de tokyo revengers ?\n🎌Tokyo Revengers🎌", answer: "takemichi hanagaki" },
  { question: "quel est le surnom de manjiro sano ?\n🎌Tokyo Revengers🎌", answer: "mikey" },
  { question: "comment s’appelle l’organisation que mikey dirige ?\n🎌Tokyo Revengers🎌", answer: "tokyo manji gang" },
  { question: "quelle est la capacité spéciale de takemichi ?\n🎌Tokyo Revengers🎌", answer: "voyage dans le temps" },
  { question: "quel personnage est surnommé 'draken' ?\n🎌Tokyo Revengers🎌", answer: "ken ryuguji" },
  { question: "qui est la petite amie de takemichi dans le passé ?\n🎌Tokyo Revengers🎌", answer: "hinata tachibana" },
  { question: "comment takemichi retourne-t-il dans le passé ?\n🎌Tokyo Revengers🎌", answer: "en serrant la main de naoto" },
  { question: "quel est le rôle de naoto tachibana ?\n🎌Tokyo Revengers🎌", answer: "inspecteur de police" },
  { question: "qui est le fondateur du tokyo manji gang ?\n🎌Tokyo Revengers🎌", answer: "mikey" },
  { question: "qui est le bras droit de mikey ?\n🎌Tokyo Revengers🎌", answer: "draken" },
  { question: "quelle est la couleur des cheveux de mikey ?\n🎌Tokyo Revengers🎌", answer: "blond" },
  { question: "qui est le premier antagoniste principal dans l’histoire ?\n🎌Tokyo Revengers🎌", answer: "kisaki" },
  { question: "qui est le chef de moebius ?\n🎌Tokyo Revengers🎌", answer: "shoji hanma" },
  { question: "quel est le but de takemichi dans le présent ?\n🎌Tokyo Revengers🎌", answer: "sauver hinata" },
  { question: "comment s'appelle le frère de hinata ?\n🎌Tokyo Revengers🎌", answer: "naoto" },
  { question: "quelle division est dirigée par takemichi dans toman ?\n🎌Tokyo Revengers🎌", answer: "1ère division" },
  { question: "quel est le vrai nom de baji ?\n🎌Tokyo Revengers🎌", answer: "keisuke baji" },
  { question: "comment s'appelle le meilleur ami de baji ?\n🎌Tokyo Revengers🎌", answer: "chifuyu matsuno" },
  { question: "qui est le fondateur de valhalla ?\n🎌Tokyo Revengers🎌", answer: "kisaki" },
  { question: "quel gang absorbe toman dans une timeline alternative ?\n🎌Tokyo Revengers🎌", answer: "black dragons" },
  { question: "quel est le rôle de hanma ?\n🎌Tokyo Revengers🎌", answer: "bras droit de kisaki" },
  { question: "qui tue baji ?\n🎌Tokyo Revengers🎌", answer: "kazutora" },
  { question: "quel est le vrai nom de mikey ?\n🎌Tokyo Revengers🎌", answer: "manjiro sano" },
  { question: "qui est le frère aîné de mikey ?\n🎌Tokyo Revengers🎌", answer: "shinichiro sano" },
  { question: "qui est le fondateur des black dragons ?\n🎌Tokyo Revengers🎌", answer: "shinichiro sano" },
  { question: "quelle génération des black dragons est la plus crainte ?\n🎌Tokyo Revengers🎌", answer: "10e" },
  { question: "qui dirige les black dragons à la 10e génération ?\n🎌Tokyo Revengers🎌", answer: "taiju shiba" },
  { question: "quelle est la spécialité de taiju shiba ?\n🎌Tokyo Revengers🎌", answer: "force brute" },
  { question: "qui est le frère de taiju ?\n🎌Tokyo Revengers🎌", answer: "hakkai shiba" },
  { question: "qui veut protéger hakkai des abus de taiju ?\n🎌Tokyo Revengers🎌", answer: "takemichi" },
  { question: "qui est la sœur de hakkai ?\n🎌Tokyo Revengers🎌", answer: "yuzuha shiba" },
  { question: "quelle est la principale faiblesse de takemichi ?\n🎌Tokyo Revengers🎌", answer: "il ne sait pas se battre" },
  { question: "comment mikey devient-il instable dans certaines timelines ?\n🎌Tokyo Revengers🎌", answer: "à cause de la perte de ses proches" },
  { question: "qui est le stratège derrière les manipulations de gang ?\n🎌Tokyo Revengers🎌", answer: "kisaki" },
  { question: "quelle est la conséquence de l’absence de draken dans le futur ?\n🎌Tokyo Revengers🎌", answer: "toman devient criminel" },
  { question: "qui aide takemichi à comprendre kisaki ?\n🎌Tokyo Revengers🎌", answer: "chifuyu" },
  { question: "que fait kisaki à la fin de l'arc tenjiku ?\n🎌Tokyo Revengers🎌", answer: "il tente de tuer takemichi" },
  { question: "qui est le chef de tenjiku ?\n🎌Tokyo Revengers🎌", answer: "izana kuro" },
  { question: "quel est le lien entre izana et mikey ?\n🎌Tokyo Revengers🎌", answer: "demi-frère adoptif" },
  { question: "qui est surnommé 'le roi du crime' ?\n🎌Tokyo Revengers🎌", answer: "izana" },
  { question: "quel est le nom du gang final dans la timeline la plus sombre ?\n🎌Tokyo Revengers🎌", answer: "bonten" },
  { question: "qui dirige bonten ?\n🎌Tokyo Revengers🎌", answer: "mikey" },
  { question: "qui est le bras droit de bonten ?\n🎌Tokyo Revengers🎌", answer: "sanzu" },
  { question: "comment s’appelle le chef d’unité de la 2e division de toman ?\n🎌Tokyo Revengers🎌", answer: "mitsuya" },
  { question: "quel est le rêve de takemichi à la fin ?\n🎌Tokyo Revengers🎌", answer: "vivre une vie paisible avec hinata" },
  { question: "quelle est la date récurrente du début du voyage temporel ?\n🎌Tokyo Revengers🎌", answer: "4 juillet" },
  { question: "quel est le point de départ de la série ?\n🎌Tokyo Revengers🎌", answer: "hinata meurt dans un accident" },
  { question: "qui est surnommé le 'chien fou de bonten' ?\n🎌Tokyo Revengers🎌", answer: "sanzu haruchiyo" },
  { question: "qui a trahi toman pendant l'arc valhalla ?\n🎌Tokyo Revengers🎌", answer: "kisaki" },
  { question: "quelle est la couleur de cheveux de draken ?\n🎌Tokyo Revengers🎌", answer: "blond" },
  { question: "quel est le gang rival de toman durant l’arc moebius ?\n🎌Tokyo Revengers🎌", answer: "moebius" },
  
  { question: "quel est le vrai nom de kaiju no. 8 ?\n🎌Kaiju No. 8🎌", answer: "kaffka hibino" },
  { question: "quel est le nom de l’amie d’enfance de kaffka ?\n🎌Kaiju No. 8🎌", answer: "mina ashira" },
  { question: "quelle est l’unité dirigée par mina ?\n🎌Kaiju No. 8🎌", answer: "3e division" },
  { question: "comment kaffka obtient-il ses pouvoirs ?\n🎌Kaiju No. 8🎌", answer: "il est infecté par un kaiju" },
  { question: "qui est le capitaine strict de la 3e division ?\n🎌Kaiju No. 8🎌", answer: "soshiro hoshina" },
  { question: "quelle organisation combat les kaijus ?\n🎌Kaiju No. 8🎌", answer: "force de défense" },
  { question: "quelle est la particularité de kaiju no. 8 ?\n🎌Kaiju No. 8🎌", answer: "il est humain et kaiju" },
  { question: "quel est le rêve de kaffka au début ?\n🎌Kaiju No. 8🎌", answer: "rejoindre la force de défense" },
  { question: "quel est le surnom du kaiju numéro 9 ?\n🎌Kaiju No. 8🎌", answer: "kaiju intelligent" },
  { question: "quel est le poste initial de kaffka ?\n🎌Kaiju No. 8🎌", answer: "nettoyeur de cadavres de kaiju" },
  { question: "qui est la recrue talentueuse aux lunettes ?\n🎌Kaiju No. 8🎌", answer: "reno ichikawa" },
  { question: "qui est la jeune recrue timide amie de reno ?\n🎌Kaiju No. 8🎌", answer: "ichikawa" },
  { question: "quelle est la puissance de déploiement de kaffka ?\n🎌Kaiju No. 8🎌", answer: "zéro pourcent" },
  { question: "quelle arme utilise hoshina ?\n🎌Kaiju No. 8🎌", answer: "sabres" },
  { question: "comment s’appelle la fille forte qui rejoint la 3e division ?\n🎌Kaiju No. 8🎌", answer: "kikoru shinomiya" },
  { question: "quel est le lien de kikoru avec la direction ?\n🎌Kaiju No. 8🎌", answer: "fille du directeur général" },
  { question: "quel est le grade de mina ashira ?\n🎌Kaiju No. 8🎌", answer: "capitaine" },
  { question: "comment kaffka cache-t-il son identité ?\n🎌Kaiju No. 8🎌", answer: "il se transforme hors de vue" },
  { question: "quel est le nom du kaiju qui parle et planifie ?\n🎌Kaiju No. 8🎌", answer: "kaiju no. 9" },
  { question: "quelle unité utilise la technologie la plus avancée ?\n🎌Kaiju No. 8🎌", answer: "1ère division" },
  { question: "comment s'appelle l'armure utilisée contre les kaiju ?\n🎌Kaiju No. 8🎌", answer: "système de combinaison" },
  { question: "quelle est la première mission de kaffka après sa réussite ?\n🎌Kaiju No. 8🎌", answer: "attaque d’un kaiju classe fort" },
  { question: "quelle est la particularité du kaiju no. 9 ?\n🎌Kaiju No. 8🎌", answer: "il évolue rapidement" },
  { question: "qui est le chef suprême de la défense ?\n🎌Kaiju No. 8🎌", answer: "isao shinomiya" },
  { question: "quelle division est réputée pour ses missions périlleuses ?\n🎌Kaiju No. 8🎌", answer: "3e division" },
  { question: "qui est surnommé 'le chasseur de kaiju' ?\n🎌Kaiju No. 8🎌", answer: "hoshina" },
  { question: "comment kaffka réagit face à la peur en mission ?\n🎌Kaiju No. 8🎌", answer: "il agit instinctivement" },
  { question: "qu'est-ce qui rend kaiju no. 8 différent des autres ?\n🎌Kaiju No. 8🎌", answer: "il garde sa conscience humaine" },
  { question: "quel est le style de combat de kikoru ?\n🎌Kaiju No. 8🎌", answer: "force brute" },
  { question: "quelle est la réponse de la direction après l’identification de kaiju no. 8 ?\n🎌Kaiju No. 8🎌", answer: "exécution immédiate" },
  { question: "quelle est la conséquence pour kaffka après sa transformation révélée ?\n🎌Kaiju No. 8🎌", answer: "il est placé en détention" },
  { question: "quelle est la réaction de mina après la révélation de kaffka ?\n🎌Kaiju No. 8🎌", answer: "elle reste silencieuse" },
  { question: "qui veut surpasser kaffka en puissance ?\n🎌Kaiju No. 8🎌", answer: "reno" },
  { question: "quelle ville est attaquée dans les premiers chapitres ?\n🎌Kaiju No. 8🎌", answer: "yokohama" },
  { question: "quelle est la mission principale de la force de défense ?\n🎌Kaiju No. 8🎌", answer: "éliminer les kaiju" },
  { question: "quel est le nom de code officiel de kaffka ?\n🎌Kaiju No. 8🎌", answer: "kaiju no. 8" },
  { question: "quelle est l’arme la plus efficace contre les kaijus ?\n🎌Kaiju No. 8🎌", answer: "combinaison de puissance" },
  { question: "comment les recrues améliorent-elles leur score ?\n🎌Kaiju No. 8🎌", answer: "en synchronisant leur combinaison" },
  { question: "quel personnage veut venger ses camarades ?\n🎌Kaiju No. 8🎌", answer: "kikoru" },
  { question: "quel est le rôle des agents d’élite ?\n🎌Kaiju No. 8🎌", answer: "éliminer les kaiju classe supérieur" },
  { question: "qui interroge kaffka après sa capture ?\n🎌Kaiju No. 8🎌", answer: "isao" },
  { question: "que représente le chiffre d’un kaiju ?\n🎌Kaiju No. 8🎌", answer: "son classement spécial" },
  { question: "quelle est la principale faiblesse de kaffka ?\n🎌Kaiju No. 8🎌", answer: "il perd parfois le contrôle" },
  { question: "comment kaffka protège reno pendant une attaque ?\n🎌Kaiju No. 8🎌", answer: "en se transformant en kaiju" },
  { question: "quel est l’objectif de kaiju no. 9 ?\n🎌Kaiju No. 8🎌", answer: "créer une armée de kaiju intelligents" },
  { question: "quel est le surnom donné à kaffka par les médias ?\n🎌Kaiju No. 8🎌", answer: "le traître humain" },
  { question: "quel kaiju possède des pouvoirs de duplication ?\n🎌Kaiju No. 8🎌", answer: "kaiju no. 9" },
  { question: "qui aide kaffka à reprendre le contrôle lors de sa rage ?\n🎌Kaiju No. 8🎌", answer: "reno" },
  { question: "quel est l’élément central du conflit dans kaiju no. 8 ?\n🎌Kaiju No. 8🎌", answer: "coexistence impossible humain/kaiju" },
  { question: "comment kaffka est jugé utile malgré sa transformation ?\n🎌Kaiju No. 8🎌", answer: "grâce à sa conscience humaine" },
  { question: "qui commence à douter des intentions de la hiérarchie ?\n🎌Kaiju No. 8🎌", answer: "hoshina" },
  
  { question: "quel est le prénom du protagoniste principal ?\n🎌Chainsaw Man🎌", answer: "denji" },
  { question: "quel démon est fusionné avec denji ?\n🎌Chainsaw Man🎌", answer: "pochita" },
  { question: "quel est le nom de l'organisation de chasse aux démons ?\n🎌Chainsaw Man🎌", answer: "sécurité publique" },
  { question: "comment s'appelle la fille aux cheveux roses qui aime les armes ?\n🎌Chainsaw Man🎌", answer: "power" },
  { question: "quel démon contrôle la peur des armes à feu ?\n🎌Chainsaw Man🎌", answer: "gun devil" },
  { question: "quel est le nom du supérieur de denji dans la sécurité publique ?\n🎌Chainsaw Man🎌", answer: "makima" },
  { question: "comment s'appelle le partenaire de denji, calme et sérieux ?\n🎌Chainsaw Man🎌", answer: "aki" },
  { question: "quel est le démon avec lequel aki a un contrat pour voir sa mort ?\n🎌Chainsaw Man🎌", answer: "futur devil" },
  { question: "quel est le démon avec lequel aki a un contrat au début ?\n🎌Chainsaw Man🎌", answer: "fox devil" },
  { question: "quel personnage est obsédé par le fait de venger sa famille tuée par le gun devil ?\n🎌Chainsaw Man🎌", answer: "aki" },
  { question: "quel est le nom du katana man ?\n🎌Chainsaw Man🎌", answer: "sawatari" },
  { question: "quel démon power utilise-t-elle ?\n🎌Chainsaw Man🎌", answer: "blood devil" },
  { question: "quelle est la boisson préférée de makima ?\n🎌Chainsaw Man🎌", answer: "coca" },
  { question: "comment s'appelle l’unité spéciale de makima ?\n🎌Chainsaw Man🎌", answer: "division 4" },
  { question: "quel est le surnom de makima dans l’acte 2 ?\n🎌Chainsaw Man🎌", answer: "control devil" },
  { question: "quelle partie du corps de denji contient une corde à tirer ?\n🎌Chainsaw Man🎌", answer: "poitrine" },
  { question: "que veut denji plus que tout au début du manga ?\n🎌Chainsaw Man🎌", answer: "une vie normale" },
  { question: "quel démon représente la peur du futur ?\n🎌Chainsaw Man🎌", answer: "futur devil" },
  { question: "quelle est la couleur des cheveux de makima ?\n🎌Chainsaw Man🎌", answer: "roux" },
  { question: "quelle est la technique de signature de power ?\n🎌Chainsaw Man🎌", answer: "manipulation sanguine" },
  { question: "comment s'appelle le diable qui ressuscite power ?\n🎌Chainsaw Man🎌", answer: "pochita" },
  { question: "quel démon représente la peur du contrôle ?\n🎌Chainsaw Man🎌", answer: "makima" },
  { question: "quel démon dévore makima à la fin ?\n🎌Chainsaw Man🎌", answer: "denji" },
  { question: "comment s'appelle la petite sœur de reze ?\n🎌Chainsaw Man🎌", answer: "elle n'en a pas" },
  { question: "quel est le démon associé à reze ?\n🎌Chainsaw Man🎌", answer: "bomb devil" },
  { question: "qui est la femme qui manipule des serpents ?\n🎌Chainsaw Man🎌", answer: "sawatari" },
  { question: "quelle est la technique utilisée par le gun devil pour tuer en masse ?\n🎌Chainsaw Man🎌", answer: "fragments de balle" },
  { question: "qui est le démon de la peur des ténèbres ?\n🎌Chainsaw Man🎌", answer: "darkness devil" },
  { question: "dans quel pays le gun devil a-t-il causé le plus de morts ?\n🎌Chainsaw Man🎌", answer: "etats-unis" },
  { question: "combien de secondes le gun devil a-t-il mis pour tuer 1.2 million de personnes ?\n🎌Chainsaw Man🎌", answer: "5" },
  { question: "quelle partie du corps de denji devient une tronçonneuse ?\n🎌Chainsaw Man🎌", answer: "tête" },
  { question: "quelle est la profession de kishibe ?\n🎌Chainsaw Man🎌", answer: "chasseur de démons" },
  { question: "quelle est la faiblesse principale de makima ?\n🎌Chainsaw Man🎌", answer: "pochita" },
  { question: "qu’est-ce que pochita voulait avant de disparaître ?\n🎌Chainsaw Man🎌", answer: "voir le rêve de denji" },
  { question: "quelle est l'odeur que seule cha hae-in peut sentir sur jinwoo ?\n🎌Chainsaw Man🎌", answer: "ça ne s’applique pas ici" },
  { question: "comment reze meurt-elle ?\n🎌Chainsaw Man🎌", answer: "tuée par makima" },
  { question: "qui adopte l'identité de chainsaw man dans l'acte 2 ?\n🎌Chainsaw Man🎌", answer: "denji" },
  { question: "qui est nayuta ?\n🎌Chainsaw Man🎌", answer: "réincarnation de makima" },
  { question: "comment s'appelle la présidente de l'école dans act 2 ?\n🎌Chainsaw Man🎌", answer: "yoshida" },
  { question: "quelle est la nourriture préférée de denji ?\n🎌Chainsaw Man🎌", answer: "pain avec confiture" },
  { question: "quelle est l'identité du démon de la guerre ?\n🎌Chainsaw Man🎌", answer: "asa mitaka" },
  { question: "quelle est la relation entre power et meowy ?\n🎌Chainsaw Man🎌", answer: "chat de compagnie" },
  { question: "comment power meurt-elle ?\n🎌Chainsaw Man🎌", answer: "tuée par makima" },
  { question: "quelle est la capacité spéciale du blood devil ?\n🎌Chainsaw Man🎌", answer: "manipulation du sang" },
  { question: "qui remplace power dans l’acte 2 ?\n🎌Chainsaw Man🎌", answer: "nayuta" },
  { question: "qui dirige la division 4 après la mort de makima ?\n🎌Chainsaw Man🎌", answer: "kishibe" },
  { question: "quelle est la première chose que denji achète avec son salaire ?\n🎌Chainsaw Man🎌", answer: "nourriture" },
  { question: "quelle partie du corps de power devient une arme ?\n🎌Chainsaw Man🎌", answer: "sang" },
  { question: "qui sauve denji dans l’acte 2 des démons de l’école ?\n🎌Chainsaw Man🎌", answer: "asa mitaka" },
  { question: "comment pochita parle-t-il à denji ?\n🎌Chainsaw Man🎌", answer: "dans ses rêves" },
  
  { question: "quel est le nom du protagoniste principal de solo leveling ?\n🎌Solo Leveling🎌", answer: "sung jinwoo" },
  { question: "quelle classe avait sung jinwoo au début de l'histoire ?\n🎌Solo Leveling🎌", answer: "e" },
  { question: "quel est le surnom donné à sung jinwoo par les autres chasseurs ?\n🎌Solo Leveling🎌", answer: "monarque de l'ombre" },
  { question: "quelle est la première ombre que jinwoo a ressuscitée ?\n🎌Solo Leveling🎌", answer: "iron" },
  { question: "quel est le nom de l'ombre de l'ours géant ?\n🎌Solo Leveling🎌", answer: "tank" },
  { question: "comment s'appelle l'ombre du chevalier de rang a que jinwoo a battu ?\n🎌Solo Leveling🎌", answer: "igen" },
  { question: "quelle organisation classe les donjons et chasseurs ?\n🎌Solo Leveling🎌", answer: "association des chasseurs" },
  { question: "quel est le nom du portail le plus dangereux ?\n🎌Solo Leveling🎌", answer: "donjon de rang s" },
  { question: "quel est le nom du système qui donne des quêtes à jinwoo ?\n🎌Solo Leveling🎌", answer: "système du joueur" },
  { question: "qui est la sœur de sung jinwoo ?\n🎌Solo Leveling🎌", answer: "sung jinah" },
  { question: "comment s'appelle le médecin qui aide la mère de jinwoo ?\n🎌Solo Leveling🎌", answer: "docteur kim" },
  { question: "qui est le président de l'association des chasseurs de corée ?\n🎌Solo Leveling🎌", answer: "go gunhee" },
  { question: "quelle est la profession du père de jinwoo ?\n🎌Solo Leveling🎌", answer: "chasseur" },
  { question: "comment s'appelle le leader des monarques ?\n🎌Solo Leveling🎌", answer: "ashborn" },
  { question: "quel monarque a affronté jinwoo à tokyo ?\n🎌Solo Leveling🎌", answer: "baran" },
  { question: "qui est le roi des géants ?\n🎌Solo Leveling🎌", answer: "rakan" },
  { question: "quelle est la capitale des géants ?\n🎌Solo Leveling🎌", answer: "ethel" },
  { question: "quelle est l’ombre la plus puissante de jinwoo ?\n🎌Solo Leveling🎌", answer: "beru" },
  { question: "qui est l'ancien roi des fourmis ?\n🎌Solo Leveling🎌", answer: "fourmi de jeju" },
  { question: "dans quel pays se déroule le raid de jeju ?\n🎌Solo Leveling🎌", answer: "corée" },
  { question: "qui est l'ancien commandant des ombres avant jinwoo ?\n🎌Solo Leveling🎌", answer: "ashborn" },
  { question: "combien de soldats d’ombre jinwoo peut-il invoquer à la fin ?\n🎌Solo Leveling🎌", answer: "plus de 100 000" },
  { question: "quelle guilde recrute le plus de chasseurs s ?\n🎌Solo Leveling🎌", answer: "guilde des chasseurs" },
  { question: "qui est cha hae-in ?\n🎌Solo Leveling🎌", answer: "chasseuse de rang s" },
  { question: "quel est le pouvoir spécial de cha hae-in ?\n🎌Solo Leveling🎌", answer: "odorat spirituel" },
  { question: "quelle arme utilise principalement jinwoo ?\n🎌Solo Leveling🎌", answer: "dague" },
  { question: "quelle est la classe cachée de jinwoo ?\n🎌Solo Leveling🎌", answer: "nécromancien d'ombre" },
  { question: "que se passe-t-il si jinwoo meurt dans le système ?\n🎌Solo Leveling🎌", answer: "fin du jeu" },
  { question: "quelle est la mission la plus redoutée donnée par le système ?\n🎌Solo Leveling🎌", answer: "quête de punition" },
  { question: "qui a failli tuer go gunhee ?\n🎌Solo Leveling🎌", answer: "monarque des glaces" },
  { question: "comment jinwoo devient-il plus fort ?\n🎌Solo Leveling🎌", answer: "en s'entraînant dans le système" },
  { question: "quel est le rôle de l’île de jeju ?\n🎌Solo Leveling🎌", answer: "nid des fourmis magiques" },
  { question: "quel personnage est surnommé 'le tank humain' ?\n🎌Solo Leveling🎌", answer: "baek yoonho" },
  { question: "quelle est la guilde dirigée par baek yoonho ?\n🎌Solo Leveling🎌", answer: "guilde des chasseurs blancs" },
  { question: "quelle guilde refuse de participer à jeju au début ?\n🎌Solo Leveling🎌", answer: "guilde des tigres" },
  { question: "que devient le roi des dragons face à jinwoo ?\n🎌Solo Leveling🎌", answer: "vaincu" },
  { question: "quel est le but des monarques ?\n🎌Solo Leveling🎌", answer: "détruire les humains" },
  { question: "quel rôle ashborn confie-t-il à jinwoo ?\n🎌Solo Leveling🎌", answer: "héritier" },
  { question: "quelle est la dernière mission de jinwoo ?\n🎌Solo Leveling🎌", answer: "sauver le monde" },
  { question: "comment jinwoo revient-il après la guerre finale ?\n🎌Solo Leveling🎌", answer: "par le temps" },
  { question: "qui est le plus jeune chasseur s de corée ?\n🎌Solo Leveling🎌", answer: "jinwoo" },
  { question: "dans quelle tour s’est réveillé le système ?\n🎌Solo Leveling🎌", answer: "donjon double" },
  { question: "quelle est la ville principale de l’histoire ?\n🎌Solo Leveling🎌", answer: "séoul" },
  { question: "qui contrôle le portail au début ?\n🎌Solo Leveling🎌", answer: "personne" },
  { question: "quelle est l’ultime capacité de jinwoo ?\n🎌Solo Leveling🎌", answer: "domination de l’ombre" },
  { question: "comment s'appelle le roi des bêtes ?\n🎌Solo Leveling🎌", answer: "monarque des bêtes" },
  { question: "quelle est la technique spéciale de beru ?\n🎌Solo Leveling🎌", answer: "hurlement royal" },
  { question: "comment jinwoo communique avec ses ombres ?\n🎌Solo Leveling🎌", answer: "télépathie" },
  { question: "quelle est la récompense après avoir battu un donjon s ?\n🎌Solo Leveling🎌", answer: "clef spéciale ou artefact" },
  { question: "quel est le rang maximum d’un chasseur ?\n🎌Solo Leveling🎌", answer: "s" },
  
  { question: "quel est le nom complet du capitaine des chapeaux de paille ?\n🎌One Piece🎌", answer: "monkey d. luffy" },
  { question: "quel est le nom du sabreur de l'équipage de luffy ?\n🎌One Piece🎌", answer: "roronoa zoro" },
  { question: "quelle est la prime actuelle de monkey d. luffy après wano ?\n🎌One Piece🎌", answer: "3 milliards" },
  { question: "qui est le père de luffy ?\n🎌One Piece🎌", answer: "monkey d. dragon" },
  { question: "quelle est la capacité du fruit du démon de luffy ?\n🎌One Piece🎌", answer: "caoutchouc" },
  { question: "quel est le vrai nom du fruit de luffy après révélation à wano ?\n🎌One Piece🎌", answer: "hito hito no mi modèle nika" },
  { question: "qui est le cuisinier de l'équipage ?\n🎌One Piece🎌", answer: "sanji" },
  { question: "qui a sauvé luffy du roi des mers quand il était enfant ?\n🎌One Piece🎌", answer: "shanks" },
  { question: "quelle est la seule femme dans les mugiwaras à savoir lire les ponéglyphes ?\n🎌One Piece🎌", answer: "nico robin" },
  { question: "qui est le médecin de l’équipage de luffy ?\n🎌One Piece🎌", answer: "tony tony chopper" },
  { question: "comment s'appelle le charpentier de sunny go ?\n🎌One Piece🎌", answer: "franky" },
  { question: "quelle est la position de brook dans l’équipage ?\n🎌One Piece🎌", answer: "musicien" },
  { question: "qui est l'inventrice et navigatrice dans l'équipage ?\n🎌One Piece🎌", answer: "nami" },
  { question: "qui est l'homme-poisson membre de l’équipage ?\n🎌One Piece🎌", answer: "jinbei" },
  { question: "quel empereur luffy a-t-il affronté à whole cake island ?\n🎌One Piece🎌", answer: "big mom" },
  { question: "qui a vaincu kaido à onigashima ?\n🎌One Piece🎌", answer: "luffy" },
  { question: "comment s'appelle le frère adoptif de luffy mort à marineford ?\n🎌One Piece🎌", answer: "portgas d. ace" },
  { question: "quelle est la dernière île du nouveau monde ?\n🎌One Piece🎌", answer: "laugh tale" },
  { question: "qui est le rival principal de luffy au début du manga ?\n🎌One Piece🎌", answer: "koby" },
  { question: "qui est le directeur d’impel down ?\n🎌One Piece🎌", answer: "magellan" },
  { question: "comment s’appelle l'ancien roi pirate ?\n🎌One Piece🎌", answer: "gol d. roger" },
  { question: "quel est le rêve de zoro ?\n🎌One Piece🎌", answer: "devenir le meilleur épéiste" },
  { question: "quel est le nom du plus grand épéiste du monde ?\n🎌One Piece🎌", answer: "dracule mihawk" },
  { question: "qui a tué ace ?\n🎌One Piece🎌", answer: "akainu" },
  { question: "qui a volé le plan du pluton à water 7 ?\n🎌One Piece🎌", answer: "cp9" },
  { question: "comment s’appelle le bateau avant le sunny ?\n🎌One Piece🎌", answer: "merry go" },
  { question: "qui a brûlé le drapeau du gouvernement mondial à enies lobby ?\n🎌One Piece🎌", answer: "luffy" },
  { question: "comment s'appelle l'île céleste où luffy est allé ?\n🎌One Piece🎌", answer: "skypiea" },
  { question: "qui était le dieu de skypiea ?\n🎌One Piece🎌", answer: "ener" },
  { question: "quel est le nom de l'amiral à la glace ?\n🎌One Piece🎌", answer: "aokiji" },
  { question: "qui a formé luffy au haki ?\n🎌One Piece🎌", answer: "silvers rayleigh" },
  { question: "quelle est la technique ultime de sanji ?\n🎌One Piece🎌", answer: "diable jambe" },
  { question: "quel est le nom du scientifique fou de punk hazard ?\n🎌One Piece🎌", answer: "caesar clown" },
  { question: "qui est le créateur des pacifistas ?\n🎌One Piece🎌", answer: "vega punk" },
  { question: "comment s’appelle l'île de law ?\n🎌One Piece🎌", answer: "flevance" },
  { question: "qui est l'ancien capitaine de law ?\n🎌One Piece🎌", answer: "corazon" },
  { question: "quel personnage a mangé le fruit de l’ombre ?\n🎌One Piece🎌", answer: "gecko moria" },
  { question: "quelle est la capacité de luffy en gear 5 ?\n🎌One Piece🎌", answer: "liberté absolue" },
  { question: "qui a formé sanji au combat durant l'ellipse ?\n🎌One Piece🎌", answer: "ivankov" },
  { question: "quel est le nom du roi de dressrosa ?\n🎌One Piece🎌", answer: "donquixote doflamingo" },
  { question: "qui est le père de usopp ?\n🎌One Piece🎌", answer: "yasopp" },
  { question: "qui a tué oden kozuki ?\n🎌One Piece🎌", answer: "kaido" },
  { question: "comment s'appelle la femme d’oden ?\n🎌One Piece🎌", answer: "toki" },
  { question: "quel fruit a mangé kaido ?\n🎌One Piece🎌", answer: "uou uou no mi" },
  { question: "quel personnage est surnommé le chirurgien de la mort ?\n🎌One Piece🎌", answer: "trafalgar law" },
  { question: "qui est l’enfant de big mom et kaido dans les théories ?\n🎌One Piece🎌", answer: "yamato" },
  { question: "qui est le bras droit de shanks ?\n🎌One Piece🎌", answer: "benn beckman" },
  { question: "qui est le capitaine des révolutionnaires ?\n🎌One Piece🎌", answer: "dragon" },
  { question: "que signifie le d dans les noms comme gol d roger ?\n🎌One Piece🎌", answer: "volonté du d" },
  { question: "quelle est la récompense actuelle de zoro après wano ?\n🎌One Piece🎌", answer: "1 milliard 111 millions" },
  
  { question: "comment s'appelle le père de gon ?\n🎌Hunter x Hunter🎌", answer: "ging freecss" },
  { question: "quel est le nom complet de gon ?\n🎌Hunter x Hunter🎌", answer: "gon freecss" },
  { question: "qui est l'ami aux cheveux blancs de gon ?\n🎌Hunter x Hunter🎌", answer: "killua zoldyck" },
  { question: "quel est le nom du clan de kurapika ?\n🎌Hunter x Hunter🎌", answer: "kurta" },
  { question: "quelle est la spécialité de nen de leorio ?\n🎌Hunter x Hunter🎌", answer: "émission" },
  { question: "quelle est la principale capacité de nen de gon ?\n🎌Hunter x Hunter🎌", answer: "renforcement" },
  { question: "quel est le nom du frère de killua qui adore les poupées ?\n🎌Hunter x Hunter🎌", answer: "alluka" },
  { question: "quelle organisation est responsable du massacre du clan de kurapika ?\n🎌Hunter x Hunter🎌", answer: "brigade fantôme" },
  { question: "quel est le surnom de hisoka ?\n🎌Hunter x Hunter🎌", answer: "le magicien" },
  { question: "quelle est la capacité de nen de hisoka ?\n🎌Hunter x Hunter🎌", answer: "bungee gum" },
  { question: "comment s'appelle le chef de la brigade fantôme ?\n🎌Hunter x Hunter🎌", answer: "chrollo lucilfer" },
  { question: "quel examen doit passer gon au début ?\n🎌Hunter x Hunter🎌", answer: "examen hunter" },
  { question: "comment s'appelle le majordome de la famille zoldyck ?\n🎌Hunter x Hunter🎌", answer: "gotoh" },
  { question: "quel est le plus jeune frère de killua ?\n🎌Hunter x Hunter🎌", answer: "alluka" },
  { question: "qui est l'ancien roi des fourmis chimères ?\n🎌Hunter x Hunter🎌", answer: "meruem" },
  { question: "quel est le nom de la jeune fille humaine proche de meruem ?\n🎌Hunter x Hunter🎌", answer: "komugi" },
  { question: "quelle est la capacité de nen de knuckle ?\n🎌Hunter x Hunter🎌", answer: "potclean" },
  { question: "quel zoldyck utilise des aiguilles pour se battre ?\n🎌Hunter x Hunter🎌", answer: "illumi" },
  { question: "quel personnage est médecin et membre des zodiaques ?\n🎌Hunter x Hunter🎌", answer: "leorio" },
  { question: "quelle technique de nen permet de cacher sa présence ?\n🎌Hunter x Hunter🎌", answer: "zetsu" },
  { question: "quelle est la spécialité de nen de kurapika avec ses yeux écarlates ?\n🎌Hunter x Hunter🎌", answer: "spécialisation" },
  { question: "quelle est la capacité de nen de shoot ?\n🎌Hunter x Hunter🎌", answer: "hand storage" },
  { question: "qui est la présidente de l’association hunter avant netero ?\n🎌Hunter x Hunter🎌", answer: "il n’y en a pas" },
  { question: "quelle est la capacité ultime de kurapika ?\n🎌Hunter x Hunter🎌", answer: "chaînes de jugement" },
  { question: "combien de membres compte la brigade fantôme ?\n🎌Hunter x Hunter🎌", answer: "13" },
  { question: "qui tue le roi meruem ?\n🎌Hunter x Hunter🎌", answer: "netero" },
  { question: "quelle est la forme de nen utilisée pour renforcer le corps ?\n🎌Hunter x Hunter🎌", answer: "renforcement" },
  { question: "comment s'appelle le jeu vidéo créé par ging ?\n🎌Hunter x Hunter🎌", answer: "greed island" },
  { question: "quel personnage utilise une arme en forme de pipe ?\n🎌Hunter x Hunter🎌", answer: "morau" },
  { question: "qui est palm ?\n🎌Hunter x Hunter🎌", answer: "élève de knov" },
  { question: "quelle est la capacité de nen de killua ?\n🎌Hunter x Hunter🎌", answer: "électricité" },
  { question: "quelle est la spécialité de nen de knov ?\n🎌Hunter x Hunter🎌", answer: "matérialisation" },
  { question: "quel zodiaque a une tête de chien ?\n🎌Hunter x Hunter🎌", answer: "cheadle" },
  { question: "comment killua se libère de l'influence d’illumi ?\n🎌Hunter x Hunter🎌", answer: "il retire l’aiguille" },
  { question: "quel est le nom du père de killua ?\n🎌Hunter x Hunter🎌", answer: "silva zoldyck" },
  { question: "qui affronte meruem en dernier ?\n🎌Hunter x Hunter🎌", answer: "netero" },
  { question: "quel zoldyck est expert en poison ?\n🎌Hunter x Hunter🎌", answer: "kikyo" },
  { question: "comment meurt kite ?\n🎌Hunter x Hunter🎌", answer: "tué par neferpitou" },
  { question: "comment s'appelle le conseiller militaire de meruem ?\n🎌Hunter x Hunter🎌", answer: "shaiapouf" },
  { question: "quel membre de la brigade utilise une musique comme arme ?\n🎌Hunter x Hunter🎌", answer: "melody" },
  { question: "quelle est la classe de licence la plus rare ?\n🎌Hunter x Hunter🎌", answer: "hunter triple étoile" },
  { question: "quel est le frère silencieux et puissant de killua ?\n🎌Hunter x Hunter🎌", answer: "milluki" },
  { question: "quel est le rôle de pokkle ?\n🎌Hunter x Hunter🎌", answer: "hunter de bêtes" },
  { question: "comment s'appelle le test de la première épreuve hunter ?\n🎌Hunter x Hunter🎌", answer: "course d'endurance" },
  { question: "quel est l'ennemi principal dans l’arc greed island ?\n🎌Hunter x Hunter🎌", answer: "bomber" },
  { question: "comment s'appelle le grand père de killua ?\n🎌Hunter x Hunter🎌", answer: "zia l zoldyck" },
  { question: "comment s'appelle le majordome à lunettes de la famille zoldyck ?\n🎌Hunter x Hunter🎌", answer: "gotoh" },
  { question: "quelle est la capacité de nen de gon dans greed island ?\n🎌Hunter x Hunter🎌", answer: "pierre papier ciseaux" },
  { question: "qui est la sœur de alluka ?\n🎌Hunter x Hunter🎌", answer: "nanika" },
  { question: "quel est le nom complet de bisky ?\n🎌Hunter x Hunter🎌", answer: "biscuit krueger" },
    
  { question: "quel est le nom complet d'edward ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "edward elric" },
  { question: "qui est le frère cadet d'edward ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "alphonse elric" },
  { question: "quel membre manque à edward ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "jambe droite" },
  { question: "quel est le surnom d'edward en tant qu'alchimiste d'état ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "fullmetal" },
  { question: "comment s'appelle la meilleure amie d'edward ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "winry rockbell" },
  { question: "comment s'appelle le chien de la famille hughes ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "black hayate" },
  { question: "quel est le nom du général avec une moustache proéminente ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "alex louis armstrong" },
  { question: "qui est le chef des homonculus ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "father" },
  { question: "quel est le nom de l’homonculus qui représente l’envie ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "envy" },
  { question: "quel est le nom de l'homonculus le plus rapide ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "wrath" },
  { question: "quelle partie du corps alphonse a-t-il perdue ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "tout son corps" },
  { question: "qui est roy mustang ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "flame alchemist" },
  { question: "quel est le but des elric ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "retrouver leurs corps" },
  { question: "quelle est la loi principale de l’alchimie ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "échange équivalent" },
  { question: "qui est l'assistante de roy mustang ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "riza hawkeye" },
  { question: "comment s'appelle le père d’edward et alphonse ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "van hohenheim" },
  { question: "comment s'appelle la pierre utilisée pour contourner l’échange équivalent ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "pierre philosophale" },
  { question: "quel homonculus peut changer d’apparence ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "envy" },
  { question: "quelle est la faiblesse de mustang sous la pluie ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "il ne peut pas faire de feu" },
  { question: "qui tue maes hughes ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "envy" },
  { question: "comment s'appelle la fille du général armstrong ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "olivier mira armstrong" },
  { question: "qui est le roi de xerxes ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "inconnu" },
  { question: "quel homonculus est le plus intelligent ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "pride" },
  { question: "comment s'appelle le petit garçon qui contient pride ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "selim bradley" },
  { question: "quel est le nom de l’homonculus paresseux ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "sloth" },
  { question: "quelle est l’arme principale de scar ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "son bras droit" },
  { question: "qui a enseigné l'alchimie aux elric ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "izumi curtis" },
  { question: "que signifie le mot homonculus ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "petit homme" },
  { question: "dans quel pays se passe l'histoire ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "amestris" },
  { question: "comment meurt gluttony ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "absorbé par pride" },
  { question: "qui tue lust ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "roy mustang" },
  { question: "qui est considéré comme un être immortel ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "hohenheim" },
  { question: "quelle est la capitale d'amestris ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "central city" },
  { question: "quel est le métier de winry ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "mécanicienne" },
  { question: "comment s’appelle l’épisode final ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "la vérité" },
  { question: "quel est le symbole sur le manteau d'edward ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "croix ailée avec serpent" },
  { question: "quelles sont les deux formes de transmutation interdites ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "or et humain" },
  { question: "comment s'appelle l'homonculus féminin ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "lust" },
  { question: "qu'utilise roy mustang pour créer du feu ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "gants enflammés" },
  { question: "quel est le rang d’edward dans l’armée ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "alchimiste d'état" },
  { question: "quelle est la relation entre edward et winry ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "amitié puis amour" },
  { question: "qui enseigne la médecine à scar ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "sa famille" },
  { question: "qui aide edward à se battre dans le monde souterrain ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "greed" },
  { question: "quelle est la nature de greed ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "homonculus" },
  { question: "quel est le surnom du docteur marcoh ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "alchimiste cristal" },
  { question: "quelle est l’identité de wrath ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "king bradley" },
  { question: "quelle est la relation entre pride et father ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "fils" },
  { question: "quelle est l’arme favorite d’olivier ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "épée" },
  { question: "comment hohenheim devient immortel ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "il absorbe des âmes" },
  { question: "que symbolise la porte de la vérité ?\n🎌Fullmetal Alchemist Brotherhood🎌", answer: "la connaissance absolue" },
      [
  { question: "quel est le vrai nom de saitama ?\n🎌One Punch Man🎌", answer: "saitama" },
  { question: "quel est le héros de classe s qui utilise un katana ?\n🎌One Punch Man🎌", answer: "atomic samurai" },
  { question: "quel est le rang de genos dans la classe s au début ?\n🎌One Punch Man🎌", answer: "14" },
  { question: "comment s'appelle le frère géant tué par son propre frère ?\n🎌One Punch Man🎌", answer: "marugori" },
  { question: "qui est considéré comme le héros le plus fort après blast ?\n🎌One Punch Man🎌", answer: "tatsumaki" },
  { question: "quel est le rang de saitama dans la classe c à ses débuts ?\n🎌One Punch Man🎌", answer: "388" },
  { question: "quel est le pouvoir de king selon les autres ?\n🎌One Punch Man🎌", answer: "inconnu" },
  { question: "quel est le secret de king ?\n🎌One Punch Man🎌", answer: "il n'a aucun pouvoir" },
  { question: "qui est l'apprenti de bang ?\n🎌One Punch Man🎌", answer: "garou" },
  { question: "quel est le niveau de menace de boros ?\n🎌One Punch Man🎌", answer: "dragon" },
  { question: "quelle est la technique de boros ?\n🎌One Punch Man🎌", answer: "canon de collision" },
  { question: "comment s'appelle l’organisation criminelle souterraine ?\n🎌One Punch Man🎌", answer: "maison de l'évolution" },
  { question: "qui est le créateur de genos ?\n🎌One Punch Man🎌", answer: "kuseno" },
  { question: "quel est le héros qui ressemble à un prisonnier ?\n🎌One Punch Man🎌", answer: "pur pori prisoner" },
  { question: "quelle est la spécialité de tatsumaki ?\n🎌One Punch Man🎌", answer: "télékinésie" },
  { question: "qui est la sœur de tatsumaki ?\n🎌One Punch Man🎌", answer: "fubuki" },
  { question: "quel est le chef des héros de classe s ?\n🎌One Punch Man🎌", answer: "blast" },
  { question: "quel héros porte un masque et aime les sucreries ?\n🎌One Punch Man🎌", answer: "sweet mask" },
  { question: "quel est le nom de l’association ennemie des héros ?\n🎌One Punch Man🎌", answer: "association des monstres" },
  { question: "qui est le roi des monstres ?\n🎌One Punch Man🎌", answer: "orochi" },
  { question: "quel est le rang maximum dans la classe a ?\n🎌One Punch Man🎌", answer: "1" },
  { question: "qui est le plus fort psychiquement ?\n🎌One Punch Man🎌", answer: "tatsumaki" },
  { question: "comment s'appelle le scientifique fou créateur de cyborgs ?\n🎌One Punch Man🎌", answer: "dr genus" },
  { question: "qui est le principal antagoniste de la saison 2 ?\n🎌One Punch Man🎌", answer: "garou" },
  { question: "quel est le point faible de saitama ?\n🎌One Punch Man🎌", answer: "aucun" },
  { question: "comment saitama a-t-il perdu ses cheveux ?\n🎌One Punch Man🎌", answer: "entraînement intensif" },
  { question: "quel est le nom de l’organisation des héros ?\n🎌One Punch Man🎌", answer: "association des héros" },
  { question: "quelle est la technique de genos ?\n🎌One Punch Man🎌", answer: "cannon incinérateur" },
  { question: "qui est considéré comme le héros le plus beau ?\n🎌One Punch Man🎌", answer: "sweet mask" },
  { question: "quel monstre prétend être immortel ?\n🎌One Punch Man🎌", answer: "zombieman" },
  { question: "quel héros porte une armure technologique ?\n🎌One Punch Man🎌", answer: "metal knight" },
  { question: "quelle est la mission de blast ?\n🎌One Punch Man🎌", answer: "récupérer les cubes dimensionnels" },
  { question: "qui est l’auteur de one punch man ?\n🎌One Punch Man🎌", answer: "one" },
  { question: "quelle est la particularité de garou ?\n🎌One Punch Man🎌", answer: "il évolue constamment" },
  { question: "qui bat boros en un coup ?\n🎌One Punch Man🎌", answer: "saitama" },
  { question: "quelle est la personnalité de fubuki ?\n🎌One Punch Man🎌", answer: "ambitieuse" },
  { question: "qui est l’élève direct de bang ?\n🎌One Punch Man🎌", answer: "garou" },
  { question: "quel est le pouvoir principal de zombieman ?\n🎌One Punch Man🎌", answer: "régénération" },
  { question: "qui possède une force brute immense sans pouvoirs ?\n🎌One Punch Man🎌", answer: "tank top master" },
  { question: "quelle est la faiblesse de tatsumaki ?\n🎌One Punch Man🎌", answer: "sa taille" },
  { question: "qu'est-ce qui rend saitama différent ?\n🎌One Punch Man🎌", answer: "il est trop fort" },
  { question: "quelle est la relation entre genos et saitama ?\n🎌One Punch Man🎌", answer: "maître et élève" },
  { question: "quel héros est classé s mais ne se bat pas souvent ?\n🎌One Punch Man🎌", answer: "king" },
  { question: "quel est le niveau de menace du darkshine ?\n🎌One Punch Man🎌", answer: "dragon" },
  { question: "qui est le bras droit d'orochi ?\n🎌One Punch Man🎌", answer: "gyoro gyoro" },
  { question: "quel est le pouvoir de flashy flash ?\n🎌One Punch Man🎌", answer: "vitesse" },
  { question: "qui est le plus rapide des héros ?\n🎌One Punch Man🎌", answer: "flashy flash" },
  { question: "quel est l’élément déclencheur de la transformation de garou ?\n🎌One Punch Man🎌", answer: "rage" },
  { question: "quelle est la limite de la force de saitama ?\n🎌One Punch Man🎌", answer: "inconnue" },
        
  { question: "quel est le nom du personnage principal de blue lock ?\n🎌Blue Lock🎌", answer: "yoichi isagi" },
  { question: "qui est le créateur du projet blue lock ?\n🎌Blue Lock🎌", answer: "jinpachi ego" },
  { question: "quel est le poste principal d'isagi ?\n🎌Blue Lock🎌", answer: "attaquant" },
  { question: "qui est le premier rival d'isagi dans le projet ?\n🎌Blue Lock🎌", answer: "meguru bachira" },
  { question: "quel est le joueur connu pour son instinct animal ?\n🎌Blue Lock🎌", answer: "bachira" },
  { question: "comment s'appelle le joueur surnommé le roi ?\n🎌Blue Lock🎌", answer: "barou" },
  { question: "quel joueur est connu pour sa vitesse fulgurante ?\n🎌Blue Lock🎌", answer: "chigiri" },
  { question: "qui est le joueur stratégique et manipulateur ?\n🎌Blue Lock🎌", answer: "nagi" },
  { question: "quel est le meilleur buteur du blue lock au début ?\n🎌Blue Lock🎌", answer: "kunigami" },
  { question: "comment s'appelle le coéquipier blond d'isagi ?\n🎌Blue Lock🎌", answer: "nagi" },
  { question: "qui est le partenaire initial de nagi ?\n🎌Blue Lock🎌", answer: "reo" },
  { question: "comment s'appelle le rival principal d'isagi ?\n🎌Blue Lock🎌", answer: "rin" },
  { question: "quel est le frère de rin ?\n🎌Blue Lock🎌", answer: "sae" },
  { question: "dans quelle équipe joue sae itoshi ?\n🎌Blue Lock🎌", answer: "équipe u20" },
  { question: "qui est le leader de l'équipe de barou ?\n🎌Blue Lock🎌", answer: "barou" },
  { question: "quelle est la spécialité de gagamaru ?\n🎌Blue Lock🎌", answer: "réflexes" },
  { question: "quel joueur excelle dans les tirs à longue distance ?\n🎌Blue Lock🎌", answer: "shidou" },
  { question: "quel joueur est connu pour son agressivité extrême ?\n🎌Blue Lock🎌", answer: "shidou" },
  { question: "comment s'appelle le test final de la deuxième sélection ?\n🎌Blue Lock🎌", answer: "match 3 vs 3" },
  { question: "qui forme un duo inattendu avec isagi ?\n🎌Blue Lock🎌", answer: "barou" },
  { question: "qui est l’ennemi juré de rin ?\n🎌Blue Lock🎌", answer: "isagi" },
  { question: "quel est le but du projet blue lock ?\n🎌Blue Lock🎌", answer: "trouver le meilleur attaquant" },
  { question: "quelle est la couleur du bâtiment de blue lock ?\n🎌Blue Lock🎌", answer: "bleu" },
  { question: "quelle est la spécialité d'isagi ?\n🎌Blue Lock🎌", answer: "vision du jeu" },
  { question: "quel est le point faible d’isagi au départ ?\n🎌Blue Lock🎌", answer: "manque de finition" },
  { question: "quelle est l’attente d’ego pour l’attaquant parfait ?\n🎌Blue Lock🎌", answer: "égoïsme" },
  { question: "quel joueur a une coupe rose et rapide ?\n🎌Blue Lock🎌", answer: "chigiri" },
  { question: "quel joueur est surnommé le prince du football ?\n🎌Blue Lock🎌", answer: "reo" },
  { question: "quel joueur utilise une technique appelée direct shot ?\n🎌Blue Lock🎌", answer: "isagi" },
  { question: "quel joueur joue en utilisant son flair ?\n🎌Blue Lock🎌", answer: "bachira" },
  { question: "qui est le meilleur joueur des u20 ?\n🎌Blue Lock🎌", answer: "sae" },
  { question: "qui est le joueur le plus imprévisible ?\n🎌Blue Lock🎌", answer: "nagi" },
  { question: "quel joueur crée ses propres règles ?\n🎌Blue Lock🎌", answer: "barou" },
  { question: "quelle est la position de gagamaru dans les derniers matchs ?\n🎌Blue Lock🎌", answer: "gardien" },
  { question: "quelle qualité ego cherche-t-il le plus ?\n🎌Blue Lock🎌", answer: "égoïsme" },
  { question: "dans quelle sélection isagi affronte-t-il rin ?\n🎌Blue Lock🎌", answer: "deuxième sélection" },
  { question: "quel joueur devient obsédé par l'évolution ?\n🎌Blue Lock🎌", answer: "barou" },
  { question: "quelle technique isagi développe-t-il grâce à barou ?\n🎌Blue Lock🎌", answer: "puzzle spatial" },
  { question: "quel joueur est tactiquement intelligent mais peu doué physiquement ?\n🎌Blue Lock🎌", answer: "isagi" },
  { question: "qui est le rival d’enfance de chigiri ?\n🎌Blue Lock🎌", answer: "tokimitsu" },
  { question: "quel joueur a une peur paralysante de l’échec ?\n🎌Blue Lock🎌", answer: "tokimitsu" },
  { question: "quel joueur est très colérique et brutal ?\n🎌Blue Lock🎌", answer: "shidou" },
  { question: "quel joueur fait preuve d’un calme absolu sur le terrain ?\n🎌Blue Lock🎌", answer: "niko" },
  { question: "comment s'appelle le test final de la troisième sélection ?\n🎌Blue Lock🎌", answer: "match contre les u20" },
  { question: "qui fait une passe décisive cruciale dans le match final ?\n🎌Blue Lock🎌", answer: "isagi" },
  { question: "quelle est la particularité du blue lock eleven ?\n🎌Blue Lock🎌", answer: "joueurs de blue lock contre u20" },
  { question: "quelle est la capacité la plus redoutée d'isagi ?\n🎌Blue Lock🎌", answer: "anticipation" },
  { question: "quelle équipe nagi et reo forment-ils au départ ?\n🎌Blue Lock🎌", answer: "équipe v" },
  { question: "quelle est la mission d’ego avec ce projet ?\n🎌Blue Lock🎌", answer: "révolutionner le football japonais" },
  { question: "quel joueur est misérable mais puissant en duel ?\n🎌Blue Lock🎌", answer: "aryu" },

  { question: "quel est le vrai nom d'aqua dans oshi no ko ?\n🎌Oshi no Ko🎌", answer: "goro amemiya" },
  { question: "qui est la mère biologique de ruby et aqua ?\n🎌Oshi no Ko🎌", answer: "ai hoshino" },
  { question: "quel métier faisait goro avant de mourir ?\n🎌Oshi no Ko🎌", answer: "médecin" },
  { question: "quelle est la profession d'ai hoshino ?\n🎌Oshi no Ko🎌", answer: "idole" },
  { question: "comment ai est-elle morte ?\n🎌Oshi no Ko🎌", answer: "assassinée" },
  { question: "quel est le nom du groupe d'idoles d’ai hoshino ?\n🎌Oshi no Ko🎌", answer: "b komachi" },
  { question: "quelle est l'identité réincarnée de sarina ?\n🎌Oshi no Ko🎌", answer: "ruby" },
  { question: "quelle est la couleur des yeux de ruby et aqua ?\n🎌Oshi no Ko🎌", answer: "étoilée" },
  { question: "dans quel domaine aqua commence-t-il à travailler après l’enfance ?\n🎌Oshi no Ko🎌", answer: "acteur" },
  { question: "quelle est la motivation principale d'aqua ?\n🎌Oshi no Ko🎌", answer: "trouver le père" },
  { question: "qui est l’ami réalisateur d’aqua ?\n🎌Oshi no Ko🎌", answer: "taishi gotanda" },
  { question: "quel est le nom de famille de ruby et aqua ?\n🎌Oshi no Ko🎌", answer: "hoshino" },
  { question: "quel était le rêve de sarina avant sa mort ?\n🎌Oshi no Ko🎌", answer: "devenir idole" },
  { question: "comment goro est-il mort ?\n🎌Oshi no Ko🎌", answer: "assassiné" },
  { question: "quel est le nom du producteur qui aide ruby à relancer b komachi ?\n🎌Oshi no Ko🎌", answer: "miyako" },
  { question: "qui est la collègue de ruby dans le nouveau b komachi ?\n🎌Oshi no Ko🎌", answer: "kana arima" },
  { question: "comment aqua obtient-il des tests adn ?\n🎌Oshi no Ko🎌", answer: "via contacts dans l'industrie" },
  { question: "quel genre d’émission fait kana au début ?\n🎌Oshi no Ko🎌", answer: "comédie" },
  { question: "comment aqua manipule-t-il ses relations pour l'enquête ?\n🎌Oshi no Ko🎌", answer: "en jouant un rôle" },
  { question: "que cherche aqua dans l'industrie du divertissement ?\n🎌Oshi no Ko🎌", answer: "le père d'ai" },
  { question: "quelle idole a été affectée par le harcèlement en ligne ?\n🎌Oshi no Ko🎌", answer: "akane" },
  { question: "comment akane montre-t-elle son talent dans l’émission de télé-réalité ?\n🎌Oshi no Ko🎌", answer: "en jouant ai" },
  { question: "quel est le nom du groupe d’idoles reformé par ruby ?\n🎌Oshi no Ko🎌", answer: "b komachi" },
  { question: "quel est le lien entre aqua et akane ?\n🎌Oshi no Ko🎌", answer: "relation amoureuse" },
  { question: "quel est le nom du lycée fréquenté par ruby et aqua ?\n🎌Oshi no Ko🎌", answer: "yoto high school" },
  { question: "quelle est la passion de ruby ?\n🎌Oshi no Ko🎌", answer: "devenir idole" },
  { question: "quelle actrice est connue pour sa capacité à tout jouer ?\n🎌Oshi no Ko🎌", answer: "kana arima" },
  { question: "quel est le premier grand rôle d’aqua au lycée ?\n🎌Oshi no Ko🎌", answer: "pièce de théâtre" },
  { question: "quelle émission télé est controversée dans oshi no ko ?\n🎌Oshi no Ko🎌", answer: "love now" },
  { question: "quel traumatisme akane surmonte-t-elle ?\n🎌Oshi no Ko🎌", answer: "tentative de suicide" },
  { question: "comment ruby apprend-elle la vérité sur sa mère ?\n🎌Oshi no Ko🎌", answer: "par des vidéos cachées" },
  { question: "quelle est la stratégie d’aqua pour se rapprocher de la vérité ?\n🎌Oshi no Ko🎌", answer: "devenir acteur" },
  { question: "quelle est la particularité visuelle de ruby et aqua ?\n🎌Oshi no Ko🎌", answer: "étoile dans les yeux" },
  { question: "quelle est la société de production dirigée par la femme de ichigo ?\n🎌Oshi no Ko🎌", answer: "ichigo production" },
  { question: "qui était le médecin de sarina ?\n🎌Oshi no Ko🎌", answer: "goro amemiya" },
  { question: "quelle est la relation entre kana et aqua ?\n🎌Oshi no Ko🎌", answer: "collègue et amour secret" },
  { question: "qui découvre en premier l’identité d’aqua ?\n🎌Oshi no Ko🎌", answer: "akane" },
  { question: "quelle est la signification du titre oshi no ko ?\n🎌Oshi no Ko🎌", answer: "l’enfant de son idole" },
  { question: "comment aqua infiltre-t-il des productions ?\n🎌Oshi no Ko🎌", answer: "en acceptant des rôles" },
  { question: "quel est l’événement déclencheur du drame principal ?\n🎌Oshi no Ko🎌", answer: "la mort d’ai" },
  { question: "quel est le surnom de kana dans l’industrie ?\n🎌Oshi no Ko🎌", answer: "enfant prodige" },
  { question: "quelle relation lie ichigo à ai ?\n🎌Oshi no Ko🎌", answer: "manager" },
  { question: "qui est sarina avant sa réincarnation ?\n🎌Oshi no Ko🎌", answer: "patiente en phase terminale" },
  { question: "quelle est la motivation principale de ruby ?\n🎌Oshi no Ko🎌", answer: "honorer ai" },
  { question: "qui aide ruby à reformer b komachi ?\n🎌Oshi no Ko🎌", answer: "miyako" },
  { question: "quel événement unit akane et aqua ?\n🎌Oshi no Ko🎌", answer: "émission love now" },
  { question: "qui est le rival indirect de kana ?\n🎌Oshi no Ko🎌", answer: "akane" },
  { question: "quel est le genre de l’anime oshi no ko ?\n🎌Oshi no Ko🎌", answer: "drame psychologique" },
  { question: "comment aqua manipule-t-il ses sentiments ?\n🎌Oshi no Ko🎌", answer: "stratégie calculée" },
  { question: "qui tient le rôle de soutien émotionnel pour ruby ?\n🎌Oshi no Ko🎌", answer: "kana" },

  { question: "comment s'appelle le personnage principal de the eminence in shadow ?\n🎌The Eminence in Shadow🎌", answer: "cid kagenou" },
  { question: "quel est le nom de l'organisation secrète dirigée par cid ?\n🎌The Eminence in Shadow🎌", answer: "shadow garden" },
  { question: "quel nom cid utilise-t-il lorsqu’il est en civil ?\n🎌The Eminence in Shadow🎌", answer: "cid kagenou" },
  { question: "quel est l’alias de cid lorsqu’il agit dans l’ombre ?\n🎌The Eminence in Shadow🎌", answer: "shadow" },
  { question: "quelle est la première membre recrutée par cid ?\n🎌The Eminence in Shadow🎌", answer: "alpha" },
  { question: "quelle est la spécialité de beta ?\n🎌The Eminence in Shadow🎌", answer: "écriture" },
  { question: "quelle membre est une épéiste à deux lames ?\n🎌The Eminence in Shadow🎌", answer: "zeta" },
  { question: "quel est le but supposé de shadow garden ?\n🎌The Eminence in Shadow🎌", answer: "détruire culte de diabolos" },
  { question: "quel est le nom du groupe ennemi principal ?\n🎌The Eminence in Shadow🎌", answer: "culte de diabolos" },
  { question: "qui est alpha dans sa vie d’avant ?\n🎌The Eminence in Shadow🎌", answer: "une elfe malade" },
  { question: "quelle est la couleur des cheveux de gamma ?\n🎌The Eminence in Shadow🎌", answer: "bleu" },
  { question: "quelle est la faiblesse physique de gamma ?\n🎌The Eminence in Shadow🎌", answer: "maladroite" },
  { question: "quelle boutique cid a-t-il fondée dans le monde ?\n🎌The Eminence in Shadow🎌", answer: "midgar maison" },
  { question: "comment s’appelle la princesse que cid sauve accidentellement ?\n🎌The Eminence in Shadow🎌", answer: "alexia midgar" },
  { question: "quelle relation lie cid et claire ?\n🎌The Eminence in Shadow🎌", answer: "frère et sœur" },
  { question: "quel est le nom de l’élève noble qui hait cid ?\n🎌The Eminence in Shadow🎌", answer: "zenon" },
  { question: "quelle est la capacité principale de cid au combat ?\n🎌The Eminence in Shadow🎌", answer: "magie noire" },
  { question: "qui est epsilon ?\n🎌The Eminence in Shadow🎌", answer: "membre élégante de shadow garden" },
  { question: "combien de membres principales forment l’élite de shadow garden ?\n🎌The Eminence in Shadow🎌", answer: "sept" },
  { question: "comment s’appelle le royaume où l’histoire commence ?\n🎌The Eminence in Shadow🎌", answer: "midgar" },
  { question: "quel type de roman beta écrit-elle ?\n🎌The Eminence in Shadow🎌", answer: "romance" },
  { question: "quelle est la vraie nature du culte de diabolos ?\n🎌The Eminence in Shadow🎌", answer: "expérimentations magiques" },
  { question: "quelle est l’armure portée par shadow ?\n🎌The Eminence in Shadow🎌", answer: "armure noire magique" },
  { question: "quelle élève du royaume devient une proche de cid malgré elle ?\n🎌The Eminence in Shadow🎌", answer: "alexia" },
  { question: "qui est eta dans shadow garden ?\n🎌The Eminence in Shadow🎌", answer: "la scientifique" },
  { question: "comment s’appelle le groupe que cid invente de toutes pièces ?\n🎌The Eminence in Shadow🎌", answer: "culte de diabolos" },
  { question: "qui est la membre silencieuse et furtive du groupe ?\n🎌The Eminence in Shadow🎌", answer: "delta" },
  { question: "comment s'appelle la sœur de cid ?\n🎌The Eminence in Shadow🎌", answer: "claire kagenou" },
  { question: "quelle est la réputation publique de cid ?\n🎌The Eminence in Shadow🎌", answer: "étudiant médiocre" },
  { question: "quelle est la personnalité de zeta ?\n🎌The Eminence in Shadow🎌", answer: "calme et efficace" },
  { question: "quels sont les objectifs de shadow garden selon les rumeurs ?\n🎌The Eminence in Shadow🎌", answer: "illuminatis" },
  { question: "dans quel genre cid veut-il exceller ?\n🎌The Eminence in Shadow🎌", answer: "l’ombre" },
  { question: "comment cid voit-il ses actions héroïques ?\n🎌The Eminence in Shadow🎌", answer: "jeu de rôle" },
  { question: "quelle capacité a epsilon au combat ?\n🎌The Eminence in Shadow🎌", answer: "manipulation magique" },
  { question: "comment gamma devient-elle célèbre ?\n🎌The Eminence in Shadow🎌", answer: "commerce de livres" },
  { question: "que veut dire 'the eminence in shadow' ?\n🎌The Eminence in Shadow🎌", answer: "l’éminence dans l’ombre" },
  { question: "quelle est la puissance de shadow comparée aux autres ?\n🎌The Eminence in Shadow🎌", answer: "surpuissant" },
  { question: "qui est rose oriana ?\n🎌The Eminence in Shadow🎌", answer: "princesse d’un autre royaume" },
  { question: "dans quel genre se situe l'anime ?\n🎌The Eminence in Shadow🎌", answer: "action comédie isekai" },
  { question: "quelle est la devise de cid ?\n🎌The Eminence in Shadow🎌", answer: "agir dans l’ombre" },
  { question: "quel personnage est connu pour son obsession de shadow ?\n🎌The Eminence in Shadow🎌", answer: "epsilon" },
  { question: "quelle est la capitale du royaume de midgar ?\n🎌The Eminence in Shadow🎌", answer: "midgar city" },
  { question: "qui est le mentor de cid dans sa vie passée ?\n🎌The Eminence in Shadow🎌", answer: "aucun" },
  { question: "qui sont les principales cibles de shadow garden ?\n🎌The Eminence in Shadow🎌", answer: "culte de diabolos" },
  { question: "quel est l’autre nom de gamma ?\n🎌The Eminence in Shadow🎌", answer: "la belle endormie" },
  { question: "qui gère les finances de shadow garden ?\n🎌The Eminence in Shadow🎌", answer: "gamma" },
  { question: "quelle membre est obsédée par la perfection physique ?\n🎌The Eminence in Shadow🎌", answer: "epsilon" },
  { question: "quel est l’arme favorite de delta ?\n🎌The Eminence in Shadow🎌", answer: "griffes" },
  { question: "comment s'appelle le monde dans lequel cid est réincarné ?\n🎌The Eminence in Shadow🎌", answer: "aucun nom officiel" },
  { question: "que signifie le mot 'shadow' dans ce contexte ?\n🎌The Eminence in Shadow🎌", answer: "celui qui agit dans l’ombre" },
  { question: "qui est responsable de la formation magique dans shadow garden ?\n🎌The Eminence in Shadow🎌", answer: "eta" }



];

const activeSessions = {};

module.exports = {
  config: {
    name: "quizz-manga",
    role: "0",
    author: "Merdi Madimba or Bryan Bulakali",
    version: "1.0",
    description: "Quiz culture générale avec score",
    category: "🎮 Jeu"
  },

  onStart: async function ({ event, message, usersData }) {
    const threadID = event.threadID;

    if (activeSessions[threadID]) {
      return message.reply("❗ Un quiz est déjà en cours !");
    }

    // Sélectionner 10 questions aléatoires
    const selected = [...questions].sort(() => 0.5 - Math.random()).slice(0, 50);
    const scores = {};

    let currentIndex = 0;
    let currentQuestion = null;
    let timeoutID = null;
    let answered = false;

    const sendQuestion = async () => {
      if (currentIndex >= selected.length) {
        // Fin du quiz
        const sorted = Object.entries(scores).sort((a, b) => b[1] - a[1]);
        let finalBoard = "🏁 Fin du quiz ! Résultat final :\n";
        let winner = sorted[0]?.[0] || "Aucun";

        for (let [name, pts] of sorted) {
          finalBoard += `🏅 ${name} : ${pts} pts\n`;
        }

        finalBoard += `👑 Vainqueur : ${winner}`;
        await message.send(finalBoard);
        delete activeSessions[threadID];
        return;
      }

      answered = false;
      currentQuestion = selected[currentIndex];

      await message.send(`❓ Question ${currentIndex + 1} : ${currentQuestion.question}`);

      timeoutID = setTimeout(async () => {
        if (!answered) {
          await message.send(`⏰ Temps écoulé ! La bonne réponse était : ${currentQuestion.answer}`);
          currentIndex++;
          sendQuestion();
        }
      }, 10000);
    };

    activeSessions[threadID] = async ({ event, message }) => {
      if (!currentQuestion || answered) return;

      const senderName = await usersData.getName(event.senderID);
      const msg = event.body?.toLowerCase().trim();

      if (msg === currentQuestion.answer) {
        answered = true;
        clearTimeout(timeoutID);

        scores[senderName] = (scores[senderName] || 0) + 10;

        // Scoreboard
        let board = "📊 Score actuel :\n";
        for (let [name, pts] of Object.entries(scores)) {
          board += `🏅 ${name} : ${pts} pts\n`;
        }

        await message.reply(`✅ Bonne réponse de ${senderName} !\n\n${board}`);
        currentIndex++;
        setTimeout(sendQuestion, 1000);
      }
    };

    sendQuestion();
  },

  onChat: function (context) {
    const handler = activeSessions[context.event.threadID];
    if (handler) handler(context);
  }
};
